// Generated by scripts/generate-deployable-runtimes.mjs. Do not edit by hand.

import { collectProjectors, resolveModuleProjectionGroups, resolveModuleSubscriptions } from "@chase-sets/bounded-context-runtime";
import type { PgTransactionalPool } from "@chase-sets/event-core-postgres";
import { module as catalogModule } from "@chase-sets/catalog";

export type ContextRuntimePools = Readonly<{
  catalog: PgTransactionalPool;
}>;

export type ContextRuntimeServices = Readonly<{
  catalog: ReturnType<typeof catalogModule.createServices>;
}>;

export type ContextRuntimeHostPorts = Readonly<Record<string, never>>;

export function createContextRuntime(
  pools: ContextRuntimePools,
  hostPorts: ContextRuntimeHostPorts = {} as ContextRuntimeHostPorts,
) {
  const services = {} as Record<string, unknown> as {
  catalog: ReturnType<typeof catalogModule.createServices>;
  };

  services.catalog = catalogModule.createServices(pools.catalog, undefined);

  const mountedContexts = [
    {
      contextName: "catalog",
      mountRole: "active",
      module: catalogModule,
      services: services.catalog,
      pool: pools.catalog,
      projectors: catalogModule.projectors(services.catalog),
    },
  ] as const;

  const mountedModules = [
    { module: catalogModule, services: services.catalog },
  ] as const;

  const subscriptionRunners = resolveModuleSubscriptions(mountedContexts);
  const projectionGroups = resolveModuleProjectionGroups(
    mountedContexts,
    subscriptionRunners,
  );

  return {
    mountedContexts,
    mountedModules,
    services: services as ContextRuntimeServices,
    projectors: collectProjectors([
    services.catalog,
    ]),
    projectionGroups,
    subscriptionRunners,
  };
}
