// Generated by scripts/generate-deployable-api-mounts.mjs. Do not edit by hand.

import { resolveModuleApiMounts, type ResolvedApiMount } from "@chase-sets/bounded-context-runtime";
import { module as CatalogModule } from "@chase-sets/catalog";

export function createContextApiMounts(
  services: ReturnType<typeof CatalogModule.createServices>,
): readonly ResolvedApiMount[] {
  return resolveModuleApiMounts(CatalogModule, services);
}
