// Generated by scripts/generate-deployable-runtimes.mjs. Do not edit by hand.

import { collectProjectors } from "@chase-sets/bounded-context-runtime";
import type { PgTransactionalPool } from "@chase-sets/event-core-postgres";
import { module as catalogModule } from "@chase-sets/catalog";


export type ContextRuntimeServices = Readonly<{
  catalog: ReturnType<typeof catalogModule.createServices>;
}>;

export type ContextRuntimeHostPorts = Readonly<Record<string, never>>;

export function createContextRuntime(
  pool: PgTransactionalPool,
  hostPorts: ContextRuntimeHostPorts = {} as ContextRuntimeHostPorts,
) {
  const services = {} as Record<string, unknown> as {
  catalog: ReturnType<typeof catalogModule.createServices>;
  };

  services.catalog = catalogModule.createServices(pool, undefined);

  const mountedModules = [
    { module: catalogModule, services: services.catalog },
  ] as const;

  return {
    mountedModules,
    services: services as ContextRuntimeServices,
    projectors: collectProjectors([
    services.catalog,
    ]),
  };
}
