// Generated by scripts/generate-deployable-api-mounts.mjs. Do not edit by hand.

import type { ResolvedApiMount } from "@chase-sets/bounded-context-runtime";
import { resolveApiMounts as resolveCatalogApiMounts } from "@chase-sets/catalog";

export function createContextApiMounts(
  services: Parameters<typeof resolveCatalogApiMounts>[0],
): readonly ResolvedApiMount[] {
  return resolveCatalogApiMounts(services);
}
