export default {
  id: "buyer",
  routeScope: [
    "^bounded-contexts/checkout/routes/(account-cart|checkout-session|checkout-start|buy-checkout-confirmation)\\.tsx$",
    "^bounded-contexts/payments/routes/marketplace/",
    "^bounded-contexts/ordering/routes/account-purchases?\\.tsx$",
    "^bounded-contexts/fulfillment/routes/marketplace/account-shipments?\\.tsx$",
    "^bounded-contexts/marketplace/routes/account-offers?-",
    "^bounded-contexts/marketplace/routes/marketplace/(account-purchase-review|account-review|account-written-reviews|account-review-summary)\\.tsx$",
    "^bounded-contexts/discovery/routes/account-product-alerts\\.tsx$",
    "^bounded-contexts/notifications/routes/account-notifications\\.tsx$",
    "^bounded-contexts/identity/routes/marketplace/(account|account-security|account-consents|account-shipping-addresses)\\.tsx$",
    "^bounded-contexts/auth/routes/marketplace/account-",
    "^bounded-contexts/platform-operations/routes/marketplace/",
  ],
  goals: [
    {
      id: "find-card",
      version: 1,
      startPath: "/",
      role: "buyer",
      host: "marketplace",
      goal: "Find an English Base Set Charizard, raw and Near Mint. Determine whether you can buy that variant now and at what price. Do not add it to a cart or buy it. Report unavailable information rather than guessing.",
      checks: ["variant", "availability-and-price"],
      oracle: {
        variant: "Reobserve the actual variant against authoritative fixture data.",
        "availability-and-price": "Reobserve the actual availability and price against authoritative fixture data.",
      },
      routes: {},
      paths: ["bounded-contexts/discovery/", "bounded-contexts/catalog/"],
      selectOnSharedChange: true,
    },
    {
      id: "buyer-shipment",
      version: 1,
      startPath: "/account",
      role: "buyer",
      host: "marketplace",
      goal: "Find the Twilight Masquerade Elite Trainer Box shipment with tracking reference 1ZSEEDREVIEWELIGIBLE. Determine whether and when it was delivered, and reach the place to report a problem for the correct purchase. Do not submit a report, send a message, review, or buy anything.",
      checks: ["shipment-identity", "delivery-status-and-time", "problem-entry"],
      oracle: {
        "shipment-identity": "Reobserve the actual shipment identity against authoritative fixture data.",
        "delivery-status-and-time": "Reobserve the actual delivery status and time against authoritative fixture data.",
        "problem-entry": "Reaching generic instructions is not reaching the correct report form.",
      },
      routes: {
        "bounded-contexts/fulfillment/routes/marketplace/account-shipments.tsx": "shipment-identity",
        "bounded-contexts/fulfillment/routes/marketplace/account-shipment.tsx": "delivery-status-and-time",
      },
      paths: ["bounded-contexts/fulfillment/", "bounded-contexts/ordering/", "bounded-contexts/platform-operations/"],
      selectOnSharedChange: true,
    },
  ],
  excludedRoutes: [],
};
