export default {
  id: "guest",
  routeScope: [
    "^bounded-contexts/public-presence/routes/(marketplace|developers)/",
    "^bounded-contexts/commercial-terms/routes/public/",
    "^bounded-contexts/discovery/routes/(search|set|item-detail|item-detail-market-history|public-account|public-listing)\\.tsx$",
    "^bounded-contexts/pricing/routes/marketplace/market-price-history\\.tsx$",
    "^bounded-contexts/auth/routes/marketplace/(sign-in|sign-in-magic|register|invite|sign-out|guest-checkout-exit)\\.tsx$",
    "^deployables/(marketplace|public-web)/app/routes/",
  ],
  goals: [
    {
      id: "condition-policy",
      version: 1,
      startPath: "/help",
      role: "guest",
      host: "marketplace",
      goal: "A card arrived in worse condition than its listing. Find where to report it, the reporting deadline after delivery, and who pays return shipping. Do not open a case or contact anyone. Explain any uncertainty or inconsistent guidance.",
      checks: ["report-location", "deadline", "return-shipping"],
      oracle: {
        "report-location":
          "Compare the report location against the authoritative policy, not just the participant's first page.",
        deadline:
          "Compare the reporting deadline against the authoritative policy, not just the participant's first page.",
        "return-shipping":
          "Compare return shipping responsibility against the authoritative policy, not just the participant's first page.",
      },
      routes: {
        "bounded-contexts/public-presence/routes/marketplace/help.tsx": "report-location",
        "bounded-contexts/public-presence/routes/marketplace/help-article.tsx": "deadline",
        "bounded-contexts/public-presence/routes/marketplace/refunds-and-returns.tsx": "return-shipping",
      },
      paths: ["bounded-contexts/public-presence/", "bounded-contexts/settlement/"],
      selectOnSharedChange: true,
    },
    {
      id: "landing-waitlist",
      version: 1,
      startPath: "/",
      role: "guest",
      host: "public-web",
      goal: "landing and waitlist signup (public-web)",
      checks: ["landing", "waitlist-signup"],
      oracle: {
        landing: "Revisit the public landing page and confirm its visible sections.",
        "waitlist-signup": "Confirm the waitlist signup form is reachable; do not submit it.",
      },
      routes: {
        "bounded-contexts/public-presence/routes/marketplace/home.tsx": "landing",
      },
      paths: ["bounded-contexts/public-presence/features/waitlist/"],
    },
    {
      id: "search-set-browsing",
      version: 1,
      startPath: "/search",
      role: "guest",
      host: "marketplace",
      goal: "search, filters, and set browsing",
      checks: ["search", "set-browsing"],
      oracle: {
        search: "Compare visible search results against representative commerce bootstrap state.",
        "set-browsing": "Revisit the selected set and confirm its displayed catalog state.",
      },
      routes: {
        "bounded-contexts/discovery/routes/search.tsx": "search",
        "bounded-contexts/discovery/routes/set.tsx": "set-browsing",
        "deployables/marketplace/app/routes/index.tsx": "search",
      },
      paths: ["bounded-contexts/discovery/", "contracts/catalog-seed/representative-commerce-state.ts"],
    },
    {
      id: "item-market-history",
      version: 1,
      startPath: "/search",
      role: "guest",
      host: "marketplace",
      goal: "item detail with market and price history",
      checks: ["item-detail", "market-history"],
      oracle: {
        "item-detail": "Compare the displayed item with representative commerce bootstrap state.",
        "market-history": "Compare displayed market and price history with the available read model.",
      },
      routes: {
        "bounded-contexts/discovery/routes/item-detail.tsx": "item-detail",
        "bounded-contexts/discovery/routes/item-detail-market-history.tsx": "market-history",
        "bounded-contexts/pricing/routes/marketplace/market-price-history.tsx": "market-history",
      },
      paths: ["bounded-contexts/discovery/", "bounded-contexts/pricing/", "contracts/catalog-seed/representative-commerce-state.ts"],
    },
    {
      id: "public-seller-listing",
      version: 1,
      startPath: "/search",
      role: "guest",
      host: "marketplace",
      goal: "public seller account and public listing",
      checks: ["public-account", "public-listing"],
      oracle: {
        "public-account": "Compare the displayed public account with representative commerce bootstrap state.",
        "public-listing": "Compare the displayed public listing with representative commerce bootstrap state.",
      },
      routes: {
        "bounded-contexts/discovery/routes/public-account.tsx": "public-account",
        "bounded-contexts/discovery/routes/public-listing.tsx": "public-listing",
      },
      paths: ["bounded-contexts/discovery/", "contracts/catalog-seed/representative-commerce-state.ts"],
    },
    {
      id: "help-center",
      version: 1,
      startPath: "/help",
      role: "guest",
      host: "public-web",
      goal: "help center (home, category, article)",
      checks: ["help-home", "help-category", "help-article"],
      oracle: {
        "help-home": "Confirm the help center home content from the published help articles.",
        "help-category": "Confirm the category content against the published help articles.",
        "help-article": "Compare the article answer against its authoritative policy or help source.",
      },
      routes: {
        "bounded-contexts/public-presence/routes/marketplace/help.tsx": "help-home",
        "bounded-contexts/public-presence/routes/marketplace/help-category.tsx": "help-category",
        "bounded-contexts/public-presence/routes/marketplace/help-article.tsx": "help-article",
      },
      paths: ["bounded-contexts/public-presence/features/help/"],
    },
    {
      id: "policy-pages",
      version: 1,
      startPath: "/terms",
      role: "guest",
      host: "public-web",
      goal: "policy pages (terms, privacy, refunds and returns, order protection, seller agreement, payments, authenticity, agent terms, sales fees)",
      checks: ["policy-text", "refunds-redirect"],
      oracle: {
        "policy-text": "Compare each displayed policy with its authoritative policy text.",
        "refunds-redirect": "Confirm the route redirects to the published refunds and returns article.",
      },
      routes: {
        "bounded-contexts/public-presence/routes/marketplace/terms.tsx": "policy-text",
        "bounded-contexts/public-presence/routes/marketplace/privacy.tsx": "policy-text",
        "bounded-contexts/public-presence/routes/marketplace/refunds-and-returns.tsx": "refunds-redirect",
        "bounded-contexts/public-presence/routes/marketplace/order-protection.tsx": "policy-text",
        "bounded-contexts/public-presence/routes/marketplace/seller-agreement.tsx": "policy-text",
        "bounded-contexts/public-presence/routes/marketplace/payments-terms.tsx": "policy-text",
        "bounded-contexts/public-presence/routes/marketplace/authenticity-terms.tsx": "policy-text",
        "bounded-contexts/public-presence/routes/marketplace/agent-terms.tsx": "policy-text",
        "bounded-contexts/commercial-terms/routes/public/sales-fees.tsx": "policy-text",
      },
      paths: ["bounded-contexts/public-presence/features/policies/", "bounded-contexts/commercial-terms/"],
    },
    {
      id: "compare-marketplaces",
      version: 1,
      startPath: "/compare/ebay",
      role: "guest",
      host: "public-web",
      goal: "compare-eBay and compare-TCGplayer",
      checks: ["comparison-content"],
      oracle: { "comparison-content": "Compare displayed claims with their cited comparison sources." },
      routes: {
        "bounded-contexts/public-presence/routes/marketplace/compare-ebay.tsx": "comparison-content",
        "bounded-contexts/public-presence/routes/marketplace/compare-tcgplayer.tsx": "comparison-content",
      },
      paths: ["bounded-contexts/public-presence/features/"],
    },
    {
      id: "company-information",
      version: 1,
      startPath: "/founders",
      role: "guest",
      host: "public-web",
      goal: "founders, press, FAQ, contact",
      checks: ["company-information"],
      oracle: { "company-information": "Compare displayed company information with the published page content." },
      routes: {
        "bounded-contexts/public-presence/routes/marketplace/founders.tsx": "company-information",
        "bounded-contexts/public-presence/routes/marketplace/press.tsx": "company-information",
        "bounded-contexts/public-presence/routes/marketplace/faq.tsx": "company-information",
        "bounded-contexts/public-presence/routes/marketplace/contact.tsx": "company-information",
      },
      paths: ["bounded-contexts/public-presence/routes/marketplace/"],
    },
    {
      id: "developer-portal",
      version: 1,
      startPath: "/developers",
      role: "guest",
      host: "public-web",
      goal: "developer portal, articles, manifest",
      checks: ["developer-content", "manifest"],
      oracle: {
        "developer-content": "Compare the developer portal and article content with published developer documentation.",
        manifest: "Compare the manifest with the published developer portal metadata.",
      },
      routes: {
        "bounded-contexts/public-presence/routes/developers/portal.tsx": "developer-content",
        "bounded-contexts/public-presence/routes/developers/article.tsx": "developer-content",
        "bounded-contexts/public-presence/routes/developers/llms.tsx": "developer-content",
        "bounded-contexts/public-presence/routes/developers/manifest.tsx": "manifest",
      },
      paths: ["bounded-contexts/public-presence/features/developer-portal/"],
    },
    {
      id: "sign-in-magic-link",
      version: 1,
      startPath: "/sign-in",
      role: "guest",
      host: "marketplace",
      startSignedIn: false,
      goal: "sign in, magic link",
      checks: ["sign-in-screen", "magic-link-screen"],
      oracle: {
        "sign-in-screen": "Confirm the sign-in screen is reached; do not enter credentials.",
        "magic-link-screen": "Confirm the magic-link screen is reached; do not request or send a link.",
      },
      routes: {
        "bounded-contexts/auth/routes/marketplace/sign-in.tsx": "sign-in-screen",
        "bounded-contexts/auth/routes/marketplace/sign-in-magic.tsx": "magic-link-screen",
      },
      paths: ["bounded-contexts/auth/routes/marketplace/"],
    },
    {
      id: "registration",
      version: 1,
      startPath: "/register",
      role: "guest",
      host: "marketplace",
      startSignedIn: false,
      goal: "register",
      checks: ["registration-screen"],
      oracle: { "registration-screen": "Confirm the registration screen is reached; stop before credential entry or submission." },
      routes: {
        "bounded-contexts/auth/routes/marketplace/register.tsx": "registration-screen",
      },
      paths: ["bounded-contexts/auth/routes/marketplace/"],
    },
    {
      id: "sign-out-guest-checkout-exit",
      version: 1,
      startPath: "/account",
      role: "guest",
      host: "marketplace",
      startSignedIn: true,
      goal: "sign out, guest checkout exit",
      checks: ["sign-out"],
      oracle: {
        "sign-out": "Confirm the moderator signs out the synthetic account and restores its starting session.",
      },
      routes: {
        "bounded-contexts/auth/routes/marketplace/sign-out.tsx": "sign-out",
      },
      paths: ["bounded-contexts/auth/routes/marketplace/"],
    },
  ],
  excludedRoutes: [
    {
      path: "bounded-contexts/public-presence/routes/marketplace/welcome.tsx",
      reason: "fixture-gap: no seeded waitlist signup id",
    },
    {
      path: "bounded-contexts/auth/routes/marketplace/invite.tsx",
      reason: "fixture-gap: no seeded guest invitation token",
    },
    {
      path: "bounded-contexts/auth/routes/marketplace/guest-checkout-exit.tsx",
      reason: "fixture-gap: no seeded guest checkout session",
    },
    { path: "deployables/marketplace/app/routes/layout.tsx", reason: "layout-only" },
    { path: "deployables/marketplace/app/routes/not-found.tsx", reason: "error-page" },
    { path: "deployables/marketplace/app/routes/offline.tsx", reason: "error-page" },
    { path: "deployables/public-web/app/routes/not-found.tsx", reason: "error-page" },
  ],
};
