// Generated by scripts/sync-workspace-metadata.mjs. Do not edit by hand.

import { catalogAttentionQueueEnglishTranslations } from "./catalog/attention-queue";
import { catalogBlueprintsEnglishTranslations } from "./catalog/blueprints";
import { catalogItemsEnglishTranslations } from "./catalog/catalog-items";
import { catalogCategoriesEnglishTranslations } from "./catalog/categories";
import { catalogComponentsEnglishTranslations } from "./catalog/components";
import { catalogDimensionsEnglishTranslations } from "./catalog/dimensions";
import { catalogDisplayTemplatesEnglishTranslations } from "./catalog/display-templates";
import { catalogFieldsEnglishTranslations } from "./catalog/fields";
import { catalogProviderScopeDiscoveryEnglishTranslations } from "./catalog/provider-scope-discovery";
import { catalogProviderScopeMappingEnglishTranslations } from "./catalog/provider-scope-mapping";
import { catalogReferenceDataEnglishTranslations } from "./catalog/reference-data";
import { catalogRoutesEnglishTranslations } from "./catalog/routes";
import { catalogScopeRegistryEnglishTranslations } from "./catalog/scope-registry";
import { catalogScopeSyncBatchesEnglishTranslations } from "./catalog/scope-sync-batches";
import { catalogSourceObservationsAliasReviewEnglishTranslations } from "./catalog/source-observations-alias-review";
import { catalogSourceObservationsApiDetailMappingEnglishTranslations } from "./catalog/source-observations-api-detail-mapping";
import { catalogSourceObservationsControlPlaneEnglishTranslations } from "./catalog/source-observations-control-plane";
import { catalogSourceObservationsScopeDetailEnglishTranslations } from "./catalog/source-observations-scope-detail";
import { catalogSourceObservationsScopeLandingEnglishTranslations } from "./catalog/source-observations-scope-landing";
import { catalogSourceObservationsWorkbenchHealthCopyEnglishTranslations } from "./catalog/source-observations-workbench-health-copy";
import { catalogSourceObservationsWorkbenchOperationsEnglishTranslations } from "./catalog/source-observations-workbench-operations";
import { catalogSourceObservationsWorkbenchProfileValidationEnglishTranslations } from "./catalog/source-observations-workbench-profile-validation";
import { catalogSourceObservationsWorkbenchProviderDetailEnglishTranslations } from "./catalog/source-observations-workbench-provider-detail";
import { catalogSupportEnglishTranslations } from "./catalog/support";

export const catalogEnglishTranslations = {
  ...catalogAttentionQueueEnglishTranslations,
  ...catalogBlueprintsEnglishTranslations,
  ...catalogItemsEnglishTranslations,
  ...catalogCategoriesEnglishTranslations,
  ...catalogComponentsEnglishTranslations,
  ...catalogDimensionsEnglishTranslations,
  ...catalogDisplayTemplatesEnglishTranslations,
  ...catalogFieldsEnglishTranslations,
  ...catalogProviderScopeDiscoveryEnglishTranslations,
  ...catalogProviderScopeMappingEnglishTranslations,
  ...catalogReferenceDataEnglishTranslations,
  ...catalogRoutesEnglishTranslations,
  ...catalogScopeRegistryEnglishTranslations,
  ...catalogScopeSyncBatchesEnglishTranslations,
  ...catalogSourceObservationsAliasReviewEnglishTranslations,
  ...catalogSourceObservationsApiDetailMappingEnglishTranslations,
  ...catalogSourceObservationsControlPlaneEnglishTranslations,
  ...catalogSourceObservationsScopeDetailEnglishTranslations,
  ...catalogSourceObservationsScopeLandingEnglishTranslations,
  ...catalogSourceObservationsWorkbenchHealthCopyEnglishTranslations,
  ...catalogSourceObservationsWorkbenchOperationsEnglishTranslations,
  ...catalogSourceObservationsWorkbenchProfileValidationEnglishTranslations,
  ...catalogSourceObservationsWorkbenchProviderDetailEnglishTranslations,
  ...catalogSupportEnglishTranslations,
} as const;
