services:
  postgres:
    container_name: chase-sets-postgres-dev
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - chase-sets-postgres-dev-data:/var/lib/postgresql/data

volumes:
  chase-sets-postgres-dev-data:
