import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./bounded-contexts/**/*.{ts,tsx}",
    "./packages/design-system/src/**/*.{ts,tsx}",
    "./deployables/admin-web/app/**/*.{ts,tsx}",
    "./deployables/admin-web/src/**/*.{ts,tsx}",
    "./deployables/marketplace/app/**/*.{ts,tsx}",
    "./deployables/marketplace/src/**/*.{ts,tsx}",
    "./deployables/marketplace/index.html",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-2": "var(--color-surface-2)",
        "surface-3": "var(--color-surface-3)",
        elevated: "var(--color-elevated-surface)",
        border: "var(--color-border)",
        muted: "var(--color-muted-border)",
        foreground: "var(--color-text-primary)",
        secondary: "var(--color-text-secondary)",
        tertiary: "var(--color-text-tertiary)",
        disabled: "var(--color-text-disabled)",
        inverse: "var(--color-text-inverse)",
        brand: "var(--color-brand-primary)",
        "brand-2": "var(--color-brand-secondary)",
        accent: "var(--color-accent)",
        "accent-2": "var(--color-accent-2)",
        "accent-soft": "var(--color-accent-soft)",
        "accent-contrast": "var(--color-accent-contrast)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-active": "var(--color-accent-active)",
        success: "var(--color-success)",
        "success-soft": "var(--color-success-soft)",
        "success-hover": "var(--color-success-hover)",
        "success-active": "var(--color-success-active)",
        "success-contrast": "var(--color-success-contrast)",
        warning: "var(--color-warning)",
        "warning-soft": "var(--color-warning-soft)",
        "warning-hover": "var(--color-warning-hover)",
        "warning-active": "var(--color-warning-active)",
        "warning-contrast": "var(--color-warning-contrast)",
        danger: "var(--color-danger)",
        "danger-soft": "var(--color-danger-soft)",
        "danger-hover": "var(--color-danger-hover)",
        "danger-active": "var(--color-danger-active)",
        "danger-contrast": "var(--color-danger-contrast)",
        info: "var(--color-info)",
        "info-soft": "var(--color-info-soft)",
        "info-hover": "var(--color-info-hover)",
        "info-active": "var(--color-info-active)",
        "info-contrast": "var(--color-info-contrast)",
        trust: "var(--color-trust)",
        "trust-soft": "var(--color-trust-soft)",
        deal: "var(--color-deal)",
        "deal-soft": "var(--color-deal-soft)",
        rating: "var(--color-rating)",
        "rating-soft": "var(--color-rating-soft)",
        focus: "var(--color-focus-ring)",
      },
      fontFamily: {
        display: ["var(--font-display)", "ui-sans-serif", "system-ui"],
        heading: ["var(--font-heading)", "ui-sans-serif", "system-ui"],
        body: ["var(--font-body)", "ui-sans-serif", "system-ui"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      fontSize: {
        "3xs": ["var(--font-size-3xs)", { lineHeight: "var(--line-height-3xs)" }],
        "2xs": ["var(--font-size-2xs)", { lineHeight: "var(--line-height-2xs)" }],
        xs: ["var(--font-size-xs)", { lineHeight: "var(--line-height-xs)" }],
        sm: ["var(--font-size-sm)", { lineHeight: "var(--line-height-sm)" }],
        base: ["var(--font-size-base)", { lineHeight: "var(--line-height-base)" }],
        lg: ["var(--font-size-lg)", { lineHeight: "var(--line-height-lg)" }],
        xl: ["var(--font-size-xl)", { lineHeight: "var(--line-height-xl)" }],
        "2xl": ["var(--font-size-2xl)", { lineHeight: "var(--line-height-2xl)" }],
        "3xl": ["var(--font-size-3xl)", { lineHeight: "var(--line-height-3xl)" }],
        "4xl": ["var(--font-size-4xl)", { lineHeight: "var(--line-height-4xl)" }],
        "5xl": ["var(--font-size-5xl)", { lineHeight: "var(--line-height-5xl)" }],
      },
      lineHeight: {
        "3xs": "var(--line-height-3xs)",
        "2xs": "var(--line-height-2xs)",
        xs: "var(--line-height-xs)",
        sm: "var(--line-height-sm)",
        base: "var(--line-height-base)",
        lg: "var(--line-height-lg)",
        xl: "var(--line-height-xl)",
        "2xl": "var(--line-height-2xl)",
        "3xl": "var(--line-height-3xl)",
        "4xl": "var(--line-height-4xl)",
        "5xl": "var(--line-height-5xl)",
        none: "var(--line-height-none)",
        tight: "var(--line-height-tight)",
        snug: "var(--line-height-snug)",
        normal: "var(--line-height-normal)",
        relaxed: "var(--line-height-relaxed)",
        display: "var(--line-height-display)",
        hero: "var(--line-height-hero)",
        badge: "var(--line-height-badge)",
      },
      letterSpacing: {
        none: "var(--letter-spacing-none)",
        normal: "var(--letter-spacing-normal)",
        wide: "var(--letter-spacing-wide)",
        label: "var(--letter-spacing-label)",
      },
      boxShadow: {
        tokenSm: "var(--shadow-sm)",
        tokenMd: "var(--shadow-md)",
        tokenLg: "var(--shadow-lg)",
        overlay: "var(--shadow-overlay)",
      },
      borderRadius: {
        tokenSm: "var(--radius-sm)",
        tokenMd: "var(--radius-md)",
        tokenLg: "var(--radius-lg)",
        tokenXl: "var(--radius-xl)",
        tokenFull: "var(--radius-full)",
      },
      borderWidth: {
        tokenNone: "var(--border-width-0)",
        tokenSm: "var(--border-width-sm)",
        tokenMd: "var(--border-width-md)",
        tokenLg: "var(--border-width-lg)",
      },
      opacity: {
        disabled: "var(--opacity-disabled)",
        overlay: "var(--opacity-overlay)",
      },
      spacing: {
        0: "var(--space-0)",
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        9: "var(--space-9)",
        10: "var(--space-10)",
        11: "var(--space-11)",
        12: "var(--space-12)",
      },
      zIndex: {
        sticky: "var(--z-sticky)",
        dropdown: "var(--z-dropdown)",
        popover: "var(--z-popover)",
        drawer: "var(--z-drawer)",
        modal: "var(--z-modal)",
        toast: "var(--z-toast)",
      },
    },
  },
};

export default config;
