import type { PermissionKey, RoleKey } from "../../../support/runtime-support/common";

export const IDENTITY_BOOTSTRAP_TENANT_ID = "tnt_identity" as const;
export const IDENTITY_BOOTSTRAP_USER_ID = "usr_identity_system" as const;
export const IDENTITY_BOOTSTRAP_ACCOUNT_ID = "acc_identity_system" as const;

export const PERMISSION_PRESETS = {
  paymentsOperator: ["orders.manage", "orders.view"],
  payoutsOperator: ["payouts.manage", "payouts.reconcile", "payouts.request", "payouts.setup", "payouts.view"],
  payoutsViewer: ["payouts.view"],
} satisfies Readonly<Record<string, readonly PermissionKey[]>>;

export const ROLE_PERMISSIONS = {
  "platform-admin": [
    "accounts.manage",
    "accounts.view",
    "catalog.manage",
    "catalog.view",
    "commercial-terms.manage",
    "commercial-terms.view",
    "google-shopping.manage",
    "google-shopping.view",
    "insights-dashboards.view",
    "memberships.manage",
    "memberships.view",
    "postage-policies.manage",
    "postage-policies.view",
    "platform-feedback.manage",
    "platform-feedback.view",
    "platform-policy.manage",
    "platform-policy.view",
    "public-presence.manage",
    "public-presence.view",
    "security.manage",
    "support.manage",
    "support.view",
    // Platform Wallet Adjustment authority (ADR 0020): platform-admin only.
    // Never granted via invitation/membership assignment -- platform-admin
    // itself can only be assigned by platform bootstrap (see
    // assertRoleAssignmentAllowed) -- and never bundled into payouts.*.
    "wallet-adjustments.approve",
    "wallet-adjustments.create",
    "wallet-adjustments.reverse",
    "wallet-adjustments.view",
  ],
  owner: [
    "accounts.manage",
    "accounts.view",
    "catalog.manage",
    "catalog.view",
    "commercial-terms.manage",
    "commercial-terms.view",
    "fulfillment.manage",
    "fulfillment.view",
    "google-shopping.manage",
    "google-shopping.view",
    "insights-dashboards.view",
    "memberships.manage",
    "memberships.view",
    "inventory.manage",
    "inventory.view",
    "listings.manage",
    "listings.view",
    "offers.manage",
    "offers.view",
    "orders.manage",
    "orders.view",
    "postage-policies.manage",
    "postage-policies.view",
    ...PERMISSION_PRESETS.payoutsOperator,
    "platform-feedback.manage",
    "platform-feedback.view",
    "platform-policy.view",
    "public-presence.manage",
    "public-presence.view",
    "reputation.manage",
    "reputation.view",
    "support.manage",
    "support.view",
    "security.manage",
  ],
  manager: [
    "accounts.view",
    "catalog.manage",
    "catalog.view",
    "commercial-terms.manage",
    "commercial-terms.view",
    "fulfillment.manage",
    "fulfillment.view",
    "google-shopping.manage",
    "google-shopping.view",
    "insights-dashboards.view",
    "memberships.manage",
    "memberships.view",
    "inventory.manage",
    "inventory.view",
    "listings.manage",
    "listings.view",
    "offers.manage",
    "offers.view",
    "orders.manage",
    "orders.view",
    "postage-policies.manage",
    "postage-policies.view",
    ...PERMISSION_PRESETS.payoutsOperator,
    "platform-feedback.manage",
    "platform-feedback.view",
    "platform-policy.view",
    "public-presence.manage",
    "public-presence.view",
    "reputation.manage",
    "reputation.view",
    "support.manage",
    "support.view",
  ],
  fulfillment: [
    "accounts.view",
    "fulfillment.manage",
    "fulfillment.view",
    "memberships.view",
    "inventory.view",
    "listings.view",
    "offers.view",
    "orders.view",
    "platform-feedback.view",
    "public-presence.view",
    "reputation.view",
    "support.manage",
    "support.view",
  ],
  viewer: [
    "accounts.view",
    "fulfillment.view",
    "memberships.view",
    "inventory.view",
    "listings.view",
    "offers.view",
    "orders.view",
    ...PERMISSION_PRESETS.payoutsViewer,
    "platform-feedback.view",
    "public-presence.view",
    "reputation.view",
    "support.view",
  ],
} satisfies Record<RoleKey, readonly PermissionKey[]>;
