// Generated by scripts/generate-deployable-shells.mjs. Do not edit by hand.

import type { NavigationItem } from "@chase-sets/design-system";

type ShellActor = Readonly<{
  permissions?: readonly string[];
}> | null | undefined;

type ShellContribution = Readonly<{
  key: string;
  label: string;
  icon: NavigationItem["icon"];
  href: string;
  order: number;
  visibility: "always" | "signed-in" | "signed-out";
  requiredPermissions: readonly string[];
}>;

function hasRequiredPermissions(
  actor: ShellActor,
  requiredPermissions: readonly string[],
) {
  if (requiredPermissions.length === 0) {
    return true;
  }

  const grantedPermissions = actor?.permissions ?? [];
  return requiredPermissions.every((permission) => grantedPermissions.includes(permission));
}

function isVisibleForActor(
  actor: ShellActor,
  contribution: ShellContribution,
) {
  if (contribution.visibility === "signed-in" && !actor) {
    return false;
  }

  if (contribution.visibility === "signed-out" && actor) {
    return false;
  }

  return hasRequiredPermissions(actor, contribution.requiredPermissions);
}

function resolveShellItems(
  contributions: readonly ShellContribution[],
  actor?: ShellActor,
): NavigationItem[] {
  return [...contributions]
    .filter((contribution) => isVisibleForActor(actor, contribution))
    .sort((left, right) =>
      left.order === right.order
        ? left.label.localeCompare(right.label)
        : left.order - right.order,
    )
    .map(({ key, label, icon, href }) => ({
      key,
      label,
      icon,
      href,
    }));
}

const PrimaryNavContributions = [
  {
    key: "accounts",
    label: "Accounts",
    icon: "package",
    href: "/accounts",
    order: 10,
    visibility: "signed-in",
    requiredPermissions: [],
  },
  {
    key: "users",
    label: "Users",
    icon: "user",
    href: "/users",
    order: 20,
    visibility: "signed-in",
    requiredPermissions: [],
  },
  {
    key: "memberships",
    label: "Memberships",
    icon: "settings",
    href: "/memberships",
    order: 30,
    visibility: "signed-in",
    requiredPermissions: [],
  },
  {
    key: "invitations",
    label: "Invitations",
    icon: "info",
    href: "/invitations",
    order: 40,
    visibility: "signed-in",
    requiredPermissions: [],
  },
  {
    key: "sessions",
    label: "Sessions",
    icon: "clock",
    href: "/sessions",
    order: 50,
    visibility: "signed-in",
    requiredPermissions: [],
  },
  {
    key: "api-keys",
    label: "API Keys",
    icon: "settings",
    href: "/api-keys",
    order: 60,
    visibility: "signed-in",
    requiredPermissions: [],
  },
] satisfies readonly ShellContribution[];

export function createIdentityAdminPrimaryNavItems(actor?: ShellActor): NavigationItem[] {
  return resolveShellItems(PrimaryNavContributions, actor);
}
