// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

import { route, type RouteConfig } from "@react-router/dev/routes";

export const contextRoutes = [
  route("accounts", "routes/accounts.tsx"),
  route("accounts/:id", "routes/accounts-detail.tsx"),
  route("api-keys", "routes/api-keys.tsx"),
  route("api-keys/:id", "routes/api-keys-detail.tsx"),
  route("invitations", "routes/invitations.tsx"),
  route("invitations/:id", "routes/invitations-detail.tsx"),
  route("memberships", "routes/memberships.tsx"),
  route("memberships/:id", "routes/memberships-detail.tsx"),
  route("sessions", "routes/sessions.tsx"),
  route("sessions/:id", "routes/sessions-detail.tsx"),
  route("users", "routes/users.tsx"),
  route("users/:id", "routes/users-detail.tsx"),
] satisfies RouteConfig;
