import {
  type McpJsonSchemaProperty,
  type McpServiceDescriptor,
  accountScopedListOutputSchema,
  arrayProperty,
  booleanProperty,
  idempotencyKeyProperty,
  integerProperty,
  mutationInput,
  objectSchema,
  readTool,
  resource,
  service,
  stringProperty,
  writeTool,
} from "@chase-sets/platform-runtime/mcp-contracts/builders";

const postageAddressProperty = (description: string): McpJsonSchemaProperty => ({
  type: "object",
  description,
  additionalProperties: false,
  properties: {
    name: stringProperty("Recipient or sender name."),
    company: stringProperty("Optional company name."),
    street1: stringProperty("Street line 1."),
    street2: stringProperty("Optional street line 2."),
    line1: stringProperty("Deprecated alias for street1."),
    line2: stringProperty("Deprecated alias for street2."),
    city: stringProperty("City."),
    state: stringProperty("State or province."),
    postalCode: stringProperty("Postal code."),
    country: stringProperty("Country code."),
    phone: stringProperty("Optional phone number."),
    email: stringProperty("Optional email address."),
  },
  required: ["name", "city", "state", "postalCode", "country"],
});

const postagePackageProperty = (): McpJsonSchemaProperty => ({
  type: "object",
  description: "Optional package override for postage purchase.",
  additionalProperties: false,
  properties: {
    lengthInches: { type: "number", description: "Package length in inches." },
    widthInches: { type: "number", description: "Package width in inches." },
    heightInches: { type: "number", description: "Package height in inches." },
    weightOunces: { type: "number", description: "Package weight in ounces." },
  },
  required: ["lengthInches", "widthInches", "heightInches", "weightOunces"],
});

const fulfillmentTrackingOutputSchema = objectSchema(
  {
    accountId: stringProperty("Authenticated account scope."),
    shipmentId: stringProperty("Shipment identifier."),
    status: stringProperty("Current shipment status."),
    carrierName: stringProperty("Carrier name when present."),
    trackingIdentifier: stringProperty("Tracking identifier when present."),
    labelStatus: stringProperty("Label status when present."),
    dispatchedAt: stringProperty("Dispatch timestamp when present."),
    deliveredAt: stringProperty("Delivery timestamp when present."),
    returnedAt: stringProperty("Return timestamp when present."),
    exceptionRaisedAt: stringProperty("Exception timestamp when present."),
    currentExceptionType: stringProperty("Current exception type when present."),
    currentExceptionNotes: stringProperty("Current exception notes when present."),
    providerEvents: arrayProperty("Provider tracking events.", {
      type: "object",
      description: "Postage provider event.",
      additionalProperties: true,
      properties: {},
    }),
    resourceUri: stringProperty("MCP resource URI for the shipment."),
  },
  ["accountId", "shipmentId", "status", "providerEvents", "resourceUri"],
);

const fulfillmentShipmentActionOutputSchema = objectSchema(
  {
    accountId: stringProperty("Authenticated seller account."),
    id: stringProperty("Shipment identifier."),
    shipmentId: stringProperty("Shipment identifier."),
    version: integerProperty("Committed shipment stream version."),
    status: stringProperty("Resulting shipment status."),
    action: stringProperty("Concrete state-machine action applied."),
    resourceUri: stringProperty("MCP resource URI for the shipment."),
    trackingIdentifier: stringProperty("Tracking identifier when label purchase was the next action."),
  },
  ["accountId", "id", "shipmentId", "version", "status", "action", "resourceUri"],
);

export const fulfillmentService = {
  ...service(
    "fulfillment",
    "Fulfillment",
    "bounded-contexts/fulfillment",
    "Shipments, package details, label purchase, tracking, and delivery outcomes.",
    "fulfillment.view",
    ["shipment"],
    {
      packageName: "@chase-sets/fulfillment",
    },
  ),
  tools: [
    {
      ...readTool(
        "fulfillment",
        "list-shipments",
        "List Shipments",
        "List shipments for purchases or sales.",
        "fulfillment.view",
        objectSchema(
          {
            accountId: stringProperty("Authenticated account scope."),
            side: stringProperty("Shipment side.", ["purchase", "sale"]),
          },
          ["accountId"],
        ),
        "shipment",
        ["Use before label, tracking, or delivery support actions."],
      ),
      availability: "available",
      outputSchema: accountScopedListOutputSchema("Fulfillment shipment rows visible to the actor."),
    },
    {
      ...readTool(
        "fulfillment",
        "get-tracking",
        "Get Tracking",
        "Read tracking and delivery status for a purchase or sale shipment.",
        "fulfillment.view",
        objectSchema(
          {
            accountId: stringProperty("Authenticated account scope."),
            shipmentId: stringProperty("Shipment identifier."),
          },
          ["accountId", "shipmentId"],
        ),
        "shipment-tracking",
        ["Use to answer buyer post-purchase tracking and delivery questions."],
      ),
      availability: "available",
      outputSchema: fulfillmentTrackingOutputSchema,
    },
    {
      ...writeTool(
        "fulfillment",
        "purchase-label",
        "Purchase Label",
        "Purchase a postage label through the fulfillment workflow.",
        "fulfillment.manage",
        objectSchema(
          {
            accountId: stringProperty("Authenticated account scope."),
            shipmentId: stringProperty("Shipment needing a label."),
            serviceLevel: stringProperty("USPS service level."),
            sender: postageAddressProperty("Optional sender address override."),
            recipient: postageAddressProperty("Optional recipient address override."),
            overrideReason: stringProperty("Reason for changing sender or recipient address snapshots."),
            package: postagePackageProperty(),
            reason: stringProperty("Business reason for the action."),
            idempotencyKey: idempotencyKeyProperty(),
            confirmationText: stringProperty("Exact user or policy confirmation text."),
            dryRun: booleanProperty("Validate the action without committing it."),
          },
          ["accountId", "shipmentId", "reason", "idempotencyKey", "confirmationText"],
        ),
        "shipment",
        ["Use after confirming package, sender, recipient, and service level."],
        "sensitive",
      ),
      availability: "available",
    },
    {
      ...writeTool(
        "fulfillment",
        "advance-shipment",
        "Advance Shipment",
        "Apply the shipment state machine's next seller action: start packing, prepare the package, purchase a label, or dispatch.",
        "fulfillment.manage",
        objectSchema(
          {
            accountId: stringProperty("Authenticated seller account scope."),
            shipmentId: stringProperty("Shipment to advance."),
            packageCount: integerProperty("Package count used when packing is complete."),
            serviceLevel: stringProperty("USPS service level used when label purchase is next."),
            sender: postageAddressProperty("Optional sender address override."),
            recipient: postageAddressProperty("Optional recipient address override."),
            overrideReason: stringProperty("Reason for changing address snapshots."),
            package: postagePackageProperty(),
            reason: stringProperty("Business reason for the action."),
            idempotencyKey: idempotencyKeyProperty(),
            confirmationText: stringProperty("Exact user or policy confirmation text."),
            dryRun: booleanProperty("Validate the action without committing it."),
          },
          ["accountId", "shipmentId", "reason", "idempotencyKey", "confirmationText"],
        ),
        "shipment",
        ["Use after reading the Seller Desk attention queue when the seller wants the canonical next step."],
        "sensitive",
      ),
      availability: "available",
      outputSchema: fulfillmentShipmentActionOutputSchema,
    },
    {
      ...writeTool(
        "fulfillment",
        "dispatch-shipment",
        "Dispatch Shipment",
        "Dispatch a labeled shipment through the same state-checked command used by the seller web surface.",
        "fulfillment.manage",
        mutationInput("shipmentId", "Shipment ready for dispatch."),
        "shipment",
        ["Use only after the shipment state confirms its label is attached."],
        "sensitive",
      ),
      availability: "available",
      outputSchema: fulfillmentShipmentActionOutputSchema,
    },
    {
      ...writeTool(
        "fulfillment",
        "raise-shipment-exception",
        "Raise Shipment Exception",
        "Raise a seller shipment exception through the shared fulfillment command surface.",
        "fulfillment.manage",
        objectSchema(
          {
            accountId: stringProperty("Authenticated seller account scope."),
            shipmentId: stringProperty("Shipment needing an exception."),
            exceptionType: stringProperty("Fulfillment exception type."),
            notes: stringProperty("Optional seller notes."),
            reason: stringProperty("Business reason for the action."),
            idempotencyKey: idempotencyKeyProperty(),
            confirmationText: stringProperty("Exact user or policy confirmation text."),
            dryRun: booleanProperty("Validate the action without committing it."),
          },
          ["accountId", "shipmentId", "exceptionType", "reason", "idempotencyKey", "confirmationText"],
        ),
        "shipment",
        ["Use when the seller cannot complete the normal next action and needs to surface a blocker."],
        "sensitive",
      ),
      availability: "available",
      outputSchema: fulfillmentShipmentActionOutputSchema,
    },
    {
      ...writeTool(
        "fulfillment",
        "void-label",
        "Void Label",
        "Void an unused postage label.",
        "fulfillment.manage",
        mutationInput("shipmentId", "Shipment with label to void."),
        "shipment",
        ["Use only after confirming the label is unused and eligible to void."],
        "destructive",
      ),
      availability: "available",
    },
  ],
  resources: [
    {
      ...resource(
        "fulfillment",
        "chase-sets://fulfillment/{accountId}/shipments/{shipmentId}",
        "Shipment",
        "Shipment state, package, label, and tracking read model.",
        "fulfillment.view",
        ["Use before fulfillment mutations."],
      ),
      availability: "available",
    },
  ],
} as const satisfies McpServiceDescriptor;
