import ogDefaultUrl from "./assets/chase-sets-og-default.png?url";
import ogDisneyLorcanaUrl from "./assets/chase-sets-og-disney-lorcana.png?url";
import ogFoundersUrl from "./assets/chase-sets-og-founders.png?url";
import ogMagicTheGatheringUrl from "./assets/chase-sets-og-magic-the-gathering.png?url";
import ogOnePieceCardGameUrl from "./assets/chase-sets-og-one-piece-card-game.png?url";
import ogPokemonUrl from "./assets/chase-sets-og-pokemon.png?url";
import ogYuGiOhUrl from "./assets/chase-sets-og-yu-gi-oh.png?url";
import { publicPresenceT as t } from "./public-presence-translator";

/**
 * Committed 1200x630 Open Graph cards generated by
 * `assets/generate-og-images.mjs` (see that script for the regeneration
 * command). The per-game cards back the `?game=` landing variants the
 * campaign roster links to; `default` backs every other public page that
 * has no more specific card.
 */
export const publicOpenGraphImages: Readonly<{ default: string; founders: string }> = {
  default: ogDefaultUrl,
  founders: ogFoundersUrl,
};

// Keyed by the canonical WaitlistGame slugs (features/waitlist/domain/common.ts);
// routes pass a normalized `?game=` slug, so an unknown value simply falls
// back to the default card.
const gameOpenGraphImages: Readonly<Record<string, string>> = {
  pokemon: ogPokemonUrl,
  "magic-the-gathering": ogMagicTheGatheringUrl,
  "yu-gi-oh": ogYuGiOhUrl,
  "disney-lorcana": ogDisneyLorcanaUrl,
  "one-piece-card-game": ogOnePieceCardGameUrl,
};

export function resolveGameOpenGraphImage(game: string | null | undefined): string | null {
  return (game && gameOpenGraphImages[game]) || null;
}

export function normalizePublicOrigin(origin: string) {
  return origin.replace(/\/+$/, "");
}

export function buildAbsolutePublicUrl(origin: string, path: string) {
  return new URL(path, `${normalizePublicOrigin(origin)}/`).toString();
}

/**
 * The complete social preview tag set (Open Graph + Twitter card) every
 * indexable public page publishes so shared links render a large-image card
 * on X and Discord. Callers own the plain `title`/`description` descriptors;
 * this builder only owns the social duplicates so route-specific meta stays
 * the single source for on-page copy.
 */
export function buildPublicSocialMeta({
  publicOrigin,
  path,
  title,
  description,
  imagePath,
}: Readonly<{
  publicOrigin: string;
  path: string;
  title: string;
  description: string;
  imagePath: string;
}>) {
  const pageUrl = buildAbsolutePublicUrl(publicOrigin, path);
  const imageUrl = buildAbsolutePublicUrl(publicOrigin, imagePath);

  return [
    { property: "og:site_name", content: t("publicPresence.brand") },
    { property: "og:title", content: title },
    { property: "og:description", content: description },
    { property: "og:type", content: "website" },
    { property: "og:url", content: pageUrl },
    { property: "og:image", content: imageUrl },
    { name: "twitter:card", content: "summary_large_image" },
    { name: "twitter:title", content: title },
    { name: "twitter:description", content: description },
    { name: "twitter:image", content: imageUrl },
  ];
}
