// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

export * from "@chase-sets/identity/routes/marketplace/account-team";
export { default } from "@chase-sets/identity/routes/marketplace/account-team";
