// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

import * as RouteModule from "@chase-sets/payments/routes/marketplace/account-payment";

export const loader = RouteModule.loader;
export const meta = RouteModule.meta;
export default RouteModule.default;
