// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

import * as RouteModule from "@chase-sets/ordering/routes/account-sales";

export const loader = RouteModule.loader;
export const meta = RouteModule.meta;
export default RouteModule.default;
