// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

import * as RouteModule from "@chase-sets/inventory/routes/marketplace/account-inventory";

export const loader = RouteModule.loader;
export const action = RouteModule.action;
export const meta = RouteModule.meta;
export default RouteModule.default;
