// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

export * from "@chase-sets/inventory/routes/marketplace/account-inventory-record";
export { default } from "@chase-sets/inventory/routes/marketplace/account-inventory-record";
