// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

export * from "@chase-sets/fulfillment/routes/marketplace/account-shipments";
export { default } from "@chase-sets/fulfillment/routes/marketplace/account-shipments";
