// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

export * from "@chase-sets/discovery/routes/item-detail";
export { default } from "@chase-sets/discovery/routes/item-detail";
