// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

import * as RouteModule from "@chase-sets/auth/routes/marketplace/sign-in";

export const action = RouteModule.action;
export const meta = RouteModule.meta;
export default RouteModule.default;
