// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

import * as RouteModule from "@chase-sets/auth/routes/marketplace/sign-out";

export const action = RouteModule.action;
export default RouteModule.default;
