import type { BcSchemaMigration } from "@chase-sets/bounded-context-module";

export const discoveryUnloggedProjectionSchemaMigrations: readonly BcSchemaMigration[] = [
  {
    migrationId: "20260710_discovery_unlogged_projections",
    description: "Store replayable Discovery projections as unlogged tables.",
    statements: [
      "SET lock_timeout = '5s';",
      "ALTER TABLE discovery_categories SET UNLOGGED;",
      "ALTER TABLE discovery_category_catalog_categories SET UNLOGGED;",
      "ALTER TABLE discovery_category_catalog_items SET UNLOGGED;",
      "ALTER TABLE discovery_google_shopping_feed_rows SET UNLOGGED;",
      "ALTER TABLE discovery_item_detail_catalog_blueprints SET UNLOGGED;",
      "ALTER TABLE discovery_item_detail_catalog_categories SET UNLOGGED;",
      "ALTER TABLE discovery_item_detail_catalog_dimension_options SET UNLOGGED;",
      "ALTER TABLE discovery_item_detail_catalog_dimensions SET UNLOGGED;",
      "ALTER TABLE discovery_item_detail_catalog_fields SET UNLOGGED;",
      "ALTER TABLE discovery_item_detail_catalog_items SET UNLOGGED;",
      "ALTER TABLE discovery_item_detail_catalog_reference_records SET UNLOGGED;",
      "ALTER TABLE discovery_item_detail_pages SET UNLOGGED;",
      "ALTER TABLE discovery_item_detail_product_contents SET UNLOGGED;",
      "ALTER TABLE discovery_item_detail_sell_list_lines SET UNLOGGED;",
      "ALTER TABLE discovery_market_account_reviews SET UNLOGGED;",
      "ALTER TABLE discovery_market_accounts SET UNLOGGED;",
      "ALTER TABLE discovery_market_listings SET UNLOGGED;",
      "ALTER TABLE discovery_market_product_measures SET UNLOGGED;",
      "ALTER TABLE discovery_market_supply_holds SET UNLOGGED;",
      "ALTER TABLE discovery_market_supply_items SET UNLOGGED;",
      "ALTER TABLE discovery_market_supply_locations SET UNLOGGED;",
      "ALTER TABLE discovery_offer_demand_matches SET UNLOGGED;",
      "ALTER TABLE discovery_product_alert_market_activity SET UNLOGGED;",
      "ALTER TABLE discovery_product_alert_pages SET UNLOGGED;",
      "ALTER TABLE discovery_search_catalog_blueprint_dimensions SET UNLOGGED;",
      "ALTER TABLE discovery_search_catalog_blueprints SET UNLOGGED;",
      "ALTER TABLE discovery_search_catalog_categories SET UNLOGGED;",
      "ALTER TABLE discovery_search_catalog_dimension_options SET UNLOGGED;",
      "ALTER TABLE discovery_search_catalog_dimensions SET UNLOGGED;",
      "ALTER TABLE discovery_search_catalog_fields SET UNLOGGED;",
      "ALTER TABLE discovery_search_catalog_items SET UNLOGGED;",
      "ALTER TABLE discovery_search_catalog_reference_records SET UNLOGGED;",
      "ALTER TABLE discovery_search_items SET UNLOGGED;",
      "ALTER TABLE discovery_search_product_contents SET UNLOGGED;",
    ],
  },
];
