// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/catalog/account-select": {
    params: {};
  };
  "/catalog/sign-in": {
    params: {};
  };
  "/catalog/sign-out": {
    params: {};
  };
  "/identity/account-select": {
    params: {};
  };
  "/identity/sign-in": {
    params: {};
  };
  "/identity/sign-out": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/catalog/blueprints": {
    params: {};
  };
  "/catalog/blueprints/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog/catalog-items": {
    params: {};
  };
  "/catalog/catalog-items/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog/categories": {
    params: {};
  };
  "/catalog/categories/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog/components": {
    params: {};
  };
  "/catalog/components/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog/dimensions": {
    params: {};
  };
  "/catalog/dimensions/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog/fields": {
    params: {};
  };
  "/catalog/fields/:id": {
    params: {
      "id": string;
    };
  };
  "/identity": {
    params: {};
  };
  "/identity/sessions": {
    params: {};
  };
  "/identity/sessions/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/accounts": {
    params: {};
  };
  "/identity/accounts/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/api-keys": {
    params: {};
  };
  "/identity/api-keys/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/invitations": {
    params: {};
  };
  "/identity/invitations/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/memberships": {
    params: {};
  };
  "/identity/memberships/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/users": {
    params: {};
  };
  "/identity/users/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/catalog/account-select" | "/catalog/sign-in" | "/catalog/sign-out" | "/identity/account-select" | "/identity/sign-in" | "/identity/sign-out" | "/catalog" | "/catalog/blueprints" | "/catalog/blueprints/:id" | "/catalog/catalog-items" | "/catalog/catalog-items/:id" | "/catalog/categories" | "/catalog/categories/:id" | "/catalog/components" | "/catalog/components/:id" | "/catalog/dimensions" | "/catalog/dimensions/:id" | "/catalog/fields" | "/catalog/fields/:id" | "/identity" | "/identity/sessions" | "/identity/sessions/:id" | "/identity/accounts" | "/identity/accounts/:id" | "/identity/api-keys" | "/identity/api-keys/:id" | "/identity/invitations" | "/identity/invitations/:id" | "/identity/memberships" | "/identity/memberships/:id" | "/identity/users" | "/identity/users/:id";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "../../../bounded-contexts/auth/routes/catalog-admin/account-select.tsx": {
    id: "../../../bounded-contexts/auth/routes/catalog-admin/account-select";
    page: "/catalog/account-select";
  };
  "../../../bounded-contexts/auth/routes/catalog-admin/sign-in.tsx": {
    id: "../../../bounded-contexts/auth/routes/catalog-admin/sign-in";
    page: "/catalog/sign-in";
  };
  "../../../bounded-contexts/auth/routes/catalog-admin/sign-out.tsx": {
    id: "../../../bounded-contexts/auth/routes/catalog-admin/sign-out";
    page: "/catalog/sign-out";
  };
  "../../../bounded-contexts/auth/routes/identity-admin/account-select.tsx": {
    id: "../../../bounded-contexts/auth/routes/identity-admin/account-select";
    page: "/identity/account-select";
  };
  "../../../bounded-contexts/auth/routes/identity-admin/sign-in.tsx": {
    id: "../../../bounded-contexts/auth/routes/identity-admin/sign-in";
    page: "/identity/sign-in";
  };
  "../../../bounded-contexts/auth/routes/identity-admin/sign-out.tsx": {
    id: "../../../bounded-contexts/auth/routes/identity-admin/sign-out";
    page: "/identity/sign-out";
  };
  "routes/catalog-layout.tsx": {
    id: "routes/catalog-layout";
    page: "/catalog" | "/catalog/blueprints" | "/catalog/blueprints/:id" | "/catalog/catalog-items" | "/catalog/catalog-items/:id" | "/catalog/categories" | "/catalog/categories/:id" | "/catalog/components" | "/catalog/components/:id" | "/catalog/dimensions" | "/catalog/dimensions/:id" | "/catalog/fields" | "/catalog/fields/:id";
  };
  "routes/catalog-home.tsx": {
    id: "routes/catalog-home";
    page: "/catalog";
  };
  "../../../bounded-contexts/catalog/routes/admin/blueprints.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/blueprints";
    page: "/catalog/blueprints";
  };
  "../../../bounded-contexts/catalog/routes/admin/blueprints-detail.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/blueprints-detail";
    page: "/catalog/blueprints/:id";
  };
  "../../../bounded-contexts/catalog/routes/admin/catalog-items.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/catalog-items";
    page: "/catalog/catalog-items";
  };
  "../../../bounded-contexts/catalog/routes/admin/catalog-items-detail.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/catalog-items-detail";
    page: "/catalog/catalog-items/:id";
  };
  "../../../bounded-contexts/catalog/routes/admin/categories.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/categories";
    page: "/catalog/categories";
  };
  "../../../bounded-contexts/catalog/routes/admin/categories-detail.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/categories-detail";
    page: "/catalog/categories/:id";
  };
  "../../../bounded-contexts/catalog/routes/admin/components.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/components";
    page: "/catalog/components";
  };
  "../../../bounded-contexts/catalog/routes/admin/components-detail.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/components-detail";
    page: "/catalog/components/:id";
  };
  "../../../bounded-contexts/catalog/routes/admin/dimensions.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/dimensions";
    page: "/catalog/dimensions";
  };
  "../../../bounded-contexts/catalog/routes/admin/dimensions-detail.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/dimensions-detail";
    page: "/catalog/dimensions/:id";
  };
  "../../../bounded-contexts/catalog/routes/admin/fields.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/fields";
    page: "/catalog/fields";
  };
  "../../../bounded-contexts/catalog/routes/admin/fields-detail.tsx": {
    id: "../../../bounded-contexts/catalog/routes/admin/fields-detail";
    page: "/catalog/fields/:id";
  };
  "routes/identity-layout.tsx": {
    id: "routes/identity-layout";
    page: "/identity" | "/identity/sessions" | "/identity/sessions/:id" | "/identity/accounts" | "/identity/accounts/:id" | "/identity/api-keys" | "/identity/api-keys/:id" | "/identity/invitations" | "/identity/invitations/:id" | "/identity/memberships" | "/identity/memberships/:id" | "/identity/users" | "/identity/users/:id";
  };
  "routes/identity-home.tsx": {
    id: "routes/identity-home";
    page: "/identity";
  };
  "../../../bounded-contexts/auth/routes/identity-admin/sessions.tsx": {
    id: "../../../bounded-contexts/auth/routes/identity-admin/sessions";
    page: "/identity/sessions";
  };
  "../../../bounded-contexts/auth/routes/identity-admin/sessions-detail.tsx": {
    id: "../../../bounded-contexts/auth/routes/identity-admin/sessions-detail";
    page: "/identity/sessions/:id";
  };
  "../../../bounded-contexts/identity/routes/admin/accounts.tsx": {
    id: "../../../bounded-contexts/identity/routes/admin/accounts";
    page: "/identity/accounts";
  };
  "../../../bounded-contexts/identity/routes/admin/accounts-detail.tsx": {
    id: "../../../bounded-contexts/identity/routes/admin/accounts-detail";
    page: "/identity/accounts/:id";
  };
  "../../../bounded-contexts/identity/routes/admin/api-keys.tsx": {
    id: "../../../bounded-contexts/identity/routes/admin/api-keys";
    page: "/identity/api-keys";
  };
  "../../../bounded-contexts/identity/routes/admin/api-keys-detail.tsx": {
    id: "../../../bounded-contexts/identity/routes/admin/api-keys-detail";
    page: "/identity/api-keys/:id";
  };
  "../../../bounded-contexts/identity/routes/admin/invitations.tsx": {
    id: "../../../bounded-contexts/identity/routes/admin/invitations";
    page: "/identity/invitations";
  };
  "../../../bounded-contexts/identity/routes/admin/invitations-detail.tsx": {
    id: "../../../bounded-contexts/identity/routes/admin/invitations-detail";
    page: "/identity/invitations/:id";
  };
  "../../../bounded-contexts/identity/routes/admin/memberships.tsx": {
    id: "../../../bounded-contexts/identity/routes/admin/memberships";
    page: "/identity/memberships";
  };
  "../../../bounded-contexts/identity/routes/admin/memberships-detail.tsx": {
    id: "../../../bounded-contexts/identity/routes/admin/memberships-detail";
    page: "/identity/memberships/:id";
  };
  "../../../bounded-contexts/identity/routes/admin/users.tsx": {
    id: "../../../bounded-contexts/identity/routes/admin/users";
    page: "/identity/users";
  };
  "../../../bounded-contexts/identity/routes/admin/users-detail.tsx": {
    id: "../../../bounded-contexts/identity/routes/admin/users-detail";
    page: "/identity/users/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "../../../bounded-contexts/auth/routes/catalog-admin/account-select": unknown;
  "../../../bounded-contexts/auth/routes/catalog-admin/sign-in": unknown;
  "../../../bounded-contexts/auth/routes/catalog-admin/sign-out": unknown;
  "../../../bounded-contexts/auth/routes/identity-admin/account-select": unknown;
  "../../../bounded-contexts/auth/routes/identity-admin/sign-in": unknown;
  "../../../bounded-contexts/auth/routes/identity-admin/sign-out": unknown;
  "routes/catalog-layout": typeof import("./app/routes/catalog-layout.tsx");
  "routes/catalog-home": typeof import("./app/routes/catalog-home.tsx");
  "../../../bounded-contexts/catalog/routes/admin/blueprints": unknown;
  "../../../bounded-contexts/catalog/routes/admin/blueprints-detail": unknown;
  "../../../bounded-contexts/catalog/routes/admin/catalog-items": unknown;
  "../../../bounded-contexts/catalog/routes/admin/catalog-items-detail": unknown;
  "../../../bounded-contexts/catalog/routes/admin/categories": unknown;
  "../../../bounded-contexts/catalog/routes/admin/categories-detail": unknown;
  "../../../bounded-contexts/catalog/routes/admin/components": unknown;
  "../../../bounded-contexts/catalog/routes/admin/components-detail": unknown;
  "../../../bounded-contexts/catalog/routes/admin/dimensions": unknown;
  "../../../bounded-contexts/catalog/routes/admin/dimensions-detail": unknown;
  "../../../bounded-contexts/catalog/routes/admin/fields": unknown;
  "../../../bounded-contexts/catalog/routes/admin/fields-detail": unknown;
  "routes/identity-layout": typeof import("./app/routes/identity-layout.tsx");
  "routes/identity-home": typeof import("./app/routes/identity-home.tsx");
  "../../../bounded-contexts/auth/routes/identity-admin/sessions": unknown;
  "../../../bounded-contexts/auth/routes/identity-admin/sessions-detail": unknown;
  "../../../bounded-contexts/identity/routes/admin/accounts": unknown;
  "../../../bounded-contexts/identity/routes/admin/accounts-detail": unknown;
  "../../../bounded-contexts/identity/routes/admin/api-keys": unknown;
  "../../../bounded-contexts/identity/routes/admin/api-keys-detail": unknown;
  "../../../bounded-contexts/identity/routes/admin/invitations": unknown;
  "../../../bounded-contexts/identity/routes/admin/invitations-detail": unknown;
  "../../../bounded-contexts/identity/routes/admin/memberships": unknown;
  "../../../bounded-contexts/identity/routes/admin/memberships-detail": unknown;
  "../../../bounded-contexts/identity/routes/admin/users": unknown;
  "../../../bounded-contexts/identity/routes/admin/users-detail": unknown;
};