// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/favicon.svg": {
    params: {};
  };
  "/favicon.ico": {
    params: {};
  };
  "/catalog/account-select": {
    params: {};
  };
  "/catalog/sign-in": {
    params: {};
  };
  "/catalog/sign-out": {
    params: {};
  };
  "/identity/account-select": {
    params: {};
  };
  "/identity/sign-in": {
    params: {};
  };
  "/identity/sign-out": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/catalog/blueprints": {
    params: {};
  };
  "/catalog/blueprints/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog/catalog-items": {
    params: {};
  };
  "/catalog/catalog-items/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog/categories": {
    params: {};
  };
  "/catalog/categories/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog/components": {
    params: {};
  };
  "/catalog/components/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog/dimensions": {
    params: {};
  };
  "/catalog/dimensions/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog/fields": {
    params: {};
  };
  "/catalog/fields/:id": {
    params: {
      "id": string;
    };
  };
  "/identity": {
    params: {};
  };
  "/identity/sessions": {
    params: {};
  };
  "/identity/sessions/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/commercial-terms/schedules": {
    params: {};
  };
  "/identity/commercial-terms/schedules/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/commercial-terms/agreements": {
    params: {};
  };
  "/identity/commercial-terms/agreements/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/accounts": {
    params: {};
  };
  "/identity/accounts/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/api-keys": {
    params: {};
  };
  "/identity/api-keys/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/invitations": {
    params: {};
  };
  "/identity/invitations/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/memberships": {
    params: {};
  };
  "/identity/memberships/:id": {
    params: {
      "id": string;
    };
  };
  "/identity/users": {
    params: {};
  };
  "/identity/users/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/favicon.svg" | "/favicon.ico" | "/catalog/account-select" | "/catalog/sign-in" | "/catalog/sign-out" | "/identity/account-select" | "/identity/sign-in" | "/identity/sign-out" | "/catalog" | "/catalog/blueprints" | "/catalog/blueprints/:id" | "/catalog/catalog-items" | "/catalog/catalog-items/:id" | "/catalog/categories" | "/catalog/categories/:id" | "/catalog/components" | "/catalog/components/:id" | "/catalog/dimensions" | "/catalog/dimensions/:id" | "/catalog/fields" | "/catalog/fields/:id" | "/identity" | "/identity/sessions" | "/identity/sessions/:id" | "/identity/commercial-terms/schedules" | "/identity/commercial-terms/schedules/:id" | "/identity/commercial-terms/agreements" | "/identity/commercial-terms/agreements/:id" | "/identity/accounts" | "/identity/accounts/:id" | "/identity/api-keys" | "/identity/api-keys/:id" | "/identity/invitations" | "/identity/invitations/:id" | "/identity/memberships" | "/identity/memberships/:id" | "/identity/users" | "/identity/users/:id";
  };
  "routes/favicon-svg.ts": {
    id: "routes/favicon-svg";
    page: "/favicon.svg";
  };
  "routes/favicon.ts": {
    id: "routes/favicon";
    page: "/favicon.ico";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "../../../bounded-contexts/auth/routes/catalog-admin/account-select.tsx": {
    id: "auth/catalog/account-select";
    page: "/catalog/account-select";
  };
  "../../../bounded-contexts/auth/routes/catalog-admin/sign-in.tsx": {
    id: "auth/catalog/sign-in";
    page: "/catalog/sign-in";
  };
  "../../../bounded-contexts/auth/routes/catalog-admin/sign-out.tsx": {
    id: "auth/catalog/sign-out";
    page: "/catalog/sign-out";
  };
  "../../../bounded-contexts/auth/routes/identity-admin/account-select.tsx": {
    id: "auth/identity/account-select";
    page: "/identity/account-select";
  };
  "../../../bounded-contexts/auth/routes/identity-admin/sign-in.tsx": {
    id: "auth/identity/sign-in";
    page: "/identity/sign-in";
  };
  "../../../bounded-contexts/auth/routes/identity-admin/sign-out.tsx": {
    id: "auth/identity/sign-out";
    page: "/identity/sign-out";
  };
  "routes/catalog-layout.tsx": {
    id: "routes/catalog-layout";
    page: "/catalog" | "/catalog/blueprints" | "/catalog/blueprints/:id" | "/catalog/catalog-items" | "/catalog/catalog-items/:id" | "/catalog/categories" | "/catalog/categories/:id" | "/catalog/components" | "/catalog/components/:id" | "/catalog/dimensions" | "/catalog/dimensions/:id" | "/catalog/fields" | "/catalog/fields/:id";
  };
  "routes/catalog-home.tsx": {
    id: "routes/catalog-home";
    page: "/catalog";
  };
  "../../../bounded-contexts/catalog/routes/admin/blueprints.tsx": {
    id: "catalog/catalog/blueprints";
    page: "/catalog/blueprints";
  };
  "../../../bounded-contexts/catalog/routes/admin/blueprints-detail.tsx": {
    id: "catalog/catalog/blueprints-detail";
    page: "/catalog/blueprints/:id";
  };
  "../../../bounded-contexts/catalog/routes/admin/catalog-items.tsx": {
    id: "catalog/catalog/catalog-items";
    page: "/catalog/catalog-items";
  };
  "../../../bounded-contexts/catalog/routes/admin/catalog-items-detail.tsx": {
    id: "catalog/catalog/catalog-items-detail";
    page: "/catalog/catalog-items/:id";
  };
  "../../../bounded-contexts/catalog/routes/admin/categories.tsx": {
    id: "catalog/catalog/categories";
    page: "/catalog/categories";
  };
  "../../../bounded-contexts/catalog/routes/admin/categories-detail.tsx": {
    id: "catalog/catalog/categories-detail";
    page: "/catalog/categories/:id";
  };
  "../../../bounded-contexts/catalog/routes/admin/components.tsx": {
    id: "catalog/catalog/components";
    page: "/catalog/components";
  };
  "../../../bounded-contexts/catalog/routes/admin/components-detail.tsx": {
    id: "catalog/catalog/components-detail";
    page: "/catalog/components/:id";
  };
  "../../../bounded-contexts/catalog/routes/admin/dimensions.tsx": {
    id: "catalog/catalog/dimensions";
    page: "/catalog/dimensions";
  };
  "../../../bounded-contexts/catalog/routes/admin/dimensions-detail.tsx": {
    id: "catalog/catalog/dimensions-detail";
    page: "/catalog/dimensions/:id";
  };
  "../../../bounded-contexts/catalog/routes/admin/fields.tsx": {
    id: "catalog/catalog/fields";
    page: "/catalog/fields";
  };
  "../../../bounded-contexts/catalog/routes/admin/fields-detail.tsx": {
    id: "catalog/catalog/fields-detail";
    page: "/catalog/fields/:id";
  };
  "routes/identity-layout.tsx": {
    id: "routes/identity-layout";
    page: "/identity" | "/identity/sessions" | "/identity/sessions/:id" | "/identity/commercial-terms/schedules" | "/identity/commercial-terms/schedules/:id" | "/identity/commercial-terms/agreements" | "/identity/commercial-terms/agreements/:id" | "/identity/accounts" | "/identity/accounts/:id" | "/identity/api-keys" | "/identity/api-keys/:id" | "/identity/invitations" | "/identity/invitations/:id" | "/identity/memberships" | "/identity/memberships/:id" | "/identity/users" | "/identity/users/:id";
  };
  "routes/identity-home.tsx": {
    id: "routes/identity-home";
    page: "/identity";
  };
  "../../../bounded-contexts/auth/routes/identity-admin/sessions.tsx": {
    id: "auth/identity/sessions";
    page: "/identity/sessions";
  };
  "../../../bounded-contexts/auth/routes/identity-admin/sessions-detail.tsx": {
    id: "auth/identity/sessions-detail";
    page: "/identity/sessions/:id";
  };
  "../../../bounded-contexts/commercial-terms/routes/admin/schedules.tsx": {
    id: "commercial-terms/identity/commercial-terms-schedules";
    page: "/identity/commercial-terms/schedules";
  };
  "../../../bounded-contexts/commercial-terms/routes/admin/schedules-detail.tsx": {
    id: "commercial-terms/identity/commercial-terms-schedules-detail";
    page: "/identity/commercial-terms/schedules/:id";
  };
  "../../../bounded-contexts/commercial-terms/routes/admin/agreements.tsx": {
    id: "commercial-terms/identity/commercial-terms-agreements";
    page: "/identity/commercial-terms/agreements";
  };
  "../../../bounded-contexts/commercial-terms/routes/admin/agreements-detail.tsx": {
    id: "commercial-terms/identity/commercial-terms-agreements-detail";
    page: "/identity/commercial-terms/agreements/:id";
  };
  "../../../bounded-contexts/identity/routes/admin/accounts.tsx": {
    id: "identity/identity/accounts";
    page: "/identity/accounts";
  };
  "../../../bounded-contexts/identity/routes/admin/accounts-detail.tsx": {
    id: "identity/identity/accounts-detail";
    page: "/identity/accounts/:id";
  };
  "../../../bounded-contexts/identity/routes/admin/api-keys.tsx": {
    id: "identity/identity/api-keys";
    page: "/identity/api-keys";
  };
  "../../../bounded-contexts/identity/routes/admin/api-keys-detail.tsx": {
    id: "identity/identity/api-keys-detail";
    page: "/identity/api-keys/:id";
  };
  "../../../bounded-contexts/identity/routes/admin/invitations.tsx": {
    id: "identity/identity/invitations";
    page: "/identity/invitations";
  };
  "../../../bounded-contexts/identity/routes/admin/invitations-detail.tsx": {
    id: "identity/identity/invitations-detail";
    page: "/identity/invitations/:id";
  };
  "../../../bounded-contexts/identity/routes/admin/memberships.tsx": {
    id: "identity/identity/memberships";
    page: "/identity/memberships";
  };
  "../../../bounded-contexts/identity/routes/admin/memberships-detail.tsx": {
    id: "identity/identity/memberships-detail";
    page: "/identity/memberships/:id";
  };
  "../../../bounded-contexts/identity/routes/admin/users.tsx": {
    id: "identity/identity/users";
    page: "/identity/users";
  };
  "../../../bounded-contexts/identity/routes/admin/users-detail.tsx": {
    id: "identity/identity/users-detail";
    page: "/identity/users/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/favicon-svg": typeof import("./app/routes/favicon-svg.ts");
  "routes/favicon": typeof import("./app/routes/favicon.ts");
  "routes/index": typeof import("./app/routes/index.tsx");
  "auth/catalog/account-select": unknown;
  "auth/catalog/sign-in": unknown;
  "auth/catalog/sign-out": unknown;
  "auth/identity/account-select": unknown;
  "auth/identity/sign-in": unknown;
  "auth/identity/sign-out": unknown;
  "routes/catalog-layout": typeof import("./app/routes/catalog-layout.tsx");
  "routes/catalog-home": typeof import("./app/routes/catalog-home.tsx");
  "catalog/catalog/blueprints": unknown;
  "catalog/catalog/blueprints-detail": unknown;
  "catalog/catalog/catalog-items": unknown;
  "catalog/catalog/catalog-items-detail": unknown;
  "catalog/catalog/categories": unknown;
  "catalog/catalog/categories-detail": unknown;
  "catalog/catalog/components": unknown;
  "catalog/catalog/components-detail": unknown;
  "catalog/catalog/dimensions": unknown;
  "catalog/catalog/dimensions-detail": unknown;
  "catalog/catalog/fields": unknown;
  "catalog/catalog/fields-detail": unknown;
  "routes/identity-layout": typeof import("./app/routes/identity-layout.tsx");
  "routes/identity-home": typeof import("./app/routes/identity-home.tsx");
  "auth/identity/sessions": unknown;
  "auth/identity/sessions-detail": unknown;
  "commercial-terms/identity/commercial-terms-schedules": unknown;
  "commercial-terms/identity/commercial-terms-schedules-detail": unknown;
  "commercial-terms/identity/commercial-terms-agreements": unknown;
  "commercial-terms/identity/commercial-terms-agreements-detail": unknown;
  "identity/identity/accounts": unknown;
  "identity/identity/accounts-detail": unknown;
  "identity/identity/api-keys": unknown;
  "identity/identity/api-keys-detail": unknown;
  "identity/identity/invitations": unknown;
  "identity/identity/invitations-detail": unknown;
  "identity/identity/memberships": unknown;
  "identity/identity/memberships-detail": unknown;
  "identity/identity/users": unknown;
  "identity/identity/users-detail": unknown;
};