import type { RegisteredScheduledRunnerConfig } from "../src/scheduled-runners";

export const livenessConfig: RegisteredScheduledRunnerConfig = {
  workerId: "synthetic-liveness-worker",
  leaseTtlMs: 30_000,
  channelsConnectorLivenessSweepIntervalMs: 60_000,
  paymentReconciliationIntervalMs: null,
  paymentDeadlineSweepIntervalMs: null,
  supportRequestDeadlineSweepIntervalMs: null,
  customerFeedbackAttentionDigestIntervalMs: null,
  customerFeedbackAttentionTeamRecipientUserIds: [],
  reviewWindowSweepIntervalMs: null,
  reviewOpportunityReminderSweepIntervalMs: null,
  sellerAvailabilityRestoreSweepIntervalMs: null,
  sellerAwayWindowStartSweepIntervalMs: null,
  sellerFundsReleaseIntervalMs: null,
  spendHoldSweepIntervalMs: null,
  payoutReconciliationIntervalMs: null,
  liabilityReconciliationIntervalMs: null,
  marketRollupsCloserIntervalMs: null,
  settlementAccountLinkageCloserIntervalMs: null,
  gmvReconciliationIntervalMs: null,
  catalogProviderScopeRefreshIntervalMs: null,
  googleMerchant: {
    syncEnabled: false,
    dryRun: true,
  },
  googleShoppingMaintenanceIntervalMs: null,
  googleShoppingMaintenanceBatchSize: 1,
  googleShoppingRefreshWindowDays: 1,
  googleShoppingDiagnosticsIntervalMs: null,
  googleShoppingDiagnosticsBatchSize: 1,
  discoverySearchEmbeddings: {
    apiKey: null,
    model: "synthetic",
    batchSize: 1,
    timeoutMs: 1000,
    maxAttempts: 1,
    retryBackoffBaseMs: 1,
    retryBackoffMaxMs: 1,
    intervalMs: 60_000,
    rolloutValue: "false",
    rescueValue: "false",
    hybridValue: "false",
    queryCacheMaxEntries: 1,
    queryCacheTtlMs: 1000,
    queryTimeoutMs: 800,
  },
};
