// Generated by scripts/sync-workspace-metadata.mjs. Do not edit by hand.

import { adminWebEnglishTranslations } from "./en/admin-web";
import { authEnglishTranslations } from "./en/auth";
import { authenticityEnglishTranslations } from "./en/authenticity";
import { catalogEnglishTranslations } from "./en/catalog";
import { checkoutEnglishTranslations } from "./en/checkout";
import { collectionsEnglishTranslations } from "./en/collections";
import { commercialTermsEnglishTranslations } from "./en/commercial-terms";
import { customerFeedbackEnglishTranslations } from "./en/customer-feedback";
import { discoveryEnglishTranslations } from "./en/discovery";
import { experienceEnglishTranslations } from "./en/experience";
import { fulfillmentEnglishTranslations } from "./en/fulfillment";
import { identityEnglishTranslations } from "./en/identity";
import { inventoryEnglishTranslations } from "./en/inventory";
import { localizationEnglishTranslations } from "./en/localization";
import { marketplaceEnglishTranslations } from "./en/marketplace";
import { notificationsEnglishTranslations } from "./en/notifications";
import { orderingEnglishTranslations } from "./en/ordering";
import { paymentsEnglishTranslations } from "./en/payments";
import { platformOperationsEnglishTranslations } from "./en/platform-operations";
import { pricingEnglishTranslations } from "./en/pricing";
import { publicPresenceEnglishTranslations } from "./en/public-presence";
import { reputationEnglishTranslations } from "./en/reputation";
import { settlementEnglishTranslations } from "./en/settlement";
import { supportEnglishTranslations } from "./en/support";

export const englishTranslations = {
  ...adminWebEnglishTranslations,
  ...authEnglishTranslations,
  ...authenticityEnglishTranslations,
  ...catalogEnglishTranslations,
  ...checkoutEnglishTranslations,
  ...collectionsEnglishTranslations,
  ...commercialTermsEnglishTranslations,
  ...customerFeedbackEnglishTranslations,
  ...discoveryEnglishTranslations,
  ...experienceEnglishTranslations,
  ...fulfillmentEnglishTranslations,
  ...identityEnglishTranslations,
  ...inventoryEnglishTranslations,
  ...localizationEnglishTranslations,
  ...marketplaceEnglishTranslations,
  ...notificationsEnglishTranslations,
  ...orderingEnglishTranslations,
  ...paymentsEnglishTranslations,
  ...platformOperationsEnglishTranslations,
  ...pricingEnglishTranslations,
  ...publicPresenceEnglishTranslations,
  ...reputationEnglishTranslations,
  ...settlementEnglishTranslations,
  ...supportEnglishTranslations,
} as const;

export type EnglishTranslationKey = keyof typeof englishTranslations;
