{{- range $name, $component := .Values.components }}
{{- if and $component.enabled (eq $component.kind "job") }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chase-sets-platform.componentName" (dict "root" $ "name" $name) }}
  labels:
{{ include "chase-sets-platform.labels" (dict "root" $ "name" $name) | nindent 4 }}
  {{- if $component.job.hook.enabled }}
  annotations:
    "helm.sh/hook": {{ join "," $component.job.hook.events | quote }}
    "helm.sh/hook-weight": {{ $component.job.hook.weight | quote }}
    "helm.sh/hook-delete-policy": {{ join "," $component.job.hook.deletePolicy | quote }}
  {{- end }}
spec:
  suspend: {{ $component.job.suspend }}
  backoffLimit: {{ $component.job.backoffLimit }}
{{ if $component.job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ $component.job.activeDeadlineSeconds }}
{{ end }}
  ttlSecondsAfterFinished: {{ $component.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
{{ include "chase-sets-platform.selectorLabels" (dict "root" $ "name" $name) | nindent 8 }}
    spec:
      restartPolicy: Never
{{ include "chase-sets-platform.podSpec" (dict "root" $ "name" $name "component" $component) | nindent 6 }}
{{- end }}
{{- end }}
