{{- range $name, $component := .Values.components }}
{{- if and $component.enabled (eq $component.kind "service") $component.rollout $component.rollout.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "chase-sets-platform.componentName" (dict "root" $ "name" $name) }}
  labels:
{{ include "chase-sets-platform.labels" (dict "root" $ "name" $name) | nindent 4 }}
spec:
  replicas: {{ $component.replicas }}
  selector:
    matchLabels:
{{ include "chase-sets-platform.selectorLabels" (dict "root" $ "name" $name) | nindent 6 }}
  strategy:
    canary:
      stableService: {{ include "chase-sets-platform.componentName" (dict "root" $ "name" $name) }}
      canaryService: {{ include "chase-sets-platform.canaryServiceName" (dict "root" $ "name" $name) }}
      {{- if and $component.rollout.canary.trafficRouting.nginx.enabled $component.rollout.canary.trafficRouting.nginx.stableIngress }}
      trafficRouting:
        nginx:
          stableIngress: {{ $component.rollout.canary.trafficRouting.nginx.stableIngress | quote }}
      {{- end }}
      {{- with $component.rollout.canary.steps }}
      steps:
{{ toYaml . | nindent 8 }}
      {{- end }}
  template:
    metadata:
      labels:
{{ include "chase-sets-platform.selectorLabels" (dict "root" $ "name" $name) | nindent 8 }}
{{- with $.Values.global.podLabels }}
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with $component.podLabels }}
{{ toYaml . | nindent 8 }}
{{- end }}
{{- if or $.Values.global.podAnnotations $component.podAnnotations }}
      annotations:
{{- with $.Values.global.podAnnotations }}
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with $component.podAnnotations }}
{{ toYaml . | nindent 8 }}
{{- end }}
{{- end }}
    spec:
{{ include "chase-sets-platform.podSpec" (dict "root" $ "name" $name "component" $component) | nindent 6 }}
{{- end }}
{{- end }}
