{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chase-sets-platform.serviceAccountName" . }}
  labels:
{{ include "chase-sets-platform.labels" (dict "root" . "name" "platform") | nindent 4 }}
{{- end }}
