// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/components": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/checkout" | "/components";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/admin" | "/checkout" | "/components";
  };
  "routes/marketplace.tsx": {
    id: "routes/marketplace";
    page: "/";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/components.tsx": {
    id: "routes/components";
    page: "/components";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/marketplace": typeof import("./app/routes/marketplace.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
  "routes/components": typeof import("./app/routes/components.tsx");
};