import { registryEntry } from "../source-context-wake-registry-entry";

export const catalogWakeRegistryEntry = registryEntry({
  sourceContextName: "catalog",
  owner: "Catalog",
  rolloutState: "staging-enabled",
  enablement: {
    eventStoreWakeNotifications: true,
    relayFanOut: true,
  },
  phase: "phase-2-composite-migration",
  rolloutWave: "wave-2-commerce-dependencies",
  priorityLane: "standard",
  expectedEventVolume: "high",
  wakeStoreLoadEstimate: "high",
  affectedProjectionNames: [
    "catalog:catalog-admin-catalog-item-projection",
    "catalog:catalog-attention-dismissal-projection",
    "catalog:catalog-item-projection",
    "catalog:catalog-product-contents-projection",
    "catalog:catalog-provider-scope-mapping-projection",
    "catalog:catalog-scope-registry-projection",
    "catalog:catalog-source-observation-projection",
    "checkout:checkout-catalog-item-projection",
    "checkout:checkout-marketplace-listing-options-projection",
    "collections:collections-catalog-product-projection",
    "discovery:discovery-category-projection",
    "discovery:discovery-google-shopping-feed-row-projection",
    "discovery:discovery-item-detail-projection",
    "discovery:discovery-market-projection",
    "discovery:discovery-search-item-projection",
    "inventory:inventory-catalog-item-projection",
    "marketplace:marketplace-catalog-item-projection",
    "marketplace:marketplace-listing-projection",
    "ordering:ordering-marketplace-supply-input-projection",
    "pricing:pricing-catalog-input-projection",
  ],
  routeDependencyIds: [],
});
