import { registryEntry } from "../source-context-wake-registry-entry";

export const identityWakeRegistryEntry = registryEntry({
  sourceContextName: "identity",
  owner: "Identity",
  // Staging-enabled for cross-device User presentation preferences:
  // preference writes must wake Identity's own read models so reloads and
  // second sessions observe the committed viewer setting without waiting on
  // fallback polling. Production remains inert through the environment kill
  // switches until the production proof gates pass.
  rolloutState: "staging-enabled",
  enablement: {
    eventStoreWakeNotifications: true,
    relayFanOut: true,
  },
  phase: "phase-2-composite-migration",
  rolloutWave: "wave-2-commerce-dependencies",
  priorityLane: "standard",
  expectedEventVolume: "high",
  wakeStoreLoadEstimate: "high",
  affectedProjectionNames: [
    "auth:auth-identity-account-projection",
    "auth:auth-identity-invitation-projection",
    "auth:auth-identity-membership-projection",
    "auth:auth-identity-user-projection",
    "checkout:checkout-seller-accounts-projection",
    "commercial-terms:commercial-terms-account-projection",
    "commercial-terms:commercial-terms-founders-window-reaction",
    "discovery:discovery-market-projection",
    "fulfillment:fulfillment-account-projection",
    "identity:identity-account-projection",
    "identity:identity-api-key-projection",
    "identity:identity-consent-current-state-projection",
    "identity:identity-consent-projection",
    "identity:identity-founders-cohort-projection",
    "identity:identity-invitation-projection",
    "identity:identity-membership-projection",
    "identity:identity-shipping-address-projection",
    "identity:identity-user-preferences-projection",
    "identity:identity-user-projection",
    "identity:platform-policy-document-projection",
    "marketplace:marketplace-identity-account-projection",
    "marketplace:marketplace-review-account-source-projection",
    "ordering:ordering-account-projection",
    "payments:payments-account-risk-source-projection",
    "platform-operations:risk-alert-queue-projection",
    "pricing:pricing-market-trades-projection",
    "public-presence:public-presence-waitlist-transactional-email-projection",
    "settlement:settlement-account-risk-source-projection",
  ],
  routeDependencyIds: [
    "identity.account-security-api-key-fresh-read",
    "identity.account-security-user-fresh-read",
    "identity.account-team-invitation-fresh-read",
    "identity.account-team-membership-fresh-read",
    "identity.consent-withdrawal-fresh-read",
    "identity.admin-account-detail-fresh-read",
    "identity.admin-api-key-create-detail-fresh-read",
    "identity.admin-api-key-detail-fresh-read",
    "identity.admin-api-key-list-fresh-read",
    "identity.admin-invitation-create-detail-fresh-read",
    "identity.admin-invitation-detail-fresh-read",
    "identity.admin-invitation-list-fresh-read",
    "identity.admin-membership-detail-fresh-read",
    "identity.admin-user-detail-fresh-read",
    "identity.invitation-email-auth-projection-fresh-read",
    "identity.marketplace-account-profile-fresh-read",
    "identity.registration-current-actor-display-fresh-read",
    "identity.shipping-addresses-fresh-read",
  ],
});
