// Generated by scripts/generate-deployable-api-mounts.mjs. Do not edit by hand.

import type { ResolvedApiMount } from "@chase-sets/bounded-context-runtime";
import { resolveApiMounts as resolveDiscoveryApiMounts } from "@chase-sets/discovery";
import { resolveApiMounts as resolveFulfillmentApiMounts } from "@chase-sets/fulfillment";
import { resolveApiMounts as resolveMarketplaceApiMounts } from "@chase-sets/marketplace";
import { resolveApiMounts as resolveOrderingApiMounts } from "@chase-sets/ordering";
import { resolveApiMounts as resolvePaymentsApiMounts } from "@chase-sets/payments";
import { resolveApiMounts as resolveReputationApiMounts } from "@chase-sets/reputation";
import { resolveApiMounts as resolveSettlementApiMounts } from "@chase-sets/settlement";

export function createContextApiMounts(
  services: {
  discovery: Parameters<typeof resolveDiscoveryApiMounts>[0];
  fulfillment: Parameters<typeof resolveFulfillmentApiMounts>[0];
  marketplace: Parameters<typeof resolveMarketplaceApiMounts>[0];
  ordering: Parameters<typeof resolveOrderingApiMounts>[0];
  payments: Parameters<typeof resolvePaymentsApiMounts>[0];
  reputation: Parameters<typeof resolveReputationApiMounts>[0];
  settlement: Parameters<typeof resolveSettlementApiMounts>[0];
},
): readonly ResolvedApiMount[] {
  return [
    ...resolveDiscoveryApiMounts(services.discovery),
    ...resolveFulfillmentApiMounts(services.fulfillment),
    ...resolveMarketplaceApiMounts(services.marketplace),
    ...resolveOrderingApiMounts(services.ordering),
    ...resolvePaymentsApiMounts(services.payments),
    ...resolveReputationApiMounts(services.reputation),
    ...resolveSettlementApiMounts(services.settlement),
  ];
}
