// Generated by scripts/generate-deployable-lifecycles.mjs. Do not edit by hand.

import {
  bootstrapContextDatabase,
  drainContextRuntime,
  seedApiModuleIfEmpty,
  syncContextProjectionGroups,
} from "@chase-sets/bounded-context-runtime";
import type {
  ContextRuntimePools,
  createContextRuntime,
} from "./context-runtime.generated";

const lifecycleContextOrder = [
  "catalog",
  "discovery",
  "identity",
  "inventory",
  "marketplace",
  "ordering",
  "payments",
  "fulfillment",
  "pricing",
  "reputation",
  "settlement"
] as const;

export async function seedContextRuntimeIfEmpty(
  _pools: ContextRuntimePools,
  runtime: ReturnType<typeof createContextRuntime>,
): Promise<void> {
  const mountedContextsByName = new Map(
    runtime.mountedContexts.map((entry) => [entry.contextName, entry]),
  );
  const orderedContexts = lifecycleContextOrder.map((contextName) => {
    const context = mountedContextsByName.get(contextName);
    if (!context) {
      throw new Error(
        `Runtime is missing mounted module '${contextName}' required by generated lifecycle order.`,
      );
    }

    return context;
  });

  for (const context of runtime.mountedContexts) {
    await bootstrapContextDatabase(context.module, context.pool);
  }

  for (const context of orderedContexts) {
    await syncContextProjectionGroups(runtime, context.contextName, {
      requiredOnly: true,
    });
    await seedApiModuleIfEmpty(context.module, context.pool);
    await syncContextProjectionGroups(runtime, context.contextName);
    await drainContextRuntime(runtime);
  }

  await drainContextRuntime(runtime);
}
