// Generated by scripts/generate-deployable-runtimes.mjs. Do not edit by hand.

import { collectProjectors, resolveModuleProjectionGroups, resolveModuleSubscriptions } from "@chase-sets/bounded-context-runtime";
import type { PgTransactionalPool } from "@chase-sets/event-core-postgres";
import { module as catalogModule } from "@chase-sets/catalog";
import { module as discoveryModule } from "@chase-sets/discovery";
import { module as fulfillmentModule } from "@chase-sets/fulfillment";
import { module as identityModule } from "@chase-sets/identity";
import { module as inventoryModule } from "@chase-sets/inventory";
import { module as marketplaceModule } from "@chase-sets/marketplace";
import { module as orderingModule } from "@chase-sets/ordering";
import { module as paymentsModule } from "@chase-sets/payments";
import { module as pricingModule } from "@chase-sets/pricing";
import { module as reputationModule } from "@chase-sets/reputation";
import { module as settlementModule } from "@chase-sets/settlement";

export type ContextRuntimePools = Readonly<{
  catalog: PgTransactionalPool;
  discovery: PgTransactionalPool;
  fulfillment: PgTransactionalPool;
  identity: PgTransactionalPool;
  inventory: PgTransactionalPool;
  marketplace: PgTransactionalPool;
  ordering: PgTransactionalPool;
  payments: PgTransactionalPool;
  pricing: PgTransactionalPool;
  reputation: PgTransactionalPool;
  settlement: PgTransactionalPool;
}>;

export type ContextRuntimeServices = Readonly<{
  catalog: ReturnType<typeof catalogModule.createServices>;
  discovery: ReturnType<typeof discoveryModule.createServices>;
  fulfillment: ReturnType<typeof fulfillmentModule.createServices>;
  identity: ReturnType<typeof identityModule.createServices>;
  inventory: ReturnType<typeof inventoryModule.createServices>;
  marketplace: ReturnType<typeof marketplaceModule.createServices>;
  ordering: ReturnType<typeof orderingModule.createServices>;
  payments: ReturnType<typeof paymentsModule.createServices>;
  pricing: ReturnType<typeof pricingModule.createServices>;
  reputation: ReturnType<typeof reputationModule.createServices>;
  settlement: ReturnType<typeof settlementModule.createServices>;
}>;

export type ContextRuntimeHostPorts = Readonly<{
  processorGateway: Parameters<typeof paymentsModule.createServices>[1]["processorGateway"];
}>;

export function createContextRuntime(
  pools: ContextRuntimePools,
  hostPorts: ContextRuntimeHostPorts = {} as ContextRuntimeHostPorts,
) {
  const services = {} as Record<string, unknown> as {
  catalog: ReturnType<typeof catalogModule.createServices>;
  discovery: ReturnType<typeof discoveryModule.createServices>;
  fulfillment: ReturnType<typeof fulfillmentModule.createServices>;
  identity: ReturnType<typeof identityModule.createServices>;
  inventory: ReturnType<typeof inventoryModule.createServices>;
  marketplace: ReturnType<typeof marketplaceModule.createServices>;
  ordering: ReturnType<typeof orderingModule.createServices>;
  payments: ReturnType<typeof paymentsModule.createServices>;
  pricing: ReturnType<typeof pricingModule.createServices>;
  reputation: ReturnType<typeof reputationModule.createServices>;
  settlement: ReturnType<typeof settlementModule.createServices>;
  };

  services.catalog = catalogModule.createServices(pools.catalog, undefined);
  services.discovery = discoveryModule.createServices(pools.discovery, undefined);
  services.fulfillment = fulfillmentModule.createServices(pools.fulfillment, undefined);
  services.identity = identityModule.createServices(pools.identity, undefined);
  services.inventory = inventoryModule.createServices(pools.inventory, undefined);
  services.marketplace = marketplaceModule.createServices(pools.marketplace, undefined);
  services.ordering = orderingModule.createServices(pools.ordering, undefined);
  services.payments = paymentsModule.createServices(pools.payments, {
    processorGateway: hostPorts.processorGateway,
  });
  services.pricing = pricingModule.createServices(pools.pricing, undefined);
  services.reputation = reputationModule.createServices(pools.reputation, undefined);
  services.settlement = settlementModule.createServices(pools.settlement, undefined);

  const mountedContexts = [
    {
      contextName: "catalog",
      mountRole: "active",
      module: catalogModule,
      services: services.catalog,
      pool: pools.catalog,
      projectors: catalogModule.projectors(services.catalog),
    },
    {
      contextName: "discovery",
      mountRole: "active",
      module: discoveryModule,
      services: services.discovery,
      pool: pools.discovery,
      projectors: discoveryModule.projectors(services.discovery),
    },
    {
      contextName: "fulfillment",
      mountRole: "active",
      module: fulfillmentModule,
      services: services.fulfillment,
      pool: pools.fulfillment,
      projectors: fulfillmentModule.projectors(services.fulfillment),
    },
    {
      contextName: "identity",
      mountRole: "active",
      module: identityModule,
      services: services.identity,
      pool: pools.identity,
      projectors: identityModule.projectors(services.identity),
    },
    {
      contextName: "inventory",
      mountRole: "active",
      module: inventoryModule,
      services: services.inventory,
      pool: pools.inventory,
      projectors: inventoryModule.projectors(services.inventory),
    },
    {
      contextName: "marketplace",
      mountRole: "active",
      module: marketplaceModule,
      services: services.marketplace,
      pool: pools.marketplace,
      projectors: marketplaceModule.projectors(services.marketplace),
    },
    {
      contextName: "ordering",
      mountRole: "active",
      module: orderingModule,
      services: services.ordering,
      pool: pools.ordering,
      projectors: orderingModule.projectors(services.ordering),
    },
    {
      contextName: "payments",
      mountRole: "active",
      module: paymentsModule,
      services: services.payments,
      pool: pools.payments,
      projectors: paymentsModule.projectors(services.payments),
    },
    {
      contextName: "pricing",
      mountRole: "active",
      module: pricingModule,
      services: services.pricing,
      pool: pools.pricing,
      projectors: pricingModule.projectors(services.pricing),
    },
    {
      contextName: "reputation",
      mountRole: "active",
      module: reputationModule,
      services: services.reputation,
      pool: pools.reputation,
      projectors: reputationModule.projectors(services.reputation),
    },
    {
      contextName: "settlement",
      mountRole: "active",
      module: settlementModule,
      services: services.settlement,
      pool: pools.settlement,
      projectors: settlementModule.projectors(services.settlement),
    },
  ] as const;

  const mountedModules = [
    { module: catalogModule, services: services.catalog },
    { module: discoveryModule, services: services.discovery },
    { module: fulfillmentModule, services: services.fulfillment },
    { module: identityModule, services: services.identity },
    { module: inventoryModule, services: services.inventory },
    { module: marketplaceModule, services: services.marketplace },
    { module: orderingModule, services: services.ordering },
    { module: paymentsModule, services: services.payments },
    { module: pricingModule, services: services.pricing },
    { module: reputationModule, services: services.reputation },
    { module: settlementModule, services: services.settlement },
  ] as const;

  const subscriptionRunners = resolveModuleSubscriptions(mountedContexts);
  const projectionGroups = resolveModuleProjectionGroups(
    mountedContexts,
    subscriptionRunners,
  );

  return {
    mountedContexts,
    mountedModules,
    services: services as ContextRuntimeServices,
    projectors: collectProjectors([
    services.catalog,
    services.discovery,
    services.fulfillment,
    services.identity,
    services.inventory,
    services.marketplace,
    services.ordering,
    services.payments,
    services.pricing,
    services.reputation,
    services.settlement,
    ]),
    projectionGroups,
    subscriptionRunners,
  };
}
