// Generated by scripts/generate-deployable-runtimes.mjs. Do not edit by hand.

import { collectProjectors } from "@chase-sets/bounded-context-runtime";
import type { PgTransactionalPool } from "@chase-sets/event-core-postgres";
import { module as catalogModule } from "@chase-sets/catalog";
import { module as discoveryModule } from "@chase-sets/discovery";
import { module as fulfillmentModule } from "@chase-sets/fulfillment";
import { module as identityModule } from "@chase-sets/identity";
import { module as inventoryModule } from "@chase-sets/inventory";
import { module as marketplaceModule } from "@chase-sets/marketplace";
import { module as orderingModule } from "@chase-sets/ordering";
import { module as paymentsModule } from "@chase-sets/payments";
import { module as pricingModule } from "@chase-sets/pricing";
import { module as reputationModule } from "@chase-sets/reputation";
import { module as settlementModule } from "@chase-sets/settlement";
import { createCatalogSellableUnitDescriptorPort } from "@chase-sets/catalog/integration/sellable-units";
import { createInventoryReservationGateway } from "@chase-sets/inventory/integration/reservation-gateway";
import { createMarketplaceSupplyResolver } from "@chase-sets/marketplace/integration/supply-resolver";
import { createOrderSnapshotReader } from "@chase-sets/ordering/integration/order-snapshot-reader";

export type ContextRuntimeServices = Readonly<{
  catalog: ReturnType<typeof catalogModule.createServices>;
  discovery: ReturnType<typeof discoveryModule.createServices>;
  fulfillment: ReturnType<typeof fulfillmentModule.createServices>;
  identity: ReturnType<typeof identityModule.createServices>;
  inventory: ReturnType<typeof inventoryModule.createServices>;
  marketplace: ReturnType<typeof marketplaceModule.createServices>;
  ordering: ReturnType<typeof orderingModule.createServices>;
  payments: ReturnType<typeof paymentsModule.createServices>;
  pricing: ReturnType<typeof pricingModule.createServices>;
  reputation: ReturnType<typeof reputationModule.createServices>;
  settlement: ReturnType<typeof settlementModule.createServices>;
}>;

export type ContextRuntimeHostPorts = Readonly<{
  processorGateway: Parameters<typeof paymentsModule.createServices>[1]["processorGateway"];
}>;

export function createContextRuntime(
  pool: PgTransactionalPool,
  hostPorts: ContextRuntimeHostPorts = {} as ContextRuntimeHostPorts,
) {
  const services = {} as Record<string, unknown> as {
  catalog: ReturnType<typeof catalogModule.createServices>;
  discovery: ReturnType<typeof discoveryModule.createServices>;
  fulfillment: ReturnType<typeof fulfillmentModule.createServices>;
  identity: ReturnType<typeof identityModule.createServices>;
  inventory: ReturnType<typeof inventoryModule.createServices>;
  marketplace: ReturnType<typeof marketplaceModule.createServices>;
  ordering: ReturnType<typeof orderingModule.createServices>;
  payments: ReturnType<typeof paymentsModule.createServices>;
  pricing: ReturnType<typeof pricingModule.createServices>;
  reputation: ReturnType<typeof reputationModule.createServices>;
  settlement: ReturnType<typeof settlementModule.createServices>;
  };

  services.catalog = catalogModule.createServices(pool, undefined);
  services.discovery = discoveryModule.createServices(pool, undefined);
  services.fulfillment = fulfillmentModule.createServices(pool, undefined);
  services.identity = identityModule.createServices(pool, undefined);
  services.inventory = inventoryModule.createServices(pool, undefined);
  services.marketplace = marketplaceModule.createServices(pool, undefined);
  services.ordering = orderingModule.createServices(pool, {
    supplyResolver: createMarketplaceSupplyResolver(services.marketplace),
    inventoryReservations: createInventoryReservationGateway(services.inventory),
  });
  services.payments = paymentsModule.createServices(pool, {
    processorGateway: hostPorts.processorGateway,
    getOrderSnapshot: createOrderSnapshotReader(services.ordering),
  });
  services.pricing = pricingModule.createServices(pool, {
    resolveCatalogSellableUnit: createCatalogSellableUnitDescriptorPort(services.catalog),
    resolveMarketSupply: createMarketplaceSupplyResolver(services.marketplace),
    reserveInventorySignal: createInventoryReservationGateway(services.inventory),
    loadOrderSnapshot: createOrderSnapshotReader(services.ordering),
  });
  services.reputation = reputationModule.createServices(pool, undefined);
  services.settlement = settlementModule.createServices(pool, undefined);

  const mountedModules = [
    { module: catalogModule, services: services.catalog },
    { module: discoveryModule, services: services.discovery },
    { module: fulfillmentModule, services: services.fulfillment },
    { module: identityModule, services: services.identity },
    { module: inventoryModule, services: services.inventory },
    { module: marketplaceModule, services: services.marketplace },
    { module: orderingModule, services: services.ordering },
    { module: paymentsModule, services: services.payments },
    { module: pricingModule, services: services.pricing },
    { module: reputationModule, services: services.reputation },
    { module: settlementModule, services: services.settlement },
  ] as const;

  return {
    mountedModules,
    services: services as ContextRuntimeServices,
    projectors: collectProjectors([
    services.catalog,
    services.discovery,
    services.fulfillment,
    services.identity,
    services.inventory,
    services.marketplace,
    services.ordering,
    services.payments,
    services.pricing,
    services.reputation,
    services.settlement,
    ]),
  };
}
