// Generated by scripts/generate-deployable-lifecycles.mjs. Do not edit by hand.

import { drainProjectors, seedApiModulesIfEmpty } from "@chase-sets/bounded-context-runtime";
import type { PgTransactionalPool } from "@chase-sets/event-core-postgres";
import type { createContextRuntime } from "./context-runtime.generated";

const lifecycleContextOrder = [
  "catalog",
  "discovery",
  "identity",
  "inventory",
  "marketplace",
  "ordering",
  "payments",
  "fulfillment",
  "reputation",
  "settlement"
] as const;

export async function seedContextRuntimeIfEmpty(
  pool: PgTransactionalPool,
  runtime: ReturnType<typeof createContextRuntime>,
): Promise<void> {
  const mountedModulesByName = new Map(
    runtime.mountedModules.map(({ module }) => [module.contextName, module]),
  );
  const orderedModules = lifecycleContextOrder.map((contextName) => {
    const module = mountedModulesByName.get(contextName);
    if (!module) {
      throw new Error(
        `Runtime is missing mounted module '${contextName}' required by generated lifecycle order.`,
      );
    }

    return module;
  });

  await seedApiModulesIfEmpty(orderedModules, pool);
  await drainProjectors(runtime.projectors);
}
