// Generated by scripts/generate-deployable-api-mounts.mjs. Do not edit by hand.

import { resolveModuleApiMounts, type ResolvedApiMount } from "@chase-sets/bounded-context-runtime";
import { module as DiscoveryModule } from "@chase-sets/discovery";
import { module as FulfillmentModule } from "@chase-sets/fulfillment";
import { module as MarketplaceModule } from "@chase-sets/marketplace";
import { module as OrderingModule } from "@chase-sets/ordering";
import { module as PaymentsModule } from "@chase-sets/payments";
import { module as PricingModule } from "@chase-sets/pricing";
import { module as ReputationModule } from "@chase-sets/reputation";
import { module as SettlementModule } from "@chase-sets/settlement";

export function createContextApiMounts(
  services: {
  discovery: ReturnType<typeof DiscoveryModule.createServices>;
  fulfillment: ReturnType<typeof FulfillmentModule.createServices>;
  marketplace: ReturnType<typeof MarketplaceModule.createServices>;
  ordering: ReturnType<typeof OrderingModule.createServices>;
  payments: ReturnType<typeof PaymentsModule.createServices>;
  pricing: ReturnType<typeof PricingModule.createServices>;
  reputation: ReturnType<typeof ReputationModule.createServices>;
  settlement: ReturnType<typeof SettlementModule.createServices>;
},
): readonly ResolvedApiMount[] {
  return [
    ...resolveModuleApiMounts(DiscoveryModule, services.discovery),
    ...resolveModuleApiMounts(FulfillmentModule, services.fulfillment),
    ...resolveModuleApiMounts(MarketplaceModule, services.marketplace),
    ...resolveModuleApiMounts(OrderingModule, services.ordering),
    ...resolveModuleApiMounts(PaymentsModule, services.payments),
    ...resolveModuleApiMounts(PricingModule, services.pricing),
    ...resolveModuleApiMounts(ReputationModule, services.reputation),
    ...resolveModuleApiMounts(SettlementModule, services.settlement),
  ];
}
