import { catalogSeedIds } from "@chase-sets/catalog-seed";
import type { CatalogProviderIntegrationProfile } from "../profile-types";

export const tcgdexPokemonTcgProviderProfile = {
  providerKey: "tcgdex",
  displayName: "TCGdex",
  status: "active",
  capabilities: [
    "provider-option-query",
    "source-observation-import",
    "catalog-item-promotion",
    "external-reference-extraction",
    "alias-candidate-extraction",
  ],
  supportedScopes: ["language", "series", "expansion", "product/card"],
  languageOptions: [
    "en",
    "fr",
    "es",
    "it",
    "pt",
    "pt-br",
    "pt-pt",
    "de",
    "nl",
    "pl",
    "ru",
    "ja",
    "ko",
    "zh-tw",
    "id",
    "th",
    "zh-cn",
  ],
  optionQueries: [
    {
      queryKind: "languages",
      queryKeySynonyms: ["language"],
      displayName: "Language",
      scope: "language",
      parentScope: null,
      operation: "tcgdex-list-languages",
      output: {
        valuePath: "languageCode",
        labelPath: "languageCode",
        metadataPaths: { languageCode: "languageCode" },
      },
    },
    {
      queryKind: "series",
      displayName: "Series",
      scope: "series",
      parentScope: "language",
      operation: "tcgdex-list-series",
      parentValue: {
        required: false,
        valueKind: "language-code",
        diagnosticText: "TCGdex series option queries use the selected language.",
      },
      output: {
        valuePath: "seriesId",
        labelPath: "name",
        parentValuePath: "$languageCode",
        imageUrlPath: "logoUrl",
        aliasesPath: "aliases",
        metadataPaths: {
          languageCode: "$languageCode",
          seriesId: "seriesId",
          logoUrl: "logoUrl",
        },
      },
    },
    {
      queryKind: "expansions",
      queryKeySynonyms: ["expansion"],
      displayName: "Expansion",
      scope: "expansion",
      parentScope: "series",
      operation: "tcgdex-list-expansions",
      parentValue: {
        required: false,
        valueKind: "series-id",
        diagnosticText: "TCGdex expansion option queries may use a Series parent value.",
      },
      output: {
        valuePath: "expansionId",
        labelPath: "name",
        description: { kind: "tcgdex-expansion-card-count" },
        parentValuePath: "seriesId",
        imageUrlCoalescePaths: ["symbolUrl", "logoUrl"],
        aliasesPath: "aliases",
        metadataPaths: {
          languageCode: "$languageCode",
          expansionId: "expansionId",
          seriesId: "seriesId",
          seriesName: "seriesName",
          logoUrl: "logoUrl",
          symbolUrl: "symbolUrl",
          cardCount: "cardCount",
          officialCardCount: "officialCardCount",
        },
      },
    },
  ],
  connector: {
    kind: "tcgdex-json",
    baseUrl: "https://api.tcgdex.net/v2",
    highQualityAssetVariant: "high.webp",
    endpoints: {
      seriesList: "/{language}/series",
      seriesDetail: "/{language}/series/{seriesId}",
      expansionList: "/{language}/sets",
      expansionDetail: "/{language}/sets/{expansionId}",
      productDetail: "/{language}/cards/{cardId}",
    },
  },
  normalizedObservationMapping: {
    kind: "pokemon-card",
    variantRules: [
      {
        variantKey: "standard",
        sourceKeys: ["normal", "standard"],
        displayName: "Standard Set",
        sortOrder: 0,
        parallelSet: false,
        pricingKeys: ["normal", "standard"],
      },
      {
        variantKey: "holofoil",
        sourceKeys: ["holo", "holofoil"],
        displayName: "Standard Set Foil",
        sortOrder: 10,
        parallelSet: false,
        pricingKeys: ["holo", "holofoil"],
      },
      {
        variantKey: "1st-edition",
        sourceKeys: ["firstedition", "1stedition", "1st-edition", "first-edition"],
        displayName: "1st Edition",
        sortOrder: 20,
        parallelSet: false,
        pricingKeys: ["1st-edition", "firstEdition"],
      },
      {
        variantKey: "reverse-holo",
        sourceKeys: ["reverse", "reverseholo", "reverseholofoil", "reverse-holo", "reverse-holofoil"],
        displayName: "Parallel Set - Reverse Foil",
        sortOrder: 30,
        parallelSet: true,
        pricingKeys: ["reverse-holofoil", "reverse-holo", "reverse"],
      },
      {
        variantKey: "poke-ball",
        sourceKeys: ["pokeball", "poke-ball"],
        displayName: "Premium Parallel Set - Poke Ball",
        sortOrder: 40,
        parallelSet: true,
        pricingKeys: ["poke-ball", "pokeball"],
      },
      {
        variantKey: "master-ball",
        sourceKeys: ["masterball", "master-ball"],
        displayName: "Premium Parallel Set - Master Ball",
        sortOrder: 50,
        parallelSet: true,
        pricingKeys: ["master-ball", "masterball"],
      },
    ],
    unknownVariantLabelPrefix: "Unclassified Variant",
    duplicateReferenceRule: "drop-repeated-across-variants",
  },
  catalogFieldMapping: {
    blueprintKey: "pokemon-card-single",
    categoryKey: "singles",
    fieldKeys: {
      cardNumber: "card-number",
      cardName: "card-name",
      expansion: "expansion",
      rarity: "rarity",
      cardVariant: "card-variant",
      cardIllustrator: "card-illustrator",
      releaseYear: "release-year",
    },
  },
  referenceHierarchyMapping: {
    providerReferenceIdPrefix: "ref_tcgdex",
    providerAttributes: [
      { typeKey: "series", providerAttributeKey: "tcgdex-series-id" },
      { typeKey: "expansion", providerAttributeKey: "tcgdex-set-id" },
    ],
    targetRecordRuleKey: "expansion",
    referenceTypes: [
      {
        referenceTypeId: catalogSeedIds.referenceTypes.manufacturer,
        typeKey: "manufacturer",
        name: "Manufacturer",
        descriptionText: "A company responsible for publishing or manufacturing catalog products.",
        attributeKeys: ["homepage-url"],
      },
      {
        referenceTypeId: catalogSeedIds.referenceTypes.productLine,
        typeKey: "product-line",
        name: "Product Line",
        descriptionText: "A branded collectible product line.",
        attributeKeys: ["official-name", "short-name"],
      },
      {
        referenceTypeId: catalogSeedIds.referenceTypes.series,
        typeKey: "series",
        name: "Series",
        descriptionText: "An official Pokemon TCG series that groups expansions.",
        attributeKeys: ["tcgdex-series-id"],
      },
      {
        referenceTypeId: catalogSeedIds.referenceTypes.expansion,
        typeKey: "expansion",
        name: "Expansion",
        descriptionText: "An official Pokemon TCG card expansion.",
        attributeKeys: [
          "abbreviation",
          "card-count",
          "parallel-set-card-count",
          "printed-card-count",
          "release-date",
          "tcgdex-set-id",
        ],
      },
    ],
    referenceRecords: [
      {
        ruleKey: "manufacturer",
        typeKey: "manufacturer",
        recordId: {
          kind: "static",
          referenceRecordId: catalogSeedIds.referenceRecords.manufacturers.thePokemonCompanyInternational,
        },
        key: { kind: "static", value: "the-pokemon-company-international" },
        name: { kind: "static", value: "The Pokemon Company International" },
        description: { kind: "static", value: "Publisher of the English Pokemon Trading Card Game." },
        attributes: [{ attributeKey: "homepage-url", value: { kind: "static", value: "https://www.pokemon.com/us" } }],
      },
      {
        ruleKey: "product-line",
        typeKey: "product-line",
        recordId: {
          kind: "static",
          referenceRecordId: catalogSeedIds.referenceRecords.productLines.pokemonTradingCardGame,
        },
        key: { kind: "static", value: "pokemon-trading-card-game" },
        name: { kind: "static", value: "Pokemon Trading Card Game" },
        description: { kind: "static", value: "The Pokemon Trading Card Game product line." },
        attributes: [
          { attributeKey: "official-name", value: { kind: "static", value: "Pokemon Trading Card Game" } },
          { attributeKey: "short-name", value: { kind: "static", value: "Pokemon TCG" } },
        ],
        relationships: [{ relationshipType: "published-by", ruleKey: "manufacturer" }],
      },
      {
        ruleKey: "series",
        typeKey: "series",
        recordId: { kind: "provider", typeKey: "series", providerValuePaths: ["seriesId", "seriesName"] },
        key: { kind: "path", path: "seriesId" },
        name: { kind: "path", path: "seriesName" },
        description: {
          kind: "template",
          template: "{seriesName} Pokemon TCG series.",
          values: { seriesName: { kind: "path", path: "seriesName" } },
        },
        requiredPaths: ["seriesName"],
        attributes: [{ attributeKey: "tcgdex-series-id", value: { kind: "path", path: "seriesId" }, optional: true }],
        relationships: [{ relationshipType: "part-of", ruleKey: "product-line" }],
      },
      {
        ruleKey: "expansion",
        typeKey: "expansion",
        recordId: { kind: "provider", typeKey: "expansion", providerValuePaths: ["expansionId"] },
        key: { kind: "path", path: "expansionId" },
        name: { kind: "path", path: "expansionName" },
        description: {
          kind: "template",
          template: "{expansionName} Pokemon TCG expansion.",
          values: { expansionName: { kind: "path", path: "expansionName" } },
        },
        requiredPaths: ["expansionId", "expansionName"],
        attributes: [
          { attributeKey: "tcgdex-set-id", value: { kind: "path", path: "expansionId" } },
          { attributeKey: "release-date", value: { kind: "path", path: "releaseDate" }, optional: true },
          { attributeKey: "abbreviation", value: { kind: "path", path: "expansionAbbreviation" }, optional: true },
          { attributeKey: "card-count", value: { kind: "path", path: "expansionCardCount" }, optional: true },
          {
            attributeKey: "parallel-set-card-count",
            value: { kind: "path", path: "expansionParallelSetCardCount" },
            optional: true,
          },
        ],
        relationships: [{ relationshipType: "part-of", ruleKey: "series", fallbackRuleKey: "product-line" }],
      },
    ],
  },
  externalReferenceExtractionRules: {
    referenceTarget: "mixed",
    rules: [
      {
        providerKey: "tcgplayer",
        target: "catalog-item-reference",
        externalKeyPrefix: "product:",
        containerKeys: ["ids", "marketplaceIds", "marketplaces", "markets", "pricing", "prices"],
        valueKeys: [
          "tcgplayer",
          "tcgPlayer",
          "tcgplayerId",
          "tcgPlayerId",
          "tcgplayerProductId",
          "tcgPlayerProductId",
          "tcgplayer_product_id",
        ],
        recordIdKeys: [
          "productId",
          "productID",
          "id",
          "tcgplayerId",
          "tcgPlayerId",
          "tcgplayerProductId",
          "tcgPlayerProductId",
        ],
        pricingRootKeys: ["tcgplayer", "tcgPlayer"],
        pricingScope: "by-variant",
      },
      {
        providerKey: "cardmarket",
        target: "catalog-item-reference",
        externalKeyPrefix: "product:",
        containerKeys: ["ids", "marketplaceIds", "marketplaces", "markets", "pricing", "prices"],
        valueKeys: [
          "cardmarket",
          "cardMarket",
          "cardmarketId",
          "cardMarketId",
          "cardmarketProductId",
          "cardMarketProductId",
          "idProduct",
          "id_product",
        ],
        recordIdKeys: [
          "idProduct",
          "productId",
          "productID",
          "id",
          "cardmarketId",
          "cardMarketId",
          "cardmarketProductId",
        ],
        pricingRootKeys: ["cardmarket", "cardMarket"],
        pricingScope: "card",
      },
    ],
  },
  duplicatePreventionMapping: {
    ambiguousCandidatePolicy: "block-promotion",
    replayPolicy: "same-profile-version",
    rules: [
      {
        ruleKey: "exact-external-catalog-item-reference",
        matchKind: "exact-external-catalog-item-reference",
        sourcePath: "externalCatalogItemReferences",
      },
      {
        ruleKey: "source-observation-link",
        matchKind: "source-observation-link",
        providerKeySource: "observation-provider",
        externalKey: "language-prefixed-observation-external-key",
      },
      {
        ruleKey: "pokemon-card-deterministic-fields",
        matchKind: "deterministic-pokemon-card-field-match",
        normalizedKind: "pokemon-card",
        referenceRecord: {
          typeKey: "expansion",
          keyPath: "expansionName",
          targetFieldKey: "expansion",
        },
        fieldMatches: [
          { fieldKey: "cardNumber", valuePath: "cardNumber" },
          { fieldKey: "cardName", valuePath: "name", valueTransform: "localized-text" },
          { fieldKey: "cardVariant", valuePath: "cardVariantLabel" },
        ],
      },
      {
        ruleKey: "pokemon-card-partial-draft-retry",
        matchKind: "partial-draft-pokemon-card-field-match",
        normalizedKind: "pokemon-card",
        requireDraftStatus: true,
        requireNoExternalProductReference: true,
        requiredTags: [
          { kind: "profile-provider-key" },
          { kind: "template", template: "expansion:{expansionId}", values: { expansionId: "expansionId" } },
          { kind: "template", template: "variant:{cardVariantKey}", values: { cardVariantKey: "cardVariantKey" } },
        ],
        fieldMatches: [
          { fieldKey: "cardNumber", valuePath: "cardNumber" },
          { fieldKey: "cardName", valuePath: "name", valueTransform: "localized-text" },
          { fieldKey: "cardVariant", valuePath: "cardVariantLabel" },
        ],
      },
    ],
  },
  ambiguityRules: {
    repeatedMarketplaceReference: "skip-reference",
    missingVariantSpecificReference: "leave-unmapped",
  },
} as const satisfies CatalogProviderIntegrationProfile;
