import { describe, expect, it } from "vitest";
import { ADVISORY_THRESHOLD, LARGE_THRESHOLD, classifyPrScope } from "./pr-scope-policy-v1.mjs";

function file(overrides = {}) {
  return {
    filename: "bounded-contexts/catalog/features/search/domain/search.ts",
    status: "modified",
    previousFilename: null,
    additions: 10,
    deletions: 5,
    patch: null,
    ...overrides,
  };
}

function filesOfSize(count, additionsPerFile) {
  return Array.from({ length: count }, (_, index) => ({
    filename: `bounded-contexts/catalog/features/search/domain/file-${index}.ts`,
    status: "modified",
    additions: additionsPerFile,
    deletions: 0,
    patch: null,
  }));
}

describe("pr-scope-policy/v1", () => {
  it("normalizes lockfile-only churn out of scope when a manifest source proves it mechanical", () => {
    const scope = classifyPrScope({
      changedFiles: [
        file(),
        file({ filename: "package.json", additions: 1, deletions: 0 }),
        file({ filename: "pnpm-lock.yaml", additions: 4000, deletions: 3000 }),
      ],
    });
    expect(scope.raw.lines).toBe(4000 + 3000 + 15 + 1);
    expect(scope.normalized.lines).toBe(15 + 1);
    expect(scope.excluded.totals["lockfile-mechanical-churn"]).toEqual({ files: 1, additions: 4000, deletions: 3000 });
  });

  it("counts a root lockfile change fully when no manifest source changed alongside it (false-negative guard)", () => {
    const scope = classifyPrScope({
      changedFiles: [file({ filename: "pnpm-lock.yaml", additions: 2501, deletions: 0, patch: null })],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.normalized.lines).toBe(2501);
    expect(scope.status).toBe("large");
  });

  it("normalizes generated registry metadata proven by header provenance and its changed generator source", () => {
    const patch =
      "@@ -1,3 +1,3 @@\n // Generated by scripts/sync-workspace-metadata.mjs. Do not edit by hand.\n-old\n+new";
    const scope = classifyPrScope({
      changedFiles: [
        file(),
        file({ filename: "scripts/sync-workspace-metadata.mjs", additions: 1, deletions: 0 }),
        file({
          filename: "deployables/platform-api/src/generated/context-registry.ts",
          additions: 500,
          deletions: 500,
          patch,
        }),
      ],
    });
    expect(scope.normalized.lines).toBe(15 + 1);
    expect(scope.excluded.totals["generated-registry-metadata"]).toEqual({ files: 1, additions: 500, deletions: 500 });
  });

  it("counts a generated-path file fully when its header/source provenance is unproven (false-negative guard)", () => {
    const scope = classifyPrScope({
      changedFiles: [
        file({
          filename: "deployables/platform-api/src/generated/runtime-policy.ts",
          additions: 2501,
          deletions: 0,
          patch: null,
        }),
      ],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.normalized.lines).toBe(2501);
    expect(scope.status).toBe("large");
  });

  it("excludes generated output with proven provenance while still counting its one-line source change", () => {
    const patch =
      "@@ -1,3 +1,3 @@\n // Generated by scripts/sync-workspace-metadata.mjs. Do not edit by hand.\n-old line\n+new line";
    const scope = classifyPrScope({
      changedFiles: [
        file({ filename: "scripts/sync-workspace-metadata.mjs", additions: 1, deletions: 0, patch: null }),
        file({
          filename: "deployables/platform-api/src/generated/context-registry.ts",
          additions: 2501,
          deletions: 0,
          patch,
        }),
      ],
    });
    expect(scope.raw.lines).toBe(2502);
    expect(scope.normalized.lines).toBe(1);
    expect(scope.status).toBe("normal");
  });

  it("normalizes snapshots proven by the auto-generated Vitest header", () => {
    const patch =
      "@@ -1,3 +1,3 @@\n+// Vitest Snapshot v1, https://vitest.dev/guide/snapshot.html\n+\n+exports[`x`] = `y`;";
    const scope = classifyPrScope({
      changedFiles: [
        file(),
        file({
          filename: "bounded-contexts/catalog/__snapshots__/search.test.ts.snap",
          additions: 200,
          deletions: 0,
          patch,
        }),
      ],
    });
    expect(scope.excluded.totals["generated-snapshot"]).toEqual({ files: 1, additions: 200, deletions: 0 });
  });

  it("counts a handwritten snapshot fully when it lacks the auto-generated header (false-negative guard)", () => {
    const patch = "@@ -1,3 +1,3 @@\n+exports[`x`] = `hand-authored value`;";
    const scope = classifyPrScope({
      changedFiles: [
        file({
          filename: "bounded-contexts/catalog/__snapshots__/runtime.snap",
          additions: 2501,
          deletions: 0,
          patch,
        }),
      ],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.normalized.lines).toBe(2501);
    expect(scope.status).toBe("large");
  });

  it("counts a deleted snapshot fully when the patch does not prove the auto-generated header (false-negative guard)", () => {
    const scope = classifyPrScope({
      changedFiles: [
        file({
          filename: "bounded-contexts/catalog/__snapshots__/legacy.test.ts.snap",
          status: "removed",
          additions: 0,
          deletions: 2501,
          patch: null,
        }),
      ],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.normalized.lines).toBe(2501);
    expect(scope.status).toBe("large");
  });

  it("normalizes vendored/binary files GitHub cannot count lines for", () => {
    const scope = classifyPrScope({
      changedFiles: [
        file(),
        file({ filename: "packages/design-system/src/assets/logo.png", additions: 0, deletions: 0, patch: null }),
      ],
    });
    expect(scope.excluded.totals["vendored-or-binary"]).toEqual({ files: 1, additions: 0, deletions: 0 });
  });

  it("never hides an oversized text diff whose patch GitHub omitted for size (not binary)", () => {
    const scope = classifyPrScope({
      changedFiles: [
        file({
          filename: "bounded-contexts/catalog/features/search/domain/huge.ts",
          additions: 5000,
          deletions: 100,
          patch: null,
        }),
      ],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.normalized.lines).toBe(5100);
  });

  // Option A (decision #5971): the formatting-only exclusion is removed
  // entirely for the advisory rollout rather than replaced with a narrower
  // proof rule. Pure reindentation/whitespace changes and any content
  // permutation now count fully — there is no exclusion branch left to prove
  // or defeat.
  it("counts a pure reindentation/whitespace-only change fully (Option A: no formatting-only exclusion)", () => {
    const patch = "@@ -1,2 +1,2 @@\n-const x = 1;\n+const x = 1;\n- const y = 2;\n+  const y = 2;";
    const scope = classifyPrScope({
      changedFiles: [
        file(),
        file({
          filename: "bounded-contexts/catalog/features/search/domain/format.ts",
          additions: 2,
          deletions: 2,
          patch,
        }),
      ],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.excluded.totals["formatting-only"]).toBeUndefined();
    expect(scope.normalized.lines).toBe(2 + 2 + 15);
  });

  it("counts a 2,600-statement adjacent-pair permutation fully at large status (reproduces and closes the sorted-comparison false negative)", () => {
    // 2,600 statements, adjacent pairs swapped (S0,S1 -> S1,S0; S2,S3 ->
    // S3,S2; ...): the same trimmed-line multiset in a different order — a
    // semantic reorder, not formatting. 2,600 removed + 2,600 added lines =
    // 5,200 raw changed lines.
    const removed = Array.from({ length: 2600 }, (_entry, index) => `step${index}();`);
    const added = [];
    for (let index = 0; index < 2600; index += 2) {
      added.push(`step${index + 1}();`, `step${index}();`);
    }
    const patch = [
      "@@ -1,2600 +1,2600 @@",
      ...removed.map((line) => `-${line}`),
      ...added.map((line) => `+${line}`),
    ].join("\n");
    const scope = classifyPrScope({
      changedFiles: [
        {
          filename: "bounded-contexts/catalog/features/search/domain/permuted.ts",
          status: "modified",
          additions: 2600,
          deletions: 2600,
          patch,
        },
      ],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.raw).toEqual({ additions: 2600, deletions: 2600, lines: 5200, files: 1 });
    expect(scope.normalized).toEqual({ additions: 2600, deletions: 2600, lines: 5200, files: 1 });
    expect(scope.status).toBe("large");
  });

  it("always counts migrations even though they sit beside normally-excluded shapes", () => {
    const scope = classifyPrScope({
      changedFiles: [
        file({ filename: "bounded-contexts/catalog/migrations/020-add-index.sql", additions: 300, deletions: 0 }),
      ],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.normalized.lines).toBe(300);
  });

  it("always counts workflow files", () => {
    const scope = classifyPrScope({
      changedFiles: [file({ filename: ".github/workflows/platform-pr.yml", additions: 120, deletions: 30 })],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.normalized.lines).toBe(150);
  });

  it("always counts test sources", () => {
    const scope = classifyPrScope({
      changedFiles: [
        file({
          filename: "bounded-contexts/catalog/features/search/domain/search.test.ts",
          additions: 90,
          deletions: 10,
        }),
      ],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.normalized.lines).toBe(100);
  });

  it("always counts handwritten generator sources, not just their generated output", () => {
    const scope = classifyPrScope({
      changedFiles: [file({ filename: "scripts/generate-context-registry.mjs", additions: 80, deletions: 20 })],
    });
    expect(scope.excluded.entries).toEqual([]);
    expect(scope.normalized.lines).toBe(100);
  });

  it("reports bounded contexts and composition roots from mixed-context changes", () => {
    const scope = classifyPrScope({
      changedFiles: [
        file({ filename: "bounded-contexts/catalog/features/search/domain/search.ts" }),
        file({ filename: "bounded-contexts/pricing/features/estimates/domain/estimate.ts" }),
        file({ filename: "deployables/marketplace/app/routes.tsx", additions: 5, deletions: 1 }),
      ],
    });
    expect(scope.boundedContexts).toEqual(["catalog", "pricing"]);
    expect(scope.compositionRoots).toEqual(["deployables/marketplace"]);
    expect(scope.splitSuggestion).toEqual({
      reason: "Multiple bounded contexts changed in one PR",
      boundaries: ["catalog", "pricing"],
    });
  });

  it("does not suggest a split for a single bounded context even when large", () => {
    const scope = classifyPrScope({ changedFiles: filesOfSize(40, 100) });
    expect(scope.status).toBe("large");
    expect(scope.splitSuggestion).toBeNull();
  });

  it("classifies renames by old and new path for bounded-context detection", () => {
    const scope = classifyPrScope({
      changedFiles: [
        file({
          filename: "bounded-contexts/catalog/features/search/domain/renamed.ts",
          previousFilename: "bounded-contexts/pricing/features/search/domain/renamed.ts",
          status: "renamed",
          additions: 0,
          deletions: 0,
          patch: null,
        }),
      ],
    });
    expect(scope.boundedContexts).toEqual(["catalog", "pricing"]);
    expect(scope.excluded.entries).toEqual([]);
  });

  it("counts deletions toward normalized scope", () => {
    const scope = classifyPrScope({
      changedFiles: [
        file({
          filename: "bounded-contexts/catalog/features/search/domain/old.ts",
          status: "removed",
          additions: 0,
          deletions: 400,
          patch: "@@ -1,400 +0,0 @@\n" + "-line\n".repeat(400),
        }),
      ],
    });
    expect(scope.normalized.lines).toBe(400);
    expect(scope.status).toBe("normal");
  });

  describe("threshold boundaries", () => {
    it("stays normal exactly at the advisory line boundary", () => {
      const scope = classifyPrScope({ changedFiles: filesOfSize(1, ADVISORY_THRESHOLD.lines) });
      expect(scope.normalized.lines).toBe(ADVISORY_THRESHOLD.lines);
      expect(scope.status).toBe("normal");
    });

    it("goes advisory one line past the advisory line boundary", () => {
      const scope = classifyPrScope({ changedFiles: filesOfSize(1, ADVISORY_THRESHOLD.lines + 1) });
      expect(scope.status).toBe("advisory");
    });

    it("stays normal exactly at the advisory file-count boundary", () => {
      const scope = classifyPrScope({ changedFiles: filesOfSize(ADVISORY_THRESHOLD.files, 1) });
      expect(scope.status).toBe("normal");
    });

    it("goes advisory one file past the advisory file-count boundary", () => {
      const scope = classifyPrScope({ changedFiles: filesOfSize(ADVISORY_THRESHOLD.files + 1, 1) });
      expect(scope.status).toBe("advisory");
    });

    it("stays advisory exactly at the large line boundary", () => {
      const scope = classifyPrScope({ changedFiles: filesOfSize(1, LARGE_THRESHOLD.lines) });
      expect(scope.status).toBe("advisory");
    });

    it("goes large one line past the large line boundary", () => {
      const scope = classifyPrScope({ changedFiles: filesOfSize(1, LARGE_THRESHOLD.lines + 1) });
      expect(scope.status).toBe("large");
    });

    it("stays advisory exactly at the large file-count boundary", () => {
      const scope = classifyPrScope({ changedFiles: filesOfSize(LARGE_THRESHOLD.files, 1) });
      expect(scope.status).toBe("advisory");
    });

    it("goes large one file past the large file-count boundary", () => {
      const scope = classifyPrScope({ changedFiles: filesOfSize(LARGE_THRESHOLD.files + 1, 1) });
      expect(scope.status).toBe("large");
    });

    it("is large on a mixed criterion: file count breaches large while lines stay under advisory", () => {
      const scope = classifyPrScope({ changedFiles: filesOfSize(LARGE_THRESHOLD.files + 1, 1) });
      expect(scope.normalized.lines).toBeLessThan(ADVISORY_THRESHOLD.lines);
      expect(scope.status).toBe("large");
    });
  });

  it("reuses the canonical risk-policy categories rather than a divergent list", () => {
    const scope = classifyPrScope({
      changedFiles: [file({ filename: "bounded-contexts/payments/features/refunds/domain/refund.ts" })],
    });
    expect(scope.risk.categories).toContain("money-movement");
  });

  it("rejects a non-array changedFiles input", () => {
    expect(() => classifyPrScope({ changedFiles: null })).toThrow(TypeError);
  });
});
