import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import type { PgPoolClient, PgTransactionalPool } from "@chase-sets/event-core-postgres";
import type { ProjectorHandler, ProjectorHandlerMap } from "@chase-sets/event-core/projector";
import type { TransportEvent } from "@chase-sets/event-core/transport";
import {
  closeMultiContextTestPools,
  createMultiContextTestDatabaseUrls,
  createMultiContextTestPools,
  ensureMultiContextTestDatabases,
  resetMultiContextTestSchemas,
} from "@chase-sets/bounded-context-runtime/test-support";
import { module as platformOperationsModule } from "../../../index";
import {
  addUtcMonths,
  isLookbackAnchorEligible,
  listSellerCompletedSalesPage,
  listSellersWithChangedCompletedSales,
  listSellersWithSalesOccurringInWindow,
  readSellerCompletedSalesSnapshotToken,
  readSellerComplianceSnapshotChangeSequence,
  snapshotTokensMatch,
  type SellerSaleCursor,
} from "./queries";

// phantom-SQL rule: exercised against a real Postgres sandbox
// (TEST_DATABASE_URL, see .env.sandbox.local / dev:bootstrap), never mocked.
const databaseBaseUrl = process.env.TEST_DATABASE_URL;
if (!databaseBaseUrl && process.env.CI) {
  throw new Error("TEST_DATABASE_URL is required for database-backed tests in CI.");
}
const describeDb = databaseBaseUrl ? describe : describe.skip;
const contextNames = ["platform-operations"] as const;

// Unmistakably synthetic identities: nothing here is paired with a real account, order, or
// payment, and every value is generated by this file.
const SELLER = "acct_synthetic_seller_1";
const OTHER_SELLER = "acct_synthetic_seller_2";
const ORDER_ONE = "ord_synthetic_1";
const ORDER_TWO = "ord_synthetic_2";
const PAYMENT = "pay_synthetic_1";
const CAPTURED_AT = "2026-03-01T00:00:00.000Z";
const CANCELLED_AT = "2026-02-15T00:00:00.000Z";
const REFUNDED_AT = "2026-04-01T00:00:00.000Z";
/**
 * One fixed observation instant for every event envelope. `recorded_at` and `changed_at`
 * are assigned from the event's own recorded timing so a rebuild is deterministic; holding
 * it constant lets two different arrival orders be compared on those columns too.
 */
const RECORDED_AT = "2026-05-01T00:00:00.000Z";

const ORDER_MONEY = {
  itemSubtotalAmount: "100.00",
  shippingChargeAmount: "5.00",
  shippingAllowanceAmount: "5.00",
  shippingBaseAmount: "5.00",
  shippingDiscountAmount: "0.00",
  shippingOverageAmount: "5.00",
  salesTaxAmount: "8.00",
  protectionAmount: "0.00",
  protectionAllowanceAmount: "0.00",
  protectionOverageAmount: "0.00",
  totalAmount: "113.00",
} as const;

function payout(orderId: string, overrides: Readonly<Record<string, unknown>> = {}) {
  return {
    orderId,
    sellerAccountId: SELLER,
    marketplaceSalesFeeAmount: "10.00",
    sellerItemNetAmount: "90.00",
    shippingAllowanceAmount: "5.00",
    sellerShippingPayoutAmount: "5.00",
    protectionAmount: "0.00",
    protectionAllowanceAmount: "0.00",
    protectionOverageAmount: "0.00",
    sellerPayoutAmount: "95.00",
    ...overrides,
  };
}

let eventSequence = 0;

function transportEvent(
  type: string,
  streamId: string,
  streamVersion: number,
  data: Readonly<Record<string, unknown>>,
  occurredAt: string,
): TransportEvent {
  eventSequence += 1;
  return {
    id: `evt_synthetic_${eventSequence}`,
    type,
    streamId,
    streamVersion,
    globalPosition: String(eventSequence),
    tenantId: "tenant_synthetic",
    data,
    metadata: {},
    audit: { performedByUserId: "usr_synthetic", forAccountId: "acct_synthetic" },
    trace: {},
    timing: { occurredAt, recordedAt: RECORDED_AT },
  } as unknown as TransportEvent;
}

function orderCreated(orderId: string, streamVersion: number, overrides: Readonly<Record<string, unknown>> = {}) {
  return transportEvent(
    "ordering.order.created",
    `ordering.order-${orderId}`,
    streamVersion,
    {
      orderId,
      sellerAccountId: SELLER,
      ...ORDER_MONEY,
      authenticityPlanSnapshot: null,
      lines: [
        {
          lineId: `${orderId}-line-1`,
          catalogItemId: "cat_synthetic_1",
          productId: "prd_synthetic_1",
          itemTitle: "Synthetic Title",
          selectedOptions: [{ dimensionId: "printing", optionId: "holofoil" }],
          quantity: 1,
          lineTotalAmount: "100.00",
          gradedCard: { gradingCompany: "PSA", grade: "10", certificationNumber: "9999999" },
        },
      ],
      reservationRequests: [],
      ...overrides,
    },
    "2026-01-10T00:00:00.000Z",
  );
}

function orderCancelled(orderId: string, streamVersion: number) {
  return transportEvent(
    "ordering.order.cancelled",
    `ordering.order-${orderId}`,
    streamVersion,
    { orderId, cancelledAt: CANCELLED_AT, reservationRequests: [] },
    CANCELLED_AT,
  );
}

function paymentCaptured(streamVersion: number, overrides: Readonly<Record<string, unknown>> = {}) {
  return transportEvent(
    "payments.payment-captured",
    `payments.payment-${PAYMENT}`,
    streamVersion,
    {
      paymentId: PAYMENT,
      orderIds: [ORDER_ONE],
      sellerPayouts: [payout(ORDER_ONE)],
      currencyCode: "usd",
      capturedAt: CAPTURED_AT,
      ...overrides,
    },
    CAPTURED_AT,
  );
}

function paymentRefunded(streamVersion: number, overrides: Readonly<Record<string, unknown>> = {}) {
  return transportEvent(
    "payments.payment-refunded",
    `payments.payment-${PAYMENT}`,
    streamVersion,
    {
      paymentId: PAYMENT,
      orderIds: [ORDER_ONE],
      refundedOrderAmounts: [{ orderId: ORDER_ONE, amount: "40.00" }],
      orderRefundCaps: [
        { orderId: ORDER_ONE, amount: "113.00" },
        { orderId: ORDER_TWO, amount: "50.00" },
      ],
      currencyCode: "usd",
      refundedAt: REFUNDED_AT,
      ...overrides,
    },
    REFUNDED_AT,
  );
}

describeDb("platform-operations seller compliance sale facts", () => {
  let pools: Readonly<Record<(typeof contextNames)[number], PgTransactionalPool>>;
  let pool: PgTransactionalPool;

  /**
   * Handlers are always resolved through the production manifest registration rather than
   * imported directly, so a broken registration fails these tests instead of passing a
   * direct-handler fixture.
   */
  function registeredHandlers(): ProjectorHandlerMap {
    const services = platformOperationsModule.createServices(pool, {});
    const subscriptions = (platformOperationsModule.buildSubscriptions?.(services) ?? []).filter(
      (subscription) => subscription.projectionName === "seller-compliance-sales-projection",
    );
    expect(subscriptions).toHaveLength(2);
    return Object.assign({}, ...subscriptions.map((subscription) => subscription.handlers)) as ProjectorHandlerMap;
  }

  async function deliverWith(handlers: ProjectorHandlerMap, event: TransportEvent, client?: PgPoolClient) {
    const handler = (handlers as Readonly<Record<string, ProjectorHandler | undefined>>)[event.type];
    if (!handler) throw new Error(`No registered handler for ${event.type}`);
    if (client) {
      await handler(event, { db: client });
      return;
    }
    const scoped = await pool.connect();
    try {
      await scoped.query("BEGIN");
      await handler(event, { db: scoped });
      await scoped.query("COMMIT");
    } catch (error) {
      await scoped.query("ROLLBACK");
      throw error;
    } finally {
      scoped.release();
    }
  }

  /** Each delivery rebuilds the handler set, which is also the process-restart control. */
  async function deliver(...events: readonly TransportEvent[]) {
    for (const event of events) {
      await deliverWith(registeredHandlers(), event);
    }
  }

  async function readSales() {
    const result = await pool.query(
      `SELECT * FROM platform_operations_seller_compliance_sales ORDER BY payment_id, order_id`,
    );
    return result.rows as Readonly<Record<string, unknown>>[];
  }

  async function readOrderFacts() {
    const result = await pool.query(
      `SELECT * FROM platform_operations_seller_compliance_order_facts ORDER BY order_id`,
    );
    return result.rows as Readonly<Record<string, unknown>>[];
  }

  function withoutWriteMetadata(row: Readonly<Record<string, unknown>>) {
    const { revision, change_sequence, ...facts } = row;
    void revision;
    void change_sequence;
    return facts;
  }

  beforeAll(async () => {
    const databaseUrls = createMultiContextTestDatabaseUrls(
      databaseBaseUrl!,
      contextNames,
      "platform_operations_seller_compliance_sales",
    );
    await ensureMultiContextTestDatabases(databaseBaseUrl!, databaseUrls);
    pools = createMultiContextTestPools(databaseUrls);
    pool = pools["platform-operations"];
  });

  beforeEach(async () => {
    await resetMultiContextTestSchemas(pools);
    await pool.query(platformOperationsModule.schemaSql);
  });

  afterAll(async () => {
    await closeMultiContextTestPools(pools);
  });

  it("converges ordering-first and capture-first histories across restart", async () => {
    await deliver(orderCreated(ORDER_ONE, 1), orderCancelled(ORDER_ONE, 2), paymentCaptured(1));
    const orderFirst = await readSales();
    expect(orderFirst).toHaveLength(1);

    await resetMultiContextTestSchemas(pools);
    await pool.query(platformOperationsModule.schemaSql);

    await deliver(paymentCaptured(1), orderCreated(ORDER_ONE, 1), orderCancelled(ORDER_ONE, 2));
    const captureFirst = await readSales();
    expect(captureFirst).toHaveLength(1);

    // Every recorded fact converges. `revision` and `change_sequence` are this row's write
    // and enumeration metadata: the capture-first history genuinely took more writes to
    // reach the same facts, and asserting they matched would assert a falsehood.
    expect(withoutWriteMetadata(captureFirst[0]!)).toEqual(withoutWriteMetadata(orderFirst[0]!));

    expect(orderFirst[0]).toMatchObject({
      payment_id: PAYMENT,
      order_id: ORDER_ONE,
      seller_account_id: SELLER,
      sale_state: "captured",
      currency_code: "usd",
      item_gross_cents: "10000",
      order_total_cents: "11300",
      seller_payout_cents: "9500",
      capture_anomalies: [],
      refund_anomalies: [],
      reconciliation_mismatches: [],
      refunded_order_total_cents: null,
      order_refund_cap_cents: null,
    });
    expect(orderFirst[0]!.occurred_at).toEqual(new Date(CAPTURED_AT));
    expect(orderFirst[0]!.cancelled_at).toEqual(new Date(CANCELLED_AT));
    expect(orderFirst[0]!.recorded_at).toEqual(new Date(RECORDED_AT));
  });

  it("keeps an order-only staging row out of completed sales until payment identity arrives", async () => {
    await deliver(orderCreated(ORDER_ONE, 1));
    expect(await readSales()).toEqual([]);
    const staging = await readOrderFacts();
    expect(staging).toHaveLength(1);
    expect(staging[0]).toMatchObject({ lifecycle_state: "awaiting-capture", seller_account_id: SELLER });

    await deliver(orderCancelled(ORDER_ONE, 2));
    expect((await readOrderFacts())[0]).toMatchObject({
      lifecycle_state: "cancelled-awaiting-capture",
      item_subtotal_amount: "100.00",
    });
    expect(await readSales()).toEqual([]);
  });

  it("binds one affected order to payment-scoped cumulative refund entries under replay", async () => {
    const twoOrderCapture = paymentCaptured(1, {
      orderIds: [ORDER_ONE, ORDER_TWO],
      sellerPayouts: [payout(ORDER_ONE), payout(ORDER_TWO)],
    });
    await deliver(orderCreated(ORDER_ONE, 1), orderCreated(ORDER_TWO, 1), twoOrderCapture);

    const beforeRefund = await readSales();
    expect(beforeRefund.map((row) => row.refunded_order_total_cents)).toEqual([null, null]);
    expect(beforeRefund.map((row) => row.order_refund_cap_cents)).toEqual([null, null]);

    await deliver(paymentRefunded(2));
    const [affected, unaffected] = await readSales();

    // The affected order takes its cumulative total and cap; the unaffected order's
    // payment-wide cap entry is ignored and leaves it null.
    expect(affected).toMatchObject({
      order_id: ORDER_ONE,
      refunded_order_total_cents: "4000",
      order_refund_cap_cents: "11300",
      refund_anomalies: [],
      item_gross_cents: "10000",
    });
    expect(affected!.refund_observed_at).toEqual(new Date(REFUNDED_AT));
    expect(unaffected).toMatchObject({
      order_id: ORDER_TWO,
      refunded_order_total_cents: null,
      order_refund_cap_cents: null,
      refund_anomalies: [],
      refund_observed_at: null,
    });

    // Full-refund equality is decidable for the affected order from its own two values.
    expect(affected!.refunded_order_total_cents === affected!.order_refund_cap_cents).toBe(false);

    // Shuffled entry order and redelivery assign rather than accumulate.
    const shuffled = paymentRefunded(3, {
      orderRefundCaps: [
        { orderId: ORDER_TWO, amount: "50.00" },
        { orderId: ORDER_ONE, amount: "113.00" },
      ],
      refundedOrderAmounts: [
        { orderId: ORDER_TWO, amount: "7.00" },
        { orderId: ORDER_ONE, amount: "40.00" },
      ],
    });
    await deliver(shuffled, shuffled, paymentRefunded(2));
    const afterRedelivery = await readSales();
    expect(afterRedelivery[0]).toMatchObject({
      refunded_order_total_cents: "4000",
      order_refund_cap_cents: "11300",
    });
    expect(afterRedelivery[1]!.refunded_order_total_cents).toBeNull();
  });

  it("assigns affected-order cumulative refund facts and preserves money across redelivery", async () => {
    const twoOrderCapture = paymentCaptured(1, {
      orderIds: [ORDER_ONE, ORDER_TWO],
      sellerPayouts: [payout(ORDER_ONE), payout(ORDER_TWO)],
    });
    await deliver(orderCreated(ORDER_ONE, 1), orderCreated(ORDER_TWO, 1), twoOrderCapture, paymentRefunded(2));

    const moneyBefore = (await readSales()).map((row) => [row.item_gross_cents, row.seller_payout_cents]);

    // A cancellation changes only cancellation metadata; money is never rewritten.
    await deliver(orderCancelled(ORDER_ONE, 2));
    const afterCancellation = await readSales();
    expect(afterCancellation.map((row) => [row.item_gross_cents, row.seller_payout_cents])).toEqual(moneyBefore);
    expect(afterCancellation[0]!.cancelled_at).toEqual(new Date(CANCELLED_AT));
    expect(afterCancellation[0]).toMatchObject({ refunded_order_total_cents: "4000", order_refund_cap_cents: "11300" });

    // Duplicate and missing affected entries fail closed and leave the affected order null.
    for (const [label, overrides] of [
      [
        "duplicate amount entry",
        {
          refundedOrderAmounts: [
            { orderId: ORDER_ONE, amount: "40.00" },
            { orderId: ORDER_ONE, amount: "40.00" },
          ],
        },
      ],
      ["missing amount entry", { refundedOrderAmounts: [{ orderId: ORDER_TWO, amount: "7.00" }] }],
      ["missing cap entry", { orderRefundCaps: [{ orderId: ORDER_TWO, amount: "50.00" }] }],
      [
        "duplicate cap entry",
        {
          orderRefundCaps: [
            { orderId: ORDER_ONE, amount: "113.00" },
            { orderId: ORDER_ONE, amount: "113.00" },
          ],
        },
      ],
      ["noncanonical amount", { refundedOrderAmounts: [{ orderId: ORDER_ONE, amount: "40.3" }] }],
      ["invalid currency", { currencyCode: "USD" }],
    ] as const) {
      await resetMultiContextTestSchemas(pools);
      await pool.query(platformOperationsModule.schemaSql);
      await deliver(orderCreated(ORDER_ONE, 1), orderCreated(ORDER_TWO, 1), twoOrderCapture, paymentRefunded(2, overrides));
      const [row] = await readSales();
      expect(row!.refunded_order_total_cents, label).toBeNull();
      expect(row!.order_refund_cap_cents, label).toBeNull();
      expect((row!.refund_anomalies as string[]).length, label).toBeGreaterThan(0);
      // Capture-side money survives a refund defect: the two groups are independent.
      expect(row!.item_gross_cents, label).toBe("10000");
    }
  });

  it("classifies every combined payout anomaly deterministically", async () => {
    // `seller-mismatch` compares the *sole* payout component against Ordering's
    // authoritative seller, so the row carrying all eight reasons must itself have exactly
    // one payout; the other seven come from the capture-atomic defects around it.
    await deliver(
      orderCreated(ORDER_ONE, 1),
      paymentCaptured(1, {
        orderIds: [ORDER_ONE, ORDER_ONE, ORDER_TWO, "ord_synthetic_3"],
        sellerPayouts: [
          payout(ORDER_ONE, { sellerAccountId: OTHER_SELLER }),
          payout(ORDER_TWO, { sellerPayoutAmount: "12.3" }),
          payout(ORDER_TWO, { protectionAmount: undefined }),
          payout("ord_synthetic_extra"),
        ],
        currencyCode: "USD",
      }),
    );

    const [row] = await readSales();
    expect(row!.order_id).toBe(ORDER_ONE);
    expect(row!.capture_anomalies).toEqual([
      "duplicate-capture-order-id",
      "extra-payout-component",
      "duplicate-payout-component",
      "missing-payout-component",
      "seller-mismatch",
      "currency-invalid",
      "canonical-money-invalid",
      "source-field-missing",
    ]);
    expect(row!.sale_state).toBe("captured-unreconciled");
    for (const column of [
      "item_gross_cents",
      "shipping_charge_cents",
      "sales_tax_cents",
      "authenticity_fee_cents",
      "protection_cents",
      "order_total_cents",
      "marketplace_sales_fee_cents",
      "seller_item_net_cents",
      "shipping_allowance_cents",
      "seller_shipping_payout_cents",
      "seller_payout_cents",
    ]) {
      expect(row![column], column).toBeNull();
    }
  });

  it("distinguishes every approved decision input from stored facts only", async () => {
    await deliver(orderCreated(ORDER_ONE, 1), paymentCaptured(1));
    const [row] = await readSales();

    // Item gross cross-checks the order subtotal against seller net plus marketplace fee,
    // and every other approved input stays a distinct stored column.
    expect(BigInt(row!.item_gross_cents as string)).toBe(
      BigInt(row!.seller_item_net_cents as string) + BigInt(row!.marketplace_sales_fee_cents as string),
    );
    expect({
      itemGross: row!.item_gross_cents,
      shipping: row!.shipping_charge_cents,
      tax: row!.sales_tax_cents,
      authenticity: row!.authenticity_fee_cents,
      protection: row!.protection_cents,
      orderTotal: row!.order_total_cents,
      payout: row!.seller_payout_cents,
      refundTotal: row!.refunded_order_total_cents,
      refundCap: row!.order_refund_cap_cents,
    }).toEqual({
      itemGross: "10000",
      shipping: "500",
      tax: "800",
      authenticity: "0",
      protection: "0",
      orderTotal: "11300",
      payout: "9500",
      refundTotal: null,
      refundCap: null,
    });

    expect(row!.classification_inputs).toEqual([
      {
        lineId: `${ORDER_ONE}-line-1`,
        catalogItemId: "cat_synthetic_1",
        productId: "prd_synthetic_1",
        selectedOptions: [{ dimensionId: "printing", optionId: "holofoil" }],
        quantity: 1,
        lineTotalAmount: "100.00",
        gradedCard: { gradingCompany: "PSA", grade: "10" },
      },
    ]);
    expect(row!.classification_inputs_version).toBe(1);
    expect(row!.occurred_at).toEqual(new Date(CAPTURED_AT));

    // A null authenticity plan is Ordering's authoritative no-fee value, not an inferred zero.
    await deliver(orderCreated(ORDER_TWO, 1, { authenticityPlanSnapshot: { feeAmount: "12.00" } }));
    expect((await readOrderFacts()).map((fact) => fact.authenticity_fee_amount)).toEqual(["0.00", "12.00"]);
  });

  it("guards each source field group independently", async () => {
    // A higher-versioned refund arrives before its lower-versioned capture and must not
    // suppress the capture group.
    await deliver(paymentRefunded(5), paymentCaptured(2), orderCreated(ORDER_ONE, 1));
    const [afterAll] = await readSales();
    expect(afterAll).toMatchObject({
      sale_state: "captured",
      item_gross_cents: "10000",
      refunded_order_total_cents: "4000",
      payment_captured_source_version: "2",
      payment_refunded_source_version: "5",
    });
    expect(afterAll!.occurred_at).toEqual(new Date(CAPTURED_AT));

    // A stale group version updates nothing.
    const before = await readSales();
    await deliver(paymentCaptured(1, { capturedAt: "2020-01-01T00:00:00.000Z" }), orderCreated(ORDER_ONE, 1));
    expect(await readSales()).toEqual(before);

    // A cancellation does not block or rewrite creation fields.
    await deliver(orderCancelled(ORDER_ONE, 2));
    const cancelled = await readSales();
    expect(cancelled[0]).toMatchObject({ item_gross_cents: "10000", order_cancelled_source_version: "2" });
    expect(cancelled[0]!.cancelled_at).toEqual(new Date(CANCELLED_AT));
  });

  it("converges when an Ordering and a Payments transaction interleave on one order", async () => {
    const handlers = registeredHandlers();
    const left = await pool.connect();
    const right = await pool.connect();
    try {
      await left.query("BEGIN");
      await right.query("BEGIN");
      // Both transactions target the same order; the order-scope advisory lock serializes
      // them, so neither can read a stale row and clobber the other's write.
      const leftWork = deliverWith(handlers, paymentCaptured(1), left).then(() => left.query("COMMIT"));
      const rightWork = (async () => {
        await new Promise((resolve) => setTimeout(resolve, 25));
        await deliverWith(handlers, orderCreated(ORDER_ONE, 1), right);
        await right.query("COMMIT");
      })();
      await Promise.all([leftWork, rightWork]);
    } finally {
      left.release();
      right.release();
    }

    const [row] = await readSales();
    expect(row).toMatchObject({ sale_state: "captured", seller_account_id: SELLER, item_gross_cents: "10000" });
  });

  it("rebuilds both temporal relations column for column", async () => {
    const history = [
      orderCreated(ORDER_ONE, 1),
      paymentRefunded(5),
      paymentCaptured(2, {
        orderIds: [ORDER_ONE, ORDER_TWO],
        // A per-row reason: only the second order's sole payout names a different seller
        // than Ordering's authority, so the two rows must reach different steady states.
        sellerPayouts: [payout(ORDER_ONE), payout(ORDER_TWO, { sellerAccountId: OTHER_SELLER })],
      }),
      orderCancelled(ORDER_ONE, 2),
      orderCreated(ORDER_TWO, 1),
      // Day-after duplicate delivery at a steady state must be inert.
      paymentCaptured(2, {
        orderIds: [ORDER_ONE, ORDER_TWO],
        // A per-row reason: only the second order's sole payout names a different seller
        // than Ordering's authority, so the two rows must reach different steady states.
        sellerPayouts: [payout(ORDER_ONE), payout(ORDER_TWO, { sellerAccountId: OTHER_SELLER })],
      }),
    ];

    await deliver(...history);
    const liveSales = await readSales();
    const liveOrderFacts = await readOrderFacts();
    expect(liveSales).toHaveLength(2);
    expect(liveSales.map((row) => row.sale_state)).toEqual(["captured", "captured-unreconciled"]);

    await resetMultiContextTestSchemas(pools);
    await pool.query(platformOperationsModule.schemaSql);
    await deliver(...history);

    // Full ordered equality, including revision and change_sequence: the same ordered
    // history replayed into an empty schema reproduces every column exactly.
    expect(await readSales()).toEqual(liveSales);
    expect(await readOrderFacts()).toEqual(liveOrderFacts);
  });

  it("creates the temporal fact schema without consumer or provider data", async () => {
    const columns = await pool.query<{ table_name: string; column_name: string; data_type: string }>(
      `SELECT table_name, column_name, data_type
       FROM information_schema.columns
       WHERE table_schema = current_schema()
         AND table_name IN (
           'platform_operations_seller_compliance_order_facts',
           'platform_operations_seller_compliance_sales'
         )
       ORDER BY table_name, column_name`,
    );

    const byTable = new Map<string, string[]>();
    for (const row of columns.rows) {
      byTable.set(row.table_name, [...(byTable.get(row.table_name) ?? []), row.column_name]);
    }

    expect(byTable.get("platform_operations_seller_compliance_order_facts")).toEqual([
      "authenticity_fee_amount",
      "cancelled_at",
      "changed_at",
      "classification_inputs",
      "classification_inputs_version",
      "first_observed_at",
      "item_subtotal_amount",
      "lifecycle_state",
      "order_cancelled_source_version",
      "order_created_source_version",
      "order_id",
      "order_total_amount",
      "protection_allowance_amount",
      "protection_amount",
      "protection_overage_amount",
      "revision",
      "sales_tax_amount",
      "seller_account_id",
      "shipping_allowance_amount",
      "shipping_charge_amount",
    ]);

    expect(byTable.get("platform_operations_seller_compliance_sales")).toEqual([
      "authenticity_fee_cents",
      "cancelled_at",
      "capture_anomalies",
      "capture_atomic_anomalies",
      "capture_marketplace_sales_fee_amount",
      "capture_payout_seller_account_id",
      "capture_protection_allowance_amount",
      "capture_protection_amount",
      "capture_protection_overage_amount",
      "capture_seller_item_net_amount",
      "capture_seller_payout_amount",
      "capture_seller_shipping_payout_amount",
      "capture_shipping_allowance_amount",
      "change_sequence",
      "changed_at",
      "classification_inputs",
      "classification_inputs_version",
      "currency_code",
      "item_gross_cents",
      "marketplace_sales_fee_cents",
      "occurred_at",
      "order_cancelled_source_version",
      "order_created_source_version",
      "order_id",
      "order_refund_cap_cents",
      "order_total_cents",
      "payment_captured_source_version",
      "payment_id",
      "payment_refunded_source_version",
      "protection_allowance_cents",
      "protection_cents",
      "protection_overage_cents",
      "reconciliation_mismatches",
      "recorded_at",
      "refund_anomalies",
      "refund_observed_at",
      "refunded_order_total_cents",
      "revision",
      "sale_state",
      "sales_tax_cents",
      "seller_account_id",
      "seller_item_net_cents",
      "seller_payout_cents",
      "seller_shipping_payout_cents",
      "shipping_allowance_cents",
      "shipping_charge_cents",
    ]);

    // No consumer or provider data. `sales_tax_cents` is the buyer-charged sales tax money
    // amount the approved matrix keeps distinct from item gross; the excluded tax concepts
    // are the jurisdiction/provider snapshot, which is never copied out of Ordering.
    const everyColumn = columns.rows.map((row) => row.column_name);
    for (const forbidden of [
      "buyer",
      "address",
      "email",
      "processor",
      "secret",
      "certification",
      "provider",
      "jurisdiction",
      "taxable",
      "tax_snapshot",
      "shipping_destination",
      "shipping_origin",
    ]) {
      expect(
        everyColumn.filter((column) => column.includes(forbidden)),
        forbidden,
      ).toEqual([]);
    }

    const indexes = await pool.query<{ indexname: string }>(
      `SELECT indexname FROM pg_indexes
       WHERE schemaname = current_schema()
         AND tablename IN (
           'platform_operations_seller_compliance_order_facts',
           'platform_operations_seller_compliance_sales'
         )
       ORDER BY indexname`,
    );
    expect(indexes.rows.map((row) => row.indexname)).toEqual([
      "platform_operations_seller_compliance_order_facts_pkey",
      "platform_operations_seller_compliance_sales_change_seq_idx",
      "platform_operations_seller_compliance_sales_changed_at_idx",
      "platform_operations_seller_compliance_sales_occurrence_idx",
      "platform_operations_seller_compliance_sales_order_idx",
      "platform_operations_seller_compliance_sales_pkey",
    ]);

    const sequences = await pool.query<{ sequence_name: string }>(
      `SELECT sequence_name FROM information_schema.sequences
       WHERE sequence_schema = current_schema()
         AND sequence_name = 'platform_operations_seller_compliance_sales_change_seq'`,
    );
    expect(sequences.rows).toHaveLength(1);

    // The ledgered migration alone produces the identical schema on a database booted
    // before this slice existed.
    await pool.query(`DROP TABLE platform_operations_seller_compliance_sales`);
    await pool.query(`DROP TABLE platform_operations_seller_compliance_order_facts`);
    await pool.query(`DROP SEQUENCE platform_operations_seller_compliance_sales_change_seq`);
    for (const migration of platformOperationsModule.schemaMigrations ?? []) {
      if (!migration.migrationId.includes("seller_compliance")) continue;
      for (const statement of migration.statements) {
        await pool.query(statement);
      }
    }
    const migratedColumns = await pool.query<{ table_name: string; column_name: string }>(
      `SELECT table_name, column_name
       FROM information_schema.columns
       WHERE table_schema = current_schema()
         AND table_name IN (
           'platform_operations_seller_compliance_order_facts',
           'platform_operations_seller_compliance_sales'
         )
       ORDER BY table_name, column_name`,
    );
    expect(migratedColumns.rows).toEqual(columns.rows.map(({ table_name, column_name }) => ({ table_name, column_name })));
  });

  it("uses one half-open millisecond boundary for reads and expiry handoff", async () => {
    const from = "2026-03-01T00:00:00.000Z";
    const to = "2026-06-01T00:00:00.000Z";
    const edges = [
      ["2026-02-28T23:59:59.999Z", false],
      [from, true],
      ["2026-05-31T23:59:59.999Z", true],
      [to, false],
    ] as const;

    await seedCompletedSales(
      pool,
      edges.map(([occurredAt], index) => ({
        paymentId: `pay_synthetic_edge_${index}`,
        orderId: `ord_synthetic_edge_${index}`,
        sellerAccountId: SELLER,
        occurredAt,
      })),
    );

    const page = await listSellerCompletedSalesPage(pool, {
      sellerAccountId: SELLER,
      fromInclusive: from,
      toExclusive: to,
      limit: 10,
    });
    expect(page.sales.map((sale) => sale.occurredAt)).toEqual(
      edges.filter(([, included]) => included).map(([occurredAt]) => occurredAt),
    );
    expect(page.nextCursor).toBeNull();

    // A sale at the evaluation instant is excluded by the same half-open convention.
    const atEvaluation = await listSellerCompletedSalesPage(pool, {
      sellerAccountId: SELLER,
      fromInclusive: from,
      toExclusive: "2026-05-31T23:59:59.999Z",
      limit: 10,
    });
    expect(atEvaluation.sales.map((sale) => sale.occurredAt)).toEqual([from]);

    // The inclusive lookback floor expires at the nominal instant plus exactly 1 ms.
    expect(addUtcMonths(from, 3)).toBe(to);
    expect(isLookbackAnchorEligible(from, 3, to)).toBe(true);
    expect(isLookbackAnchorEligible(from, 3, "2026-06-01T00:00:00.001Z")).toBe(false);
  });

  it("enumerates a fixed seller snapshot in terminating keyset pages", async () => {
    const sellers = Array.from({ length: 250 }, (_unused, index) => `acct_synthetic_seller_${String(index).padStart(4, "0")}`);
    await seedCompletedSales(
      pool,
      sellers.map((sellerAccountId, index) => ({
        paymentId: `pay_synthetic_${index}`,
        orderId: `ord_synthetic_${index}`,
        sellerAccountId,
        // Identical sort keys at the page boundaries prove the seller id is what pages.
        occurredAt: "2026-03-15T00:00:00.000Z",
        changedAt: "2026-03-15T00:00:00.000Z",
      })),
    );

    const snapshot = await readSellerComplianceSnapshotChangeSequence(pool);
    const window = { fromInclusive: "2026-01-01T00:00:00.000Z", toExclusive: "2026-06-01T00:00:00.000Z" };
    const seen: string[] = [];
    const cursors: (string | null)[] = [];
    let cursor: string | null = null;
    let pages = 0;
    do {
      const page: Awaited<ReturnType<typeof listSellersWithChangedCompletedSales>> =
        await listSellersWithChangedCompletedSales(pool, {
          ...window,
          snapshotChangeSequence: snapshot,
          afterSellerAccountId: cursor,
          limit: 100,
        });
      pages += 1;
      seen.push(...page.sellerAccountIds);
      cursors.push(page.nextCursor);
      cursor = page.nextCursor;
    } while (cursor !== null);

    expect(pages).toBe(3);
    expect(seen).toEqual(sellers);
    expect(new Set(seen).size).toBe(seen.length);
    expect(cursors).toEqual([sellers[99], sellers[199], null]);

    // Restarting from a returned cursor reproduces the exact suffix.
    const suffix = await listSellersWithChangedCompletedSales(pool, {
      ...window,
      snapshotChangeSequence: snapshot,
      afterSellerAccountId: sellers[199],
      limit: 100,
    });
    expect(suffix.sellerAccountIds).toEqual(sellers.slice(200));

    // A newly completed row after pass start is excluded from the fixed snapshot.
    await seedCompletedSales(pool, [
      {
        paymentId: "pay_synthetic_new",
        orderId: "ord_synthetic_new",
        sellerAccountId: "acct_synthetic_seller_9998",
        occurredAt: "2026-03-15T00:00:00.000Z",
        changedAt: "2026-03-15T00:00:00.000Z",
      },
    ]);
    const sameSnapshot = await listSellersWithChangedCompletedSales(pool, {
      ...window,
      snapshotChangeSequence: snapshot,
      afterSellerAccountId: sellers[249],
      limit: 100,
    });
    expect(sameSnapshot.sellerAccountIds).toEqual([]);

    // An existing completed row materially changed after pass start is likewise deferred,
    // then included by the next pass.
    await pool.query(
      `UPDATE platform_operations_seller_compliance_sales
       SET change_sequence = nextval('platform_operations_seller_compliance_sales_change_seq'),
           revision = revision + 1
       WHERE order_id = 'ord_synthetic_0'`,
    );
    const mutatedInOldPass = await listSellersWithChangedCompletedSales(pool, {
      ...window,
      snapshotChangeSequence: snapshot,
      limit: 100,
    });
    expect(mutatedInOldPass.sellerAccountIds).not.toContain(sellers[0]);

    const nextSnapshot = await readSellerComplianceSnapshotChangeSequence(pool);
    expect(BigInt(nextSnapshot) > BigInt(snapshot)).toBe(true);
    const nextPass = await listSellersWithChangedCompletedSales(pool, {
      ...window,
      snapshotChangeSequence: nextSnapshot,
      limit: 100,
    });
    expect(nextPass.sellerAccountIds).toContain(sellers[0]);

    // The two enumeration families are not interchangeable: this seller changed inside the
    // window but its sale occurred long before it, so swapping the families fails.
    await seedCompletedSales(pool, [
      {
        paymentId: "pay_synthetic_divergent",
        orderId: "ord_synthetic_divergent",
        sellerAccountId: "acct_synthetic_seller_9999",
        occurredAt: "2024-01-01T00:00:00.000Z",
        changedAt: "2026-03-20T00:00:00.000Z",
      },
    ]);
    const divergentSnapshot = await readSellerComplianceSnapshotChangeSequence(pool);
    const byChange = await listSellersWithChangedCompletedSales(pool, {
      ...window,
      snapshotChangeSequence: divergentSnapshot,
      afterSellerAccountId: "acct_synthetic_seller_9998",
      limit: 100,
    });
    const byOccurrence = await listSellersWithSalesOccurringInWindow(pool, {
      ...window,
      snapshotChangeSequence: divergentSnapshot,
      afterSellerAccountId: "acct_synthetic_seller_9998",
      limit: 100,
    });
    expect(byChange.sellerAccountIds).toContain("acct_synthetic_seller_9999");
    expect(byOccurrence.sellerAccountIds).not.toContain("acct_synthetic_seller_9999");
  });

  it("pages one seller with a stable tuple and rejects a changed snapshot", async () => {
    const total = 201;
    await seedCompletedSales(
      pool,
      Array.from({ length: total }, (_unused, index) => ({
        paymentId: `pay_synthetic_${String(index).padStart(4, "0")}`,
        orderId: `ord_synthetic_${String(index).padStart(4, "0")}`,
        sellerAccountId: SELLER,
        // Equal occurrence instants across a page boundary force the full tuple cursor to
        // do the work; a bare `occurred_at` cursor would loop or skip here.
        occurredAt: index < 150 ? "2026-03-10T00:00:00.000Z" : "2026-03-20T00:00:00.000Z",
      })),
    );

    const window = { fromInclusive: "2026-01-01T00:00:00.000Z", toExclusive: "2026-06-01T00:00:00.000Z" };
    const openingToken = await readSellerCompletedSalesSnapshotToken(pool, { ...window, sellerAccountId: SELLER });
    expect(openingToken.rowCount).toBe(total);

    const collected: string[] = [];
    let cursor: SellerSaleCursor | null = null;
    let pages = 0;
    do {
      const page: Awaited<ReturnType<typeof listSellerCompletedSalesPage>> = await listSellerCompletedSalesPage(pool, {
        ...window,
        sellerAccountId: SELLER,
        cursor,
        limit: 100,
      });
      pages += 1;
      expect(page.sales.length).toBeLessThanOrEqual(100);
      collected.push(...page.sales.map((sale) => sale.orderId));
      cursor = page.nextCursor;
    } while (cursor !== null);

    expect(pages).toBe(3);
    expect(collected).toHaveLength(total);
    expect(new Set(collected).size).toBe(total);
    expect(collected).toEqual([...collected].sort());

    // An intermediate-cursor restart yields the exact suffix.
    const firstPage = await listSellerCompletedSalesPage(pool, {
      ...window,
      sellerAccountId: SELLER,
      limit: 100,
    });
    const suffix = await listSellerCompletedSalesPage(pool, {
      ...window,
      sellerAccountId: SELLER,
      cursor: firstPage.nextCursor,
      limit: 100,
    });
    expect(suffix.sales.map((sale) => sale.orderId)).toEqual(collected.slice(100, 200));

    // A concurrent material change moves the closing token, so the consumer discards the
    // partial evaluation and restarts from null.
    await pool.query(
      `UPDATE platform_operations_seller_compliance_sales
       SET revision = revision + 1,
           change_sequence = nextval('platform_operations_seller_compliance_sales_change_seq')
       WHERE order_id = 'ord_synthetic_0005'`,
    );
    const closingToken = await readSellerCompletedSalesSnapshotToken(pool, { ...window, sellerAccountId: SELLER });
    expect(snapshotTokensMatch(openingToken, closingToken)).toBe(false);
    expect(closingToken.rowCount).toBe(openingToken.rowCount);

    await expect(
      listSellerCompletedSalesPage(pool, { ...window, sellerAccountId: SELLER, limit: 0 }),
    ).rejects.toThrow(/between 1 and 100/);
    await expect(
      listSellerCompletedSalesPage(pool, { ...window, sellerAccountId: SELLER, limit: 101 }),
    ).rejects.toThrow(/between 1 and 100/);
  });
});

/**
 * Bulk seeding for the read-contract tests only. The projection's own writes are exercised
 * through the registered production handlers in the tests above; these rows exist to give
 * the bounded reads enough volume to cross real page boundaries.
 */
async function seedCompletedSales(
  pool: PgTransactionalPool,
  rows: readonly Readonly<{
    paymentId: string;
    orderId: string;
    sellerAccountId: string;
    occurredAt: string;
    changedAt?: string;
  }>[],
): Promise<void> {
  for (const row of rows) {
    await pool.query(
      `INSERT INTO platform_operations_seller_compliance_sales (
         payment_id, order_id, seller_account_id, sale_state, occurred_at, currency_code,
         item_gross_cents, order_total_cents, seller_payout_cents,
         revision, change_sequence, recorded_at, changed_at
       ) VALUES ($1, $2, $3, 'captured', $4, 'usd', 10000, 11300, 9500, 1,
                 nextval('platform_operations_seller_compliance_sales_change_seq'), $5, $5)`,
      [row.paymentId, row.orderId, row.sellerAccountId, row.occurredAt, row.changedAt ?? row.occurredAt],
    );
  }
}
