// Generated by scripts/generate-deployable-runtimes.mjs. Do not edit by hand.

import { collectProjectors } from "@chase-sets/bounded-context-runtime";
import type { PgTransactionalPool } from "@chase-sets/event-core-postgres";
import { module as inventoryModule } from "@chase-sets/inventory";


export type ContextRuntimeServices = Readonly<{
  inventory: ReturnType<typeof inventoryModule.createServices>;
}>;

export type ContextRuntimeHostPorts = Readonly<Record<string, never>>;

export function createContextRuntime(
  pool: PgTransactionalPool,
  hostPorts: ContextRuntimeHostPorts = {} as ContextRuntimeHostPorts,
) {
  const services = {} as Record<string, unknown> as {
  inventory: ReturnType<typeof inventoryModule.createServices>;
  };

  services.inventory = inventoryModule.createServices(pool, undefined);

  const mountedModules = [
    { module: inventoryModule, services: services.inventory },
  ] as const;

  return {
    mountedModules,
    services: services as ContextRuntimeServices,
    projectors: collectProjectors([
    services.inventory,
    ]),
  };
}
