// Generated by scripts/generate-deployable-runtimes.mjs. Do not edit by hand.

import { collectProjectors, resolveModuleProjectionGroups, resolveModuleSubscriptions } from "@chase-sets/bounded-context-runtime";
import type { PgTransactionalPool } from "@chase-sets/event-core-postgres";
import { module as catalogModule } from "@chase-sets/catalog";
import { module as identityModule } from "@chase-sets/identity";
import { module as inventoryModule } from "@chase-sets/inventory";
import { module as orderingModule } from "@chase-sets/ordering";

export type ContextRuntimePools = Readonly<{
  catalog: PgTransactionalPool;
  identity: PgTransactionalPool;
  inventory: PgTransactionalPool;
  ordering: PgTransactionalPool;
}>;

export type ContextRuntimeServices = Readonly<{
  catalog: ReturnType<typeof catalogModule.createServices>;
  identity: ReturnType<typeof identityModule.createServices>;
  inventory: ReturnType<typeof inventoryModule.createServices>;
  ordering: ReturnType<typeof orderingModule.createServices>;
}>;

export type ContextRuntimeHostPorts = Readonly<Record<string, never>>;

export function createContextRuntime(
  pools: ContextRuntimePools,
  hostPorts: ContextRuntimeHostPorts = {} as ContextRuntimeHostPorts,
) {
  const services = {} as Record<string, unknown> as {
  catalog: ReturnType<typeof catalogModule.createServices>;
  identity: ReturnType<typeof identityModule.createServices>;
  inventory: ReturnType<typeof inventoryModule.createServices>;
  ordering: ReturnType<typeof orderingModule.createServices>;
  };

  services.catalog = catalogModule.createServices(pools.catalog, undefined);
  services.identity = identityModule.createServices(pools.identity, undefined);
  services.inventory = inventoryModule.createServices(pools.inventory, undefined);
  services.ordering = orderingModule.createServices(pools.ordering, undefined);

  const mountedContexts = [
    {
      contextName: "catalog",
      mountRole: "active",
      module: catalogModule,
      services: services.catalog,
      pool: pools.catalog,
      projectors: catalogModule.projectors(services.catalog),
    },
    {
      contextName: "identity",
      mountRole: "active",
      module: identityModule,
      services: services.identity,
      pool: pools.identity,
      projectors: identityModule.projectors(services.identity),
    },
    {
      contextName: "inventory",
      mountRole: "active",
      module: inventoryModule,
      services: services.inventory,
      pool: pools.inventory,
      projectors: inventoryModule.projectors(services.inventory),
    },
    {
      contextName: "ordering",
      mountRole: "source-only",
      module: orderingModule,
      services: services.ordering,
      pool: pools.ordering,
      projectors: [],
    },
  ] as const;

  const mountedModules = [
    { module: catalogModule, services: services.catalog },
    { module: identityModule, services: services.identity },
    { module: inventoryModule, services: services.inventory },
    { module: orderingModule, services: services.ordering },
  ] as const;

  const subscriptionRunners = resolveModuleSubscriptions(mountedContexts);
  const projectionGroups = resolveModuleProjectionGroups(
    mountedContexts,
    subscriptionRunners,
  );

  return {
    mountedContexts,
    mountedModules,
    services: services as ContextRuntimeServices,
    projectors: collectProjectors([
    services.catalog,
    services.identity,
    services.inventory,
    ]),
    projectionGroups,
    subscriptionRunners,
  };
}
