// Generated by scripts/generate-deployable-api-mounts.mjs. Do not edit by hand.

import { resolveModuleApiMounts, type ResolvedApiMount } from "@chase-sets/bounded-context-runtime";
import { module as InventoryModule } from "@chase-sets/inventory";

export function createContextApiMounts(
  services: ReturnType<typeof InventoryModule.createServices>,
): readonly ResolvedApiMount[] {
  return resolveModuleApiMounts(InventoryModule, services);
}
