// Generated by scripts/generate-deployable-api-mounts.mjs. Do not edit by hand.

import type { ResolvedApiMount } from "@chase-sets/bounded-context-runtime";
import { resolveApiMounts as resolveInventoryApiMounts } from "@chase-sets/inventory";

export function createContextApiMounts(
  services: Parameters<typeof resolveInventoryApiMounts>[0],
): readonly ResolvedApiMount[] {
  return resolveInventoryApiMounts(services);
}
