import { describe, expect, it } from "vitest";
import { buildReleaseHealthRecord, parseReleaseHealthArgs } from "./release-health.mjs";

describe("release health summary", () => {
  it("builds a production release health record", () => {
    const result = buildReleaseHealthRecord({
      releaseCommit: "a".repeat(40),
      workflowRunId: "123456",
      workflowRunAttempt: "2",
      checkedAt: "2026-05-31T12:00:00.000Z",
      releaseMode: "normal",
      prOpenedAt: "2026-05-31T10:00:00.000Z",
      prReadyForReviewAt: "2026-05-31T10:15:00.000Z",
      prApprovedAt: "2026-05-31T11:45:00.000Z",
      queueBatchSize: 1,
      queueQueuedAt: "2026-05-31T11:50:00.000Z",
      queueMergeGroupStartedAt: "2026-05-31T11:52:00.000Z",
      queueMergedAt: "2026-05-31T11:55:00.000Z",
      queueDequeuedAt: "",
      queueFailureReason: "",
      mergeSha: "e".repeat(40),
      releaseCommitCommittedAt: "2026-05-31T11:54:30.000Z",
      releaseCategory: "ordinary-deploy",
      exposurePostureCategories: ["public-marketplace-launch"],
      deploymentRequired: true,
      stagingResult: "success",
      stagingStartedAt: "2026-05-31T11:56:00.000Z",
      stagingCompletedAt: "2026-05-31T12:05:00.000Z",
      canaryResult: "skipped",
      canaryStartedAt: "",
      canaryCompletedAt: "",
      canarySkippedReason: "stage-1-canary-not-required",
      canaryCohortSubjectType: "operator",
      canaryCohortSize: 1,
      canaryPromotionDecision: "promote",
      productionResult: "success",
      productionStartedAt: "2026-05-31T12:06:00.000Z",
      productionCompletedAt: "2026-05-31T12:12:00.000Z",
      mainToProductionDriftCommits: 1,
      mainToProductionDriftSeconds: 1080,
      releaseLocked: false,
      releaseLockReference: "",
      emergencyReference: "",
      recoveryMode: "none",
      recoveryReference: "",
      recoveryTargetCommit: "",
      productionRecoveryMode: "precreated-fork",
      productionRecoveryReason: "Money movement changed.",
      rollbackReadinessResult: "skipped",
      productionRestorePointResult: "success",
      productionRestorePointType: "digitalocean-database-fork",
      productionRestorePointClusterId: "db-fork-1",
      productionRestorePointName: "cs-prod-rp-aaaaaaaa-123456-2",
      productionRestorePointStatus: "online",
      productionRestorePointCreatedAt: "2026-05-31T12:05:45.000Z",
      productionRestorePointBypassed: false,
      productionRestorePointRemediation: "Run restore-point cleanup before retrying production deploy.",
      productionRestorePointPreMigrateStateKey: "production-marker:ffffffffffffffffffffffffffffffffffffffff",
      productionRestorePointPreMigrateStateFingerprint: "0123456789abcdef",
      productionRestorePointReused: true,
      productionRestorePointReusedClusterId: "db-fork-1",
      ciRetryCount: 1,
      ciFlakyFailureCount: 1,
      ciTopFlakyJobs: [{ name: "Platform PR", retryCount: 1, flakyFailureCount: 1 }],
    });

    expect(result.passesReleaseHealthGate).toBe(true);
    expect(result.record).toMatchObject({
      schemaVersion: "release-health/v1",
      releaseCommit: "a".repeat(40),
      workflowRunId: "123456",
      releaseMode: "normal",
      pullRequest: {
        openedAt: "2026-05-31T10:00:00.000Z",
        readyForReviewAt: "2026-05-31T10:15:00.000Z",
        approvedAt: "2026-05-31T11:45:00.000Z",
      },
      mainToProductionDrift: { commits: 1, seconds: 1080 },
      queue: {
        batchSize: 1,
        queuedAt: "2026-05-31T11:50:00.000Z",
        mergeGroupStartedAt: "2026-05-31T11:52:00.000Z",
        mergedAt: "2026-05-31T11:55:00.000Z",
        mergeSha: "e".repeat(40),
        releaseCommitCommittedAt: "2026-05-31T11:54:30.000Z",
      },
      releaseCategory: { primary: "ordinary-deploy", exposurePostureCategories: ["public-marketplace-launch"] },
      staging: {
        startedAt: "2026-05-31T11:56:00.000Z",
        completedAt: "2026-05-31T12:05:00.000Z",
        result: "success",
        applied: true,
      },
      canary: {
        startedAt: null,
        completedAt: null,
        result: "skipped",
        skippedReason: "stage-1-canary-not-required",
        cohort: { subjectType: "operator", size: 1 },
        promotionDecision: "promote",
      },
      production: {
        startedAt: "2026-05-31T12:06:00.000Z",
        completedAt: "2026-05-31T12:12:00.000Z",
        result: "success",
      },
      releaseLock: { locked: false, bypassed: false, reference: null },
      recovery: {
        mode: "none",
        reference: null,
        targetCommit: null,
        productionRecoveryMode: "precreated-fork",
        productionRecoveryReason: "Money movement changed.",
        rollbackReadinessResult: "skipped",
        productionRestorePoint: {
          result: "success",
          type: "digitalocean-database-fork",
          clusterId: "db-fork-1",
          name: "cs-prod-rp-aaaaaaaa-123456-2",
          status: "online",
          createdAt: "2026-05-31T12:05:45.000Z",
          bypassed: false,
          remediation: "Run restore-point cleanup before retrying production deploy.",
          preMigrateStateKey: "production-marker:ffffffffffffffffffffffffffffffffffffffff",
          preMigrateStateFingerprint: "0123456789abcdef",
          reused: true,
          reusedClusterId: "db-fork-1",
        },
      },
      ci: {
        retryCount: 1,
        flakyFailureCount: 1,
        topFlakyJobs: [{ name: "Platform PR", retryCount: 1, flakyFailureCount: 1 }],
      },
      gateSummary: {
        blockingFailures: 0,
        advisoryWarnings: 0,
        deferredProof: 1,
      },
    });
    expect(result.record.gates).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: "staging-deploy-and-smoke",
          severity: "blocking",
          status: "pass",
        }),
        expect.objectContaining({
          id: "production-recovery-mode",
          severity: "blocking",
          status: "pass",
        }),
        expect.objectContaining({
          id: "production-restore-point",
          severity: "blocking",
          status: "pass",
        }),
        expect.objectContaining({
          id: "exposure-posture-proof",
          severity: "deferred-proof",
          status: "pass",
        }),
      ]),
    );
  });

  it("records emergency lock bypass evidence", () => {
    const result = buildReleaseHealthRecord({
      releaseCommit: "b".repeat(40),
      workflowRunId: "789",
      workflowRunAttempt: "1",
      checkedAt: "2026-05-31T12:00:00.000Z",
      releaseMode: "emergency",
      prOpenedAt: null,
      prReadyForReviewAt: null,
      prApprovedAt: null,
      queueBatchSize: 1,
      queueQueuedAt: null,
      queueMergeGroupStartedAt: null,
      queueMergedAt: null,
      queueDequeuedAt: null,
      queueFailureReason: null,
      mergeSha: null,
      releaseCommitCommittedAt: null,
      releaseCategory: "emergency-recovery",
      exposurePostureCategories: [],
      deploymentRequired: true,
      stagingResult: "success",
      stagingStartedAt: null,
      stagingCompletedAt: null,
      canaryResult: "skipped",
      canaryStartedAt: null,
      canaryCompletedAt: null,
      canarySkippedReason: null,
      canaryCohortSubjectType: null,
      canaryCohortSize: null,
      canaryPromotionDecision: null,
      productionResult: "failure",
      productionStartedAt: null,
      productionCompletedAt: null,
      mainToProductionDriftCommits: 0,
      mainToProductionDriftSeconds: 0,
      releaseLocked: true,
      releaseLockReference: "INC-2026-05-31-001",
      emergencyReference: "FIX-FORWARD-PR-123",
      recoveryMode: "fix-forward",
      recoveryReference: "FIX-FORWARD-PR-123",
      recoveryTargetCommit: "b".repeat(40),
      rollbackReadinessResult: "success",
      productionRestorePointResult: "bypassed",
      productionRestorePointBypassed: true,
    });

    expect(result.record.releaseLock).toMatchObject({
      locked: true,
      bypassed: true,
      reference: "INC-2026-05-31-001",
      emergencyReference: "FIX-FORWARD-PR-123",
    });
    expect(result.record.production.result).toBe("failure");
    expect(result.record.recovery).toMatchObject({
      mode: "fix-forward",
      reference: "FIX-FORWARD-PR-123",
      rollbackReadinessResult: "success",
      productionRestorePoint: {
        result: "bypassed",
        bypassed: true,
      },
    });
  });

  it("records advisory post-deploy readiness warnings without failing the release-health artifact", () => {
    const result = buildReleaseHealthRecord({
      releaseCommit: "a".repeat(40),
      workflowRunId: "123",
      workflowRunAttempt: "1",
      checkedAt: "2026-05-31T12:00:00.000Z",
      deploymentRequired: true,
      stagingResult: "success",
      canaryResult: "success",
      canaryPromotionDecision: "promote",
      productionReadinessGateOutcome: "budget-expired",
      productionResult: "success",
      mainToProductionDriftCommits: 0,
      mainToProductionDriftSeconds: 0,
      releaseLocked: false,
      recoveryMode: "none",
      productionRecoveryMode: "pitr",
      rollbackReadinessResult: "skipped",
      productionRestorePointResult: "skipped",
    });

    expect(result.passesReleaseHealthGate).toBe(true);
    expect(result.record.gateSummary).toMatchObject({
      blockingFailures: 0,
      advisoryWarnings: 1,
    });
    expect(result.record.gates).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: "post-deploy-projection-readiness",
          severity: "advisory",
          status: "warn",
          reason: "readiness outcome: budget-expired",
        }),
      ]),
    );
  });

  it("marks missing precreated restore points as blocking for rollback-unsafe releases", () => {
    const result = buildReleaseHealthRecord({
      releaseCommit: "a".repeat(40),
      workflowRunId: "123",
      workflowRunAttempt: "1",
      checkedAt: "2026-05-31T12:00:00.000Z",
      deploymentRequired: true,
      stagingResult: "success",
      canaryResult: "success",
      canaryPromotionDecision: "promote",
      productionResult: "failure",
      mainToProductionDriftCommits: 0,
      mainToProductionDriftSeconds: 0,
      releaseLocked: false,
      recoveryMode: "none",
      productionRecoveryMode: "precreated-fork",
      productionRecoveryReason: "Money movement provider code changed.",
      rollbackReadinessResult: "skipped",
      productionRestorePointResult: "failure",
    });

    expect(result.record.gateSummary.blockingFailures).toBeGreaterThanOrEqual(2);
    expect(result.record.gates).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: "production-restore-point",
          severity: "blocking",
          status: "fail",
          reason: "restore point result: failure",
        }),
        expect.objectContaining({
          id: "production-smoke-and-marker",
          severity: "blocking",
          status: "fail",
        }),
      ]),
    );
  });

  it("records a staging release attempt before production starts", () => {
    const result = buildReleaseHealthRecord({
      releaseCommit: "b".repeat(40),
      workflowRunId: "789",
      workflowRunAttempt: "1",
      checkedAt: "2026-05-31T12:00:00.000Z",
      releaseMode: "normal",
      queueBatchSize: 1,
      deploymentRequired: true,
      stagingResult: "skipped",
      stagingApplied: false,
      canaryResult: "skipped",
      canarySkippedReason: "staging-not-deployed",
      productionResult: "skipped",
      mainToProductionDriftCommits: 2,
      mainToProductionDriftSeconds: 900,
      releaseLocked: false,
      recoveryMode: "none",
      rollbackReadinessResult: "unknown",
      releaseAttemptResult: "skipped",
      releaseAttemptPhase: "staging",
      releaseAttemptReason: "staging-not-deployed",
      releaseAttemptWorkflowUrl: "https://github.com/chase-sets/chase-sets/actions/runs/123/attempts/1",
    });

    expect(result.passesReleaseHealthGate).toBe(true);
    expect(result.record).toMatchObject({
      staging: { result: "skipped", applied: false },
      canary: { result: "skipped", skippedReason: "staging-not-deployed" },
      production: { result: "skipped" },
      attempt: {
        result: "skipped",
        phase: "staging",
        reason: "staging-not-deployed",
        workflowUrl: "https://github.com/chase-sets/chase-sets/actions/runs/123/attempts/1",
      },
    });
  });

  it("records an intentional production supersede with the newer main commit", () => {
    const result = buildReleaseHealthRecord({
      releaseCommit: "a".repeat(40),
      workflowRunId: "789",
      workflowRunAttempt: "1",
      checkedAt: "2026-05-31T12:00:00.000Z",
      releaseMode: "normal",
      queueBatchSize: 1,
      deploymentRequired: true,
      stagingResult: "success",
      canaryResult: "skipped",
      canarySkippedReason: "production-superseded-by-newer-main",
      productionResult: "skipped",
      mainToProductionDriftCommits: 2,
      mainToProductionDriftSeconds: 900,
      releaseLocked: false,
      recoveryMode: "none",
      rollbackReadinessResult: "unknown",
      releaseAttemptResult: "skipped",
      releaseAttemptPhase: "production",
      releaseAttemptReason: "production-superseded-by-newer-main",
      releaseAttemptSupersededByCommit: "b".repeat(40),
      releaseAttemptWorkflowUrl: "https://github.com/chase-sets/chase-sets/actions/runs/123/attempts/1",
    });

    expect(result.passesReleaseHealthGate).toBe(true);
    expect(result.record).toMatchObject({
      staging: { result: "success" },
      canary: { result: "skipped", skippedReason: "production-superseded-by-newer-main" },
      production: { result: "skipped" },
      attempt: {
        result: "skipped",
        phase: "production",
        reason: "production-superseded-by-newer-main",
        supersededByCommit: "b".repeat(40),
        workflowUrl: "https://github.com/chase-sets/chase-sets/actions/runs/123/attempts/1",
      },
    });
  });

  it("fails validation when the release commit is not concrete", () => {
    const result = buildReleaseHealthRecord({
      releaseCommit: "main",
      workflowRunId: "123",
      workflowRunAttempt: "1",
      checkedAt: "2026-05-31T12:00:00.000Z",
      releaseMode: "normal",
      prOpenedAt: null,
      prReadyForReviewAt: null,
      prApprovedAt: null,
      queueBatchSize: 1,
      queueQueuedAt: null,
      queueMergeGroupStartedAt: null,
      queueMergedAt: null,
      queueDequeuedAt: null,
      queueFailureReason: null,
      mergeSha: null,
      releaseCommitCommittedAt: null,
      releaseCategory: "ordinary-deploy",
      exposurePostureCategories: [],
      deploymentRequired: true,
      stagingResult: "success",
      stagingStartedAt: null,
      stagingCompletedAt: null,
      canaryResult: "skipped",
      canaryStartedAt: null,
      canaryCompletedAt: null,
      canarySkippedReason: null,
      canaryCohortSubjectType: null,
      canaryCohortSize: null,
      canaryPromotionDecision: null,
      productionResult: "success",
      productionStartedAt: null,
      productionCompletedAt: null,
      mainToProductionDriftCommits: 0,
      mainToProductionDriftSeconds: 0,
      releaseLocked: false,
      releaseLockReference: "",
      emergencyReference: "",
      recoveryMode: "none",
      recoveryReference: "",
      recoveryTargetCommit: "",
      rollbackReadinessResult: "unknown",
    });

    expect(result.passesReleaseHealthGate).toBe(false);
    expect(result.errors).toContain("releaseCommit must be a 40-character Git commit SHA.");
  });

  it("keeps appended fields defaulted for older direct callers", () => {
    const result = buildReleaseHealthRecord({
      releaseCommit: "f".repeat(40),
      workflowRunId: "123",
      workflowRunAttempt: "1",
      checkedAt: "2026-05-31T12:00:00.000Z",
      deploymentRequired: true,
      stagingResult: "success",
      productionResult: "success",
      mainToProductionDriftCommits: 0,
      mainToProductionDriftSeconds: 0,
      releaseLocked: false,
    });

    expect(result.passesReleaseHealthGate).toBe(true);
    expect(result.record).toMatchObject({
      releaseMode: "normal",
      queue: { batchSize: 1 },
      releaseCategory: { primary: "ordinary-deploy", exposurePostureCategories: [] },
      canary: { cohort: { size: null } },
      recovery: { mode: "none", productionRestorePoint: { result: "unknown", bypassed: false } },
    });
  });

  it("parses GitHub workflow environment values", () => {
    const options = parseReleaseHealthArgs([], {
      RELEASE_HEALTH_OUT: "artifacts/release-health/release.json",
      RELEASE_COMMIT: "c".repeat(40),
      GITHUB_RUN_ID: "456",
      GITHUB_RUN_ATTEMPT: "3",
      RELEASE_MODE: "emergency",
      PR_OPENED_AT: "2026-05-31T09:00:00.000Z",
      PR_READY_FOR_REVIEW_AT: "2026-05-31T09:05:00.000Z",
      PR_APPROVED_AT: "2026-05-31T10:00:00.000Z",
      QUEUE_BATCH_SIZE: "2",
      QUEUE_QUEUED_AT: "2026-05-31T11:00:00.000Z",
      QUEUE_MERGE_GROUP_STARTED_AT: "2026-05-31T11:05:00.000Z",
      QUEUE_MERGED_AT: "2026-05-31T11:10:00.000Z",
      QUEUE_DEQUEUED_AT: "2026-05-31T11:09:00.000Z",
      QUEUE_FAILURE_REASON: "required-check-failed",
      MERGE_SHA: "f".repeat(40),
      RELEASE_COMMIT_COMMITTED_AT: "2026-05-31T11:09:30.000Z",
      RELEASE_CATEGORY: "provider-exposure",
      EXPOSURE_POSTURE_CATEGORIES: "live-money-provider,tax-posture",
      DEPLOYMENT_REQUIRED: "true",
      STAGING_RESULT: "success",
      STAGING_APPLIED: "false",
      STAGING_STARTED_AT: "2026-05-31T11:11:00.000Z",
      STAGING_COMPLETED_AT: "2026-05-31T11:20:00.000Z",
      CANARY_RESULT: "skipped",
      CANARY_SKIPPED_REASON: "no-canary-required",
      CANARY_COHORT_SUBJECT_TYPE: "operator",
      CANARY_COHORT_SIZE: "3",
      CANARY_PROMOTION_DECISION: "hold",
      PRODUCTION_READINESS_GATE_OUTCOME: "budget-expired",
      PRODUCTION_RESULT: "cancelled",
      PRODUCTION_STARTED_AT: "2026-05-31T11:21:00.000Z",
      PRODUCTION_COMPLETED_AT: "2026-05-31T11:24:00.000Z",
      RELEASE_ATTEMPT_RESULT: "cancelled",
      RELEASE_ATTEMPT_PHASE: "production",
      RELEASE_ATTEMPT_REASON: "production-release",
      RELEASE_ATTEMPT_SUPERSEDED_BY_COMMIT: "a".repeat(40),
      RELEASE_ATTEMPT_WORKFLOW_URL: "https://github.com/chase-sets/chase-sets/actions/runs/456/attempts/3",
      CI_RETRY_COUNT: "2",
      CI_FLAKY_FAILURE_COUNT: "1",
      CI_TOP_FLAKY_JOBS: '[{"name":"Platform PR","retryCount":2,"flakyFailureCount":1}]',
      MAIN_TO_PRODUCTION_DRIFT_COMMITS: "2",
      MAIN_TO_PRODUCTION_DRIFT_SECONDS: "900",
      PRODUCTION_RELEASE_LOCKED: "true",
      PRODUCTION_RELEASE_LOCK_REFERENCE: "INC-1",
      EMERGENCY_RELEASE_REFERENCE: "REVERT-1",
      RECOVERY_MODE: "rollback",
      RECOVERY_REFERENCE: "ROLLBACK-1",
      RECOVERY_TARGET_COMMIT: "c".repeat(40),
      ROLLBACK_READINESS_RESULT: "success",
      PRODUCTION_RESTORE_POINT_RESULT: "success",
      PRODUCTION_RESTORE_POINT_TYPE: "digitalocean-database-fork",
      PRODUCTION_RESTORE_POINT_CLUSTER_ID: "db-fork-2",
      PRODUCTION_RESTORE_POINT_NAME: "cs-prod-rp-cccccccc-456-3",
      PRODUCTION_RESTORE_POINT_STATUS: "online",
      PRODUCTION_RESTORE_POINT_CREATED_AT: "2026-05-31T11:20:30.000Z",
      PRODUCTION_RESTORE_POINT_BYPASSED: "false",
      PRODUCTION_RESTORE_POINT_REMEDIATION: "Run restore-point cleanup before retrying production deploy.",
      PRODUCTION_RESTORE_POINT_PRE_MIGRATE_STATE_KEY: "production-marker:ffffffffffffffffffffffffffffffffffffffff",
      PRODUCTION_RESTORE_POINT_PRE_MIGRATE_STATE_FINGERPRINT: "0123456789abcdef",
      PRODUCTION_RESTORE_POINT_REUSED: "true",
      PRODUCTION_RESTORE_POINT_REUSED_CLUSTER_ID: "db-fork-2",
    });

    expect(options).toMatchObject({
      outPath: "artifacts/release-health/release.json",
      releaseCommit: "c".repeat(40),
      workflowRunId: "456",
      workflowRunAttempt: "3",
      releaseMode: "emergency",
      prOpenedAt: "2026-05-31T09:00:00.000Z",
      prReadyForReviewAt: "2026-05-31T09:05:00.000Z",
      prApprovedAt: "2026-05-31T10:00:00.000Z",
      queueBatchSize: 2,
      queueQueuedAt: "2026-05-31T11:00:00.000Z",
      queueMergeGroupStartedAt: "2026-05-31T11:05:00.000Z",
      queueMergedAt: "2026-05-31T11:10:00.000Z",
      queueDequeuedAt: "2026-05-31T11:09:00.000Z",
      queueFailureReason: "required-check-failed",
      mergeSha: "f".repeat(40),
      releaseCommitCommittedAt: "2026-05-31T11:09:30.000Z",
      releaseCategory: "provider-exposure",
      exposurePostureCategories: ["live-money-provider", "tax-posture"],
      deploymentRequired: true,
      stagingStartedAt: "2026-05-31T11:11:00.000Z",
      stagingCompletedAt: "2026-05-31T11:20:00.000Z",
      productionStartedAt: "2026-05-31T11:21:00.000Z",
      productionCompletedAt: "2026-05-31T11:24:00.000Z",
      releaseAttemptResult: "cancelled",
      releaseAttemptPhase: "production",
      releaseAttemptReason: "production-release",
      releaseAttemptSupersededByCommit: "a".repeat(40),
      releaseAttemptWorkflowUrl: "https://github.com/chase-sets/chase-sets/actions/runs/456/attempts/3",
      ciRetryCount: 2,
      ciFlakyFailureCount: 1,
      ciTopFlakyJobs: [{ name: "Platform PR", retryCount: 2, flakyFailureCount: 1 }],
      canarySkippedReason: "no-canary-required",
      canaryCohortSubjectType: "operator",
      canaryCohortSize: 3,
      canaryPromotionDecision: "hold",
      productionReadinessGateOutcome: "budget-expired",
      mainToProductionDriftCommits: 2,
      mainToProductionDriftSeconds: 900,
      releaseLocked: true,
      releaseLockReference: "INC-1",
      emergencyReference: "REVERT-1",
      recoveryMode: "rollback",
      recoveryReference: "ROLLBACK-1",
      recoveryTargetCommit: "c".repeat(40),
      rollbackReadinessResult: "success",
      productionRestorePointResult: "success",
      productionRestorePointType: "digitalocean-database-fork",
      productionRestorePointClusterId: "db-fork-2",
      productionRestorePointName: "cs-prod-rp-cccccccc-456-3",
      productionRestorePointStatus: "online",
      productionRestorePointCreatedAt: "2026-05-31T11:20:30.000Z",
      productionRestorePointBypassed: false,
      productionRestorePointRemediation: "Run restore-point cleanup before retrying production deploy.",
      productionRestorePointPreMigrateStateKey: "production-marker:ffffffffffffffffffffffffffffffffffffffff",
      productionRestorePointPreMigrateStateFingerprint: "0123456789abcdef",
      productionRestorePointReused: true,
      productionRestorePointReusedClusterId: "db-fork-2",
    });
  });

  it("validates optional timing fields", () => {
    const result = buildReleaseHealthRecord({
      releaseCommit: "d".repeat(40),
      workflowRunId: "123",
      workflowRunAttempt: "1",
      checkedAt: "2026-05-31T12:00:00.000Z",
      releaseMode: "normal",
      prOpenedAt: null,
      prReadyForReviewAt: null,
      prApprovedAt: null,
      queueBatchSize: 1,
      queueQueuedAt: "not-a-date",
      queueMergeGroupStartedAt: null,
      queueMergedAt: null,
      queueDequeuedAt: null,
      queueFailureReason: null,
      mergeSha: null,
      releaseCommitCommittedAt: null,
      releaseCategory: "ordinary-deploy",
      exposurePostureCategories: [],
      deploymentRequired: true,
      stagingResult: "success",
      stagingStartedAt: null,
      stagingCompletedAt: null,
      canaryResult: "skipped",
      canaryStartedAt: null,
      canaryCompletedAt: null,
      canarySkippedReason: null,
      canaryCohortSubjectType: null,
      canaryCohortSize: null,
      canaryPromotionDecision: null,
      productionResult: "success",
      productionStartedAt: null,
      productionCompletedAt: null,
      mainToProductionDriftCommits: 0,
      mainToProductionDriftSeconds: 0,
      releaseLocked: false,
      releaseLockReference: "",
      emergencyReference: "",
      recoveryMode: "none",
      recoveryReference: "",
      recoveryTargetCommit: "",
      rollbackReadinessResult: "unknown",
    });

    expect(result.passesReleaseHealthGate).toBe(false);
    expect(result.errors).toContain("queueQueuedAt must be an ISO timestamp when provided.");
  });
});
