import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it } from "vitest";
import {
  buildDigestWindows,
  buildFlakeDigest,
  CI_FLAKE_DIGEST_DISPOSITION_VERSION,
  CI_FLAKE_DIGEST_MARKER_VERSION,
  collectReleaseHealthFlakeDigest,
  parseReleaseHealthFlakeDigestArgs,
  publishReleaseHealthFlakeDigest,
  summarizeDeliverySignatureFlakes,
  summarizeWorkflowRuns,
  findVitestTransitions,
  readVitestArchive,
  writeReleaseHealthFlakeDigest,
} from "./release-health-flake-digest.mjs";
import { renderCircuitMarker } from "./release-health-merge-group-failure-signatures.mjs";

const REPOSITORY = "chase-sets/chase-sets";
const CHECKED_AT = "2026-07-08T00:00:00.000Z";
const HEAD_SHA = "a".repeat(40);
const LEGACY_BODY = [
  "## CI flake threshold breach",
  "",
  "",
  "",
  "## Follow-up policy",
  "",
  "- Identify whether the top breached job should be fixed immediately or quarantined out of the blocking lane.",
  "- Link the fixing PR or the quarantine decision back to this issue.",
  "- Close only after a later digest shows the breached job below threshold or the exception is explicitly accepted.",
  "",
  "Generated by `.github/workflows/platform-ci-flake-digest.yml` from GitHub Actions retry telemetry.",
  "",
  "Part of #4024 and epic #4016.",
  "",
].join("\n");
const LEGACY = [
  [5815, "I_kwDORKgVcc8AAAABJeck5g", "CI flake digest breach: 2026-07-13 to 2026-07-20"],
  [6215, "I_kwDORKgVcc8AAAABKXIaoA", "CI flake digest breach: 2026-07-20 to 2026-07-27"],
  [6504, "I_kwDORKgVcc8AAAABLSRIeQ", "CI flake digest breach: 2026-07-27 to 2026-08-03"],
  [6715, "I_kwDORKgVcc8AAAABMLGzwQ", "CI flake digest breach: 2026-08-03 to 2026-08-10"],
  [7442, "I_kwDORKgVcc8AAAABOB_AcQ", "CI flake digest breach: 2026-08-17 to 2026-08-24"],
];

describe("release health flake digest", () => {
  it("ingests Actions-shaped Vitest archives through writer and canonical publication at the unchanged threshold", async () => {
    const dir = await mkdtemp(join(tmpdir(), "vitest-digest-synthetic-"));
    try {
      const paths = artifactPaths(dir);
      const digest = await writeReleaseHealthFlakeDigest({ ...collectorOptions(vitestCollectorFetch()), ...paths });
      expect(digest.collection.status, JSON.stringify(digest.collection)).toBe("complete");
      expect(digest.retryCount).toBe(0);
      expect(digest.flakyFailureCount).toBe(1);
      expect(digest.vitestCandidateCount).toBe(1);
      expect(digest.classification).toBe("breaching");
      expect(digest.issueBody).toContain("suite synthetic test");
      expect(digest.collection.sources["vitest-current"].producers).toHaveLength(2);
      const github = issueAuthority();
      const result = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths),
        fetchImpl: github.fetchImpl,
      });
      expect(result.status).toBe("breaching");
      expect(result.mutations[0].issueNumber).toBe(7442);
      const missingSource = structuredClone(digest);
      delete missingSource.collection.sources["vitest-current"];
      await writeFrozenArtifact(dir, missingSource);
      expect(
        (await publishReleaseHealthFlakeDigest({ ...publicationOptions(paths), fetchImpl: github.fetchImpl })).status,
      ).toBe("unknown");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("keeps complete no-transition and changed identity/SHA/order corpora clear", async () => {
    for (const scenario of [
      { firstState: "passed" },
      { secondState: "failed" },
      { firstState: "skipped" },
      { firstState: "todo" },
      { firstState: "pending" },
      { firstState: "disabled" },
      { changedHead: true },
      { changedTestedSha: true },
      { changedName: true },
      { reverse: true },
    ]) {
      const digest = await collectReleaseHealthFlakeDigest(collectorOptions(vitestCollectorFetch(scenario)));
      expect(digest.collection.status, JSON.stringify(scenario)).toBe("complete");
      expect(digest.vitestCandidateCount, JSON.stringify(scenario)).toBe(0);
      expect(digest.classification).toBe("clear");
    }
  });

  it("makes missing, expired, malformed, duplicated and started-but-unreported eligible evidence unknown, not clear", async () => {
    for (const scenario of [
      { missingArtifact: true },
      { expired: true },
      { malformed: true },
      { unknownTask: true },
      { duplicateArtifact: true },
      { duplicateAttempt: true },
      { missingPayload: true },
      { incompletePage: true },
    ]) {
      const digest = await collectReleaseHealthFlakeDigest(collectorOptions(vitestCollectorFetch(scenario)));
      expect(digest.collection.status, JSON.stringify(scenario)).toBe("unknown");
      expect(digest.classification).toBe("unknown");
    }
  });

  it("treats pre-rollout, cancelled and skipped producers as neutral, retaining executed failed siblings", async () => {
    for (const scenario of [{ preRollout: true }, { skipped: true }, { cancelled: true }]) {
      const digest = await collectReleaseHealthFlakeDigest(collectorOptions(vitestCollectorFetch(scenario)));
      expect(digest.collection.status).toBe("complete");
      expect(digest.vitestCandidateCount).toBe(0);
    }
    const digest = await collectReleaseHealthFlakeDigest(
      collectorOptions(vitestCollectorFetch({ unstartedSibling: true })),
    );
    expect(digest.collection.status).toBe("complete");
    expect(digest.vitestCandidateCount).toBe(1);
  });

  it("keeps retained duplicate or unnamed observations unknown without inferring by order, state or duration", async () => {
    for (const scenario of [
      { duplicateNames: true },
      { duplicateNames: true, reverseDuplicates: true },
      { duplicateNames: true, secondState: "failed" },
      { duplicateNames: true, firstState: "skipped" },
      { duplicateInvocation: true },
      { emptyName: true },
      { emptyName: true, firstState: "passed" },
    ]) {
      const dir = await mkdtemp(join(tmpdir(), "vitest-ambiguous-synthetic-"));
      try {
        const paths = artifactPaths(dir);
        const digest = await writeReleaseHealthFlakeDigest({
          ...collectorOptions(vitestCollectorFetch(scenario)),
          ...paths,
        });
        expect(digest.collection.status, JSON.stringify(scenario)).toBe("unknown");
        expect(digest.classification).toBe("unknown");
        expect(digest.vitestCandidateCount).toBe(0);
        expect(digest.collection.sources["vitest-current"].reasons.join(" ")).toMatch(
          /identity (ambiguous|unresolved)/,
        );
        const github = issueAuthority();
        const result = await publishReleaseHealthFlakeDigest({
          ...publicationOptions(paths),
          fetchImpl: github.fetchImpl,
        });
        expect(result.status).toBe("unknown");
        expect(github.calls.filter((call) => call.method !== "GET")).toHaveLength(0);
      } finally {
        await rm(dir, { recursive: true, force: true });
      }
    }
  });

  it("reconciles second-page producer/artifact authority and counts an attempt only once", async () => {
    const digest = await collectReleaseHealthFlakeDigest(collectorOptions(vitestCollectorFetch({ secondPage: true })));
    expect(digest.collection.status, JSON.stringify(digest.collection)).toBe("complete");
    expect(digest.vitestCandidateCount).toBe(1);
    const repeated = await collectReleaseHealthFlakeDigest(
      collectorOptions(vitestCollectorFetch({ sameRunRetry: true })),
    );
    expect(repeated.collection.status, JSON.stringify(repeated.collection)).toBe("complete");
    expect(repeated.vitestCandidateCount).toBe(1);
    expect(repeated.flakyFailureCount).toBe(1);
    expect(repeated.vitestCandidates[0].additionalFlakyFailureCount).toBe(0);
  });

  it("selects only the exact canonical ZIP entry and separates archive size from payload size", () => {
    const payload = Buffer.from(JSON.stringify(syntheticVitestPayload(101, 1)));
    expect(
      readVitestArchive(
        storedZip([
          ["diagnostics.json", Buffer.alloc(3 * 1024 * 1024)],
          ["workspace-test-results.json", payload],
        ]),
      ),
    ).toEqual(payload);
    expect(() => readVitestArchive(storedZip([["diagnostics.json", payload]]))).toThrow(/missing/);
    expect(() => readVitestArchive(storedZip([["nested/workspace-test-results.json", payload]]))).toThrow(/missing/);
    expect(() =>
      readVitestArchive(
        storedZip([
          ["workspace-test-results.json", payload],
          ["workspace-test-results.json", payload],
        ]),
      ),
    ).toThrow(/duplicated/);
    expect(() =>
      readVitestArchive(storedZip([["workspace-test-results.json", Buffer.alloc(32 * 1024 * 1024 + 1)]])),
    ).toThrow(/bound/);
  });

  it("rejects ambiguous execution identities before they can manufacture transitions", () => {
    const observation = {
      job: "unit-tests",
      workspace: "@chase-sets/synthetic",
      script: "test",
      file: "test.ts",
      fullName: "test",
      headSha: HEAD_SHA,
      testedSha: HEAD_SHA,
      runId: "1",
      runAttempt: 1,
      state: "failed",
      startedAt: "2026-07-06T00:00:00Z",
      completedAt: "2026-07-06T00:01:00Z",
    };
    expect(() => findVitestTransitions([observation, observation])).toThrow(/ambiguous/);
    expect(() => findVitestTransitions([{ ...observation, fullName: "" }])).toThrow(/unresolved/);
  });
  it("traces the scheduled writer, exact artifact payloads, and direct canonical publisher", async () => {
    const workflow = await readFile(
      new URL("../.github/workflows/platform-ci-flake-digest.yml", import.meta.url),
      "utf8",
    );
    const buildIndex = workflow.indexOf("- name: Build flake digest");
    const validateIndex = workflow.indexOf("- name: Validate canonical flake digest payloads");
    const uploadIndex = workflow.indexOf("id: artifact");
    const publishIndex = workflow.indexOf("- name: Reconcile canonical flake digest issue");
    expect(workflow).toContain("issues: write");
    expect(workflow).toContain("--issue-body-out artifacts/release-health/ci-flake-digest-issue.md");
    expect(workflow).toContain("artifacts/release-health/ci-flake-digest.json");
    expect(workflow).toContain("artifacts/release-health/ci-flake-digest.md");
    expect(workflow).toContain("artifacts/release-health/ci-flake-digest-issue.md");
    expect(workflow).toContain('--artifact-producer-outcome "${{ steps.artifact.outcome }}"');
    expect(workflow).toContain("--validate-payloads true");
    expect(workflow).toContain("path: artifacts/release-health/ci-flake-digest*");
    expect(workflow).toContain("--producer-job digest");
    expect(workflow).toContain("--producer-step artifact");
    expect(workflow).not.toContain("gh issue create");
    expect(workflow).not.toContain("gh issue list");
    expect(buildIndex).toBeGreaterThan(-1);
    expect(validateIndex).toBeGreaterThan(buildIndex);
    expect(uploadIndex).toBeGreaterThan(validateIndex);
    expect(publishIndex).toBeGreaterThan(uploadIndex);
  });

  it("renders populated retry statistics through the production writer into the published issue body", async () => {
    const dir = await mkdtemp(join(tmpdir(), "flake-digest-writer-"));
    try {
      const paths = artifactPaths(dir);
      const digest = await writeReleaseHealthFlakeDigest({
        ...collectorOptions(
          completeCollectorFetch({
            currentRuns: [run(17, 4, "success")],
          }),
        ),
        ...paths,
      });
      const json = JSON.parse(await readFile(paths.outPath, "utf8"));
      const issueBody = await readFile(paths.issueBodyOutPath, "utf8");
      expect(digest.collection.status, JSON.stringify(digest.collection)).toBe("complete");
      expect(digest.classification).toBe("breaching");
      expect(json.issueBody).toContain("Retries: 3 (+3 vs previous window)");
      expect(json.issueBody).toContain("| Platform PR | 3 | +3 | 3 | +3 | yes |");
      expect(issueBody).toBe(`${json.issueBody}\n`);
      expect(await readFile(paths.markdownOutPath, "utf8")).toBe(`${json.markdown}\n`);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("includes retry-pass delivery signature recovery without classifying deterministic holds as flakes", async () => {
    const issue = (id, number, state, recoveryReason) => ({
      id,
      number,
      body: renderCircuitMarker({
        schemaVersion: "delivery-failure-signature/v1",
        signature: `signature-${number}`,
        lane: "merge-group",
        job: "Unit Tests",
        state,
        recoveredAt: "2026-07-07T12:00:00.000Z",
        recoveryReason,
      }),
    });
    const issues = [
      issue(101, 1, "recovered", "retry-pass evidence classified this occurrence as a flake"),
      issue(102, 2, "holding", ""),
    ];
    const digest = await collectReleaseHealthFlakeDigest(
      collectorOptions(completeCollectorFetch({ signatureIssues: issues })),
    );
    expect(digest.collection.status).toBe("complete");
    expect(digest.deliverySignatureFlakes).toEqual([
      expect.objectContaining({ issueNumber: 1, signature: "signature-1" }),
    ]);
    expect(
      summarizeDeliverySignatureFlakes(issues, {
        start: "2026-07-01T00:00:00.000Z",
        end: CHECKED_AT,
      }),
    ).toHaveLength(1);
  });

  it("summarizes retry telemetry by workflow name", () => {
    const summary = summarizeWorkflowRuns([
      { name: "Platform PR", run_attempt: 3, conclusion: "success" },
      { name: "Platform PR", run_attempt: 2, conclusion: "failure" },
      { name: "Platform Production", run_attempt: 1, conclusion: "success" },
    ]);
    expect(summary.retryCount).toBe(3);
    expect(summary.flakyFailureCount).toBe(2);
    expect([...summary.jobs.values()]).toEqual([{ name: "Platform PR", retryCount: 3, flakyFailureCount: 2 }]);
  });

  it("builds a weekly digest with previous-window trends and populated issue statistics", () => {
    const windows = buildDigestWindows(CHECKED_AT, 7);
    const digest = buildFlakeDigest({
      checkedAt: CHECKED_AT,
      repository: REPOSITORY,
      windows,
      thresholds: { retryCount: 3, flakyFailureCount: 1 },
      currentRuns: [
        { name: "Platform PR", run_attempt: 3, conclusion: "success" },
        { name: "Platform PR", run_attempt: 2, conclusion: "success" },
        { name: "Platform Production", run_attempt: 2, conclusion: "failure" },
      ],
      previousRuns: [{ name: "Platform PR", run_attempt: 2, conclusion: "success" }],
    });
    expect(digest).toMatchObject({
      schemaVersion: "release-health-flake-digest/v1",
      classification: "breaching",
      retryCount: 4,
      flakyFailureCount: 3,
      previousRetryCount: 1,
      previousFlakyFailureCount: 1,
      breachCount: 1,
      issueTitle: "CI flake digest aggregate signal",
    });
    expect(digest.markdown).toContain("| Platform PR | 3 | +2 | 3 | +2 | yes |");
    expect(digest.issueBody).toContain("| Platform PR | 3 | +2 | 3 | +2 | yes |");
  });

  it("reconciles provider-capped windows before classification", async () => {
    const current = buildDigestWindows(CHECKED_AT, 7).current;
    const midpoint = "2026-07-04T12:00:00.000Z";
    const leftRuns = Array.from({ length: 600 }, (_, index) =>
      run(index + 1, 1, "success", "Platform PR", "2026-07-03T00:00:00.000Z"),
    );
    leftRuns[leftRuns.length - 1] = run(600, 1, "success", "Platform PR", midpoint);
    const rightRuns = [
      leftRuns[leftRuns.length - 1],
      ...Array.from({ length: 401 }, (_, index) =>
        run(index + 601, 1, "success", "Platform PR", "2026-07-06T00:00:00.000Z"),
      ),
    ];
    rightRuns[rightRuns.length - 1] = run(1001, 2, "success", "Platform PR", "2026-07-06T00:00:00.000Z");
    const fetchImpl = async (input) => {
      const url = new URL(input);
      if (url.pathname === "/search/issues")
        return jsonResponse({ total_count: 0, incomplete_results: false, items: [] });
      const created = url.searchParams.get("created");
      if (created === `${current.start}..${current.end}`) {
        return jsonResponse({ total_count: 1001, workflow_runs: leftRuns.slice(0, 100) });
      }
      if (created === `${current.start}..${midpoint}`) return pagedRuns(url, leftRuns);
      if (created === `${midpoint}..${current.end}`) return pagedRuns(url, rightRuns);
      return jsonResponse({ total_count: 0, workflow_runs: [] });
    };
    const digest = await collectReleaseHealthFlakeDigest(collectorOptions(fetchImpl));
    expect(digest.collection.status).toBe("complete");
    expect(digest.retryCount).toBe(1);
    expect(digest.flakyFailureCount).toBe(1);
    expect(digest.collection.sources["actions-current"]).toMatchObject({
      reportedTotal: 1001,
      uniqueCollectedCount: 1001,
      capHit: true,
    });
    expect(digest.collection.sources["actions-current"].sourceRunIds.at(-1)).toBe("1001");
    expect(digest.collection.sources["actions-current"].shards).toHaveLength(2);
  });

  it("accepts a run created inside the window that finishes after the window ends", async () => {
    const digest = await collectReleaseHealthFlakeDigest(
      collectorOptions(
        completeCollectorFetch({
          currentRuns: [run(1, 2, "success", "Platform PR", "2026-07-07T12:00:00.000Z", "2026-07-08T12:00:00.000Z")],
        }),
      ),
    );
    expect(digest.collection.status, JSON.stringify(digest.collection)).toBe("complete");
    expect(digest.collection.sources["actions-current"].sourceRunIds).toEqual(["1"]);
    expect(digest.retryCount).toBe(1);
  });

  it("accepts a boundary-spanning run at a recursively sharded leaf", async () => {
    const current = buildDigestWindows(CHECKED_AT, 7).current;
    const midpoint = "2026-07-04T12:00:00.000Z";
    const leftRuns = Array.from({ length: 600 }, (_, index) =>
      run(index + 1, 1, "success", "Platform PR", "2026-07-03T00:00:00.000Z"),
    );
    const rightRuns = Array.from({ length: 401 }, (_, index) =>
      run(index + 601, 1, "success", "Platform PR", "2026-07-06T00:00:00.000Z"),
    );
    rightRuns[rightRuns.length - 1] = run(
      1001,
      2,
      "success",
      "Platform PR",
      "2026-07-06T00:00:00.000Z",
      "2026-07-09T00:00:00.000Z",
    );
    const fetchImpl = async (input) => {
      const url = new URL(input);
      if (url.pathname === "/search/issues")
        return jsonResponse({ total_count: 0, incomplete_results: false, items: [] });
      const created = url.searchParams.get("created");
      if (created === `${current.start}..${current.end}`) {
        return jsonResponse({ total_count: 1001, workflow_runs: leftRuns.slice(0, 100) });
      }
      if (created === `${current.start}..${midpoint}`) return pagedRuns(url, leftRuns);
      if (created === `${midpoint}..${current.end}`) return pagedRuns(url, rightRuns);
      return jsonResponse({ total_count: 0, workflow_runs: [] });
    };
    const digest = await collectReleaseHealthFlakeDigest(collectorOptions(fetchImpl));
    expect(digest.collection.status, JSON.stringify(digest.collection)).toBe("complete");
    expect(digest.collection.sources["actions-current"].shards).toHaveLength(2);
    expect(digest.collection.sources["actions-current"].sourceRunIds).toContain("1001");
    expect(digest.retryCount).toBe(1);
  });

  it("does not classify clear before a decisive retry beyond the first page", async () => {
    const runs = Array.from({ length: 101 }, (_, index) => run(index + 1));
    runs[100] = run(101, 2, "success");
    const fetchImpl = async (input) => {
      const url = new URL(input);
      if (url.pathname === "/search/issues")
        return jsonResponse({ total_count: 0, incomplete_results: false, items: [] });
      if (url.searchParams.get("created")?.startsWith("2026-07-01")) return pagedRuns(url, runs);
      return jsonResponse({ total_count: 0, workflow_runs: [] });
    };
    const digest = await collectReleaseHealthFlakeDigest(collectorOptions(fetchImpl));
    expect(digest.collection.status).toBe("complete");
    expect(digest.classification).toBe("breaching");
    expect(digest.retryCount).toBe(1);
    expect(digest.collection.sources["actions-current"]).toMatchObject({
      reportedTotal: 101,
      pageCount: 2,
      uniqueCollectedCount: 101,
    });
  });

  it("accepts only the payload-proven canonical repository pagination path", async () => {
    const currentWindow = buildDigestWindows(CHECKED_AT, 7).current;
    const first = { ...run(1), repository: { id: 42 } };
    const second = { ...run(2, 2), repository: { id: 42 } };
    const collector = (nextRepositoryId) => async (input) => {
      const url = new URL(input);
      if (url.pathname === "/search/issues")
        return jsonResponse({ total_count: 0, incomplete_results: false, items: [] });
      if (url.searchParams.get("created") !== `${currentWindow.start}..${currentWindow.end}`) {
        return jsonResponse({ total_count: 0, workflow_runs: [] });
      }
      if (url.searchParams.get("page") === "1") {
        const next = new URL(url);
        next.pathname = `/repositories/${nextRepositoryId}/actions/runs`;
        next.searchParams.set("page", "2");
        return jsonResponse({ total_count: 2, workflow_runs: [first] }, { link: `<${next}>; rel="next"` });
      }
      return jsonResponse({ total_count: 2, workflow_runs: [second] });
    };

    const accepted = await collectReleaseHealthFlakeDigest(collectorOptions(collector(42)));
    expect(accepted.collection.status).toBe("complete");
    expect(accepted.retryCount).toBe(1);

    const rejected = await collectReleaseHealthFlakeDigest(collectorOptions(collector(43)));
    expect(rejected.collection.status).toBe("unknown");
    expect(rejected.collection.reasons.join(" ")).toContain("unsafe-next-link");
  });

  it("keeps historical runs eligible across a mixed pre-rollout and current window", async () => {
    const syntheticPreRolloutHead = "b".repeat(40);
    const syntheticCurrentHead = "c".repeat(40);
    const digest = await collectReleaseHealthFlakeDigest(
      collectorOptions(
        completeCollectorFetch({
          currentRuns: [
            {
              ...run(2, 2, "success", "Platform PR", "2026-07-07T00:00:00.000Z"),
              head_sha: syntheticCurrentHead,
            },
          ],
          previousRuns: [
            {
              ...run(1, 2, "success", "Platform PR", "2026-06-30T00:00:00.000Z"),
              head_sha: syntheticPreRolloutHead,
            },
          ],
        }),
      ),
    );
    expect(digest.collection.status).toBe("complete");
    expect(digest).toMatchObject({ retryCount: 1, previousRetryCount: 1 });
    expect(digest.collection.sources["actions-current"].sourceRunIds).toEqual(["2"]);
    expect(digest.collection.sources["actions-previous"].sourceRunIds).toEqual(["1"]);
  });

  it("holds issue state on incomplete or unavailable GitHub authority", async () => {
    const scenarios = [
      {
        reason: "count mismatch",
        fetchImpl: completeCollectorFetch({ currentRuns: [run(1)], currentReportedTotal: 2 }),
        expected: "missing-next-link",
      },
      {
        reason: "incomplete search",
        fetchImpl: completeCollectorFetch({ searchIncomplete: true }),
        expected: "incomplete-search-results",
      },
      {
        reason: "unsafe next link",
        fetchImpl: completeCollectorFetch({
          currentRuns: [run(1)],
          currentReportedTotal: 2,
          currentLink: '<https://example.invalid/steal?page=2>; rel="next"',
        }),
        expected: "unsafe-next-link",
      },
      {
        reason: "GitHub unavailable",
        fetchImpl: completeCollectorFetch({ currentStatus: 503 }),
        expected: "github-503",
      },
      {
        reason: "rate limit exhausted",
        fetchImpl: completeCollectorFetch({ currentStatus: 403, currentRateRemaining: "0" }),
        expected: "rate-limit-exhausted",
      },
      {
        reason: "collector source omitted",
        fetchImpl: completeCollectorFetch({ omitSearchItems: true }),
        expected: "payload-missing-completeness",
      },
    ];
    for (const scenario of scenarios) {
      const digest = await collectReleaseHealthFlakeDigest(collectorOptions(scenario.fetchImpl));
      expect(digest.collection.status, scenario.reason).toBe("unknown");
      expect(digest.classification, scenario.reason).toBe("unknown");
      expect(digest.collection.reasons.join(" "), scenario.reason).toContain(scenario.expected);
    }

    const dir = await mkdtemp(join(tmpdir(), "flake-digest-unknown-"));
    try {
      const digest = await collectReleaseHealthFlakeDigest(
        collectorOptions(completeCollectorFetch({ currentRuns: [run(1)], currentReportedTotal: 2 })),
      );
      const paths = await writeFrozenArtifact(dir, digest);
      let issueRequests = 0;
      const result = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths),
        fetchImpl: async () => {
          issueRequests += 1;
          throw new Error("unknown publication must not read or mutate issue state");
        },
      });
      expect(result.status).toBe("unknown");
      expect(result.mutations).toEqual([]);
      expect(issueRequests).toBe(0);

      const completenessGuardBypassMutant = buildFlakeDigest({
        checkedAt: digest.checkedAt,
        repository: digest.repository,
        windows: digest.window,
        thresholds: digest.thresholds,
        currentRuns: [run(1)],
        previousRuns: [],
        signatureFlakes: [],
        collection: {
          status: "complete",
          reasons: [],
          sources: completeAuthoritySources(digest.window, { currentIds: ["1"] }),
        },
      });
      await writeFrozenArtifact(dir, completenessGuardBypassMutant);
      const github = issueAuthority();
      const bypass = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths, { runId: "9002" }),
        fetchImpl: github.fetchImpl,
      });
      expect(bypass.status).toBe("clear");
      expect(github.issues.get(7442).state).toBe("closed");
      expect(github.calls.some((call) => call.method === "PATCH" && call.number === 7442)).toBe(true);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("requires all exact payloads and exact successful producer-step evidence", async () => {
    const dir = await mkdtemp(join(tmpdir(), "flake-digest-artifact-"));
    try {
      const digest = clearDigest();
      const paths = await writeFrozenArtifact(dir, digest);
      await rm(paths.issueBodyOutPath);
      let requests = 0;
      const missingPayload = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths),
        fetchImpl: async () => {
          requests += 1;
          throw new Error("must not read issue authority");
        },
      });
      expect(missingPayload.status).toBe("unknown");
      expect(missingPayload.reasons.join(" ")).toContain("required-payload-unavailable");
      expect(requests).toBe(0);

      await writeFile(paths.issueBodyOutPath, `${digest.issueBody}\n`);
      const wrongOwningStep = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths),
        producerStep: "different-step",
        fetchImpl: async () => {
          requests += 1;
          throw new Error("must not read issue authority");
        },
      });
      expect(wrongOwningStep.status).toBe("unknown");
      expect(wrongOwningStep.reasons).toContain("artifact-producer-step-invalid");
      expect(requests).toBe(0);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("reconciles fixed canonical issue 7442 and closes only on complete clear", async () => {
    const dir = await mkdtemp(join(tmpdir(), "flake-digest-lifecycle-"));
    try {
      const github = issueAuthority();
      github.issues.set(7443, {
        number: 7443,
        node_id: "adjacent-node",
        title: "Copied marker is not authority",
        body: `<!-- ${CI_FLAKE_DIGEST_MARKER_VERSION} {"schemaVersion":"${CI_FLAKE_DIGEST_MARKER_VERSION}"} -->`,
        state: "open",
        state_reason: null,
      });

      let paths = await writeFrozenArtifact(dir, clearDigest());
      const firstClear = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths, { runId: "9101" }),
        fetchImpl: github.fetchImpl,
      });
      expect(firstClear.status).toBe("clear");
      expect(github.issues.get(7442)).toMatchObject({
        number: 7442,
        title: "CI flake digest aggregate signal",
        state: "closed",
        state_reason: "completed",
      });

      const breach = breachingDigest("2026-07-15T00:00:00.000Z");
      paths = await writeFrozenArtifact(dir, breach);
      const opened = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths, { runId: "9102" }),
        fetchImpl: github.fetchImpl,
      });
      expect(opened.status).toBe("breaching");
      expect(github.issues.get(7442).state).toBe("open");
      expect(github.issues.get(7442).body).toContain(breach.window.current.start);

      const repeated = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths, { runId: "9102" }),
        fetchImpl: github.fetchImpl,
      });
      expect(repeated.mutations[0]).toEqual({ issueNumber: 7442, action: "already-converged" });

      paths = await writeFrozenArtifact(dir, clearDigest("2026-07-22T00:00:00.000Z"));
      const recovered = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths, { runId: "9103" }),
        fetchImpl: github.fetchImpl,
      });
      expect(recovered.status).toBe("clear");
      expect(github.issues.get(7442).state).toBe("closed");
      expect(github.issues.get(7442).body).toContain("2026-07-15T00:00:00.000Z");
      for (const number of [5815, 6215, 6504, 6715, 7442]) {
        expect(markerCount(github.issues.get(number).body, CI_FLAKE_DIGEST_DISPOSITION_VERSION)).toBe(1);
      }
      expect(markerCount(github.issues.get(7442).body, CI_FLAKE_DIGEST_MARKER_VERSION)).toBe(1);
      expect(github.calls.some((call) => call.method === "POST")).toBe(false);
      expect(github.calls.some((call) => call.number === 7443)).toBe(false);
      expect(github.issues.get(7443).state).toBe("open");

      const patchesBeforeMalformed = github.calls.filter((call) => call.method === "PATCH").length;
      github.issues.get(7442).body += `\n<!-- ${CI_FLAKE_DIGEST_MARKER_VERSION} malformed -->`;
      const malformed = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths, { runId: "9104" }),
        fetchImpl: github.fetchImpl,
      });
      expect(malformed.status).toBe("unknown");
      expect(github.calls.filter((call) => call.method === "PATCH")).toHaveLength(patchesBeforeMalformed);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("migrates the exact five legacy breach issues across partial cross-state resume", async () => {
    const dir = await mkdtemp(join(tmpdir(), "flake-digest-migration-"));
    try {
      const github = issueAuthority();
      github.failPatchNumber = 6504;
      let paths = await writeFrozenArtifact(dir, clearDigest());
      await expect(
        publishReleaseHealthFlakeDigest({
          ...publicationOptions(paths, { runId: "9201" }),
          fetchImpl: github.fetchImpl,
        }),
      ).rejects.toThrow("Issue #6504 mutation did not reconcile");
      expect(github.issues.get(7442).state).toBe("closed");
      expect(github.issues.get(5815).body).toContain('"action":"recovered"');
      expect(github.issues.get(6215).body).toContain('"action":"recovered"');
      expect(github.issues.get(6504).state).toBe("open");
      expect(github.issues.get(6715).state).toBe("open");

      github.failPatchNumber = null;
      paths = await writeFrozenArtifact(dir, breachingDigest("2026-07-15T00:00:00.000Z"));
      const resumed = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths, { runId: "9202" }),
        fetchImpl: github.fetchImpl,
      });
      expect(resumed.status).toBe("breaching");
      expect(github.issues.get(7442).state).toBe("open");
      expect(github.issues.get(5815).body).toContain('"action":"recovered"');
      expect(github.issues.get(6215).body).toContain('"action":"recovered"');
      expect(github.issues.get(6504).body).toContain('"action":"superseded"');
      expect(github.issues.get(6715).body).toContain('"action":"superseded"');
      expect(resumed.mutations.map((entry) => entry.issueNumber)).toEqual([7442, 5815, 6215, 6504, 6715]);
      expect(
        github.calls
          .filter((call) => call.method === "PATCH")
          .map((call) => call.number)
          .slice(-3),
      ).toEqual([7442, 6504, 6715]);
      for (const number of [5815, 6215, 6504, 6715, 7442]) {
        expect(markerCount(github.issues.get(number).body, CI_FLAKE_DIGEST_DISPOSITION_VERSION)).toBe(1);
      }
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("reconciles an ambiguous PATCH response by direct issue identity", async () => {
    const dir = await mkdtemp(join(tmpdir(), "flake-digest-ambiguous-"));
    try {
      const github = issueAuthority();
      github.ambiguousPatchNumber = 7442;
      const paths = await writeFrozenArtifact(dir, breachingDigest());
      const result = await publishReleaseHealthFlakeDigest({
        ...publicationOptions(paths, { runId: "9301" }),
        fetchImpl: github.fetchImpl,
      });
      expect(result.mutations[0]).toEqual({
        issueNumber: 7442,
        action: "reconciled-ambiguous-response",
      });
      expect(github.calls.some((call) => call.method === "POST")).toBe(false);
      expect(markerCount(github.issues.get(7442).body, CI_FLAKE_DIGEST_DISPOSITION_VERSION)).toBe(1);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("aborts instead of authoring from a lagging issue projection", async () => {
    const dir = await mkdtemp(join(tmpdir(), "flake-digest-etag-"));
    try {
      const github = issueAuthority();
      github.driftOnSecondReadNumber = 7442;
      const paths = await writeFrozenArtifact(dir, breachingDigest());
      await expect(
        publishReleaseHealthFlakeDigest({
          ...publicationOptions(paths, { runId: "9401" }),
          fetchImpl: github.fetchImpl,
        }),
      ).rejects.toThrow("issue-7442-authority-moved");
      expect(github.issues.get(7442).body).toContain("external concurrent edit");
      expect(github.calls.filter((call) => call.method === "PATCH")).toHaveLength(0);
      for (const number of [5815, 6215, 6504, 6715]) expect(github.issues.get(number).state).toBe("open");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("parses workflow defaults and publication evidence from the environment", () => {
    expect(
      parseReleaseHealthFlakeDigestArgs(["--window-days", "14", "--publish-issues", "true"], {
        GITHUB_REPOSITORY: REPOSITORY,
        GH_TOKEN: "token",
        GITHUB_OUTPUT: "github-output.txt",
        GITHUB_RUN_ID: "123",
        GITHUB_RUN_ATTEMPT: "2",
        GITHUB_SHA: HEAD_SHA,
      }),
    ).toMatchObject({
      repository: REPOSITORY,
      token: "token",
      windowDays: 14,
      retryThreshold: 3,
      flakyFailureThreshold: 1,
      githubOutputPath: "github-output.txt",
      publishIssues: true,
      runId: "123",
      runAttempt: 2,
      headSha: HEAD_SHA,
    });
  });
});

function run(
  id,
  runAttempt = 1,
  conclusion = "success",
  name = "Platform PR",
  createdAt = "2026-07-07T00:00:00.000Z",
  updatedAt = createdAt,
) {
  return { id, name, run_attempt: runAttempt, conclusion, created_at: createdAt, updated_at: updatedAt };
}

function collectorOptions(fetchImpl) {
  return {
    repository: REPOSITORY,
    token: "token",
    checkedAt: CHECKED_AT,
    windowDays: 7,
    retryThreshold: 3,
    flakyFailureThreshold: 1,
    fetchImpl,
  };
}

function completeCollectorFetch(options = {}) {
  return async (input) => {
    const url = new URL(input);
    if (url.pathname === "/search/issues") {
      const payload = {
        total_count: (options.signatureIssues ?? []).length,
        incomplete_results: options.searchIncomplete ?? false,
        ...(options.omitSearchItems ? {} : { items: options.signatureIssues ?? [] }),
      };
      return jsonResponse(payload);
    }
    const current = url.searchParams.get("created")?.startsWith("2026-07-01");
    const runs = current ? (options.currentRuns ?? []) : (options.previousRuns ?? []);
    const status = current ? (options.currentStatus ?? 200) : (options.previousStatus ?? 200);
    const reportedTotal = current
      ? (options.currentReportedTotal ?? runs.length)
      : (options.previousReportedTotal ?? runs.length);
    const link = current ? options.currentLink : options.previousLink;
    const rateRemaining = current ? options.currentRateRemaining : options.previousRateRemaining;
    return jsonResponse({ total_count: reportedTotal, workflow_runs: runs }, { status, link, rateRemaining });
  };
}

function pagedRuns(url, runs) {
  const page = Number(url.searchParams.get("page") ?? 1);
  const start = (page - 1) * 100;
  const values = runs.slice(start, start + 100);
  const link = start + values.length < runs.length ? nextLink(url, page + 1) : null;
  return jsonResponse({ total_count: runs.length, workflow_runs: values }, { link });
}

function nextLink(url, page) {
  const next = new URL(url);
  next.searchParams.set("page", String(page));
  return `<${next}>; rel="next"`;
}

function jsonResponse(payload, options = {}) {
  const status = options.status ?? 200;
  return {
    ok: status >= 200 && status < 300,
    status,
    headers: {
      get: (name) => {
        if (String(name).toLowerCase() === "link") return options.link ?? null;
        if (String(name).toLowerCase() === "x-ratelimit-remaining") return options.rateRemaining ?? null;
        if (String(name).toLowerCase() === "etag") return options.etag ?? null;
        return null;
      },
    },
    json: async () => structuredClone(payload),
  };
}

function artifactPaths(dir) {
  return {
    outPath: join(dir, "ci-flake-digest.json"),
    markdownOutPath: join(dir, "ci-flake-digest.md"),
    issueBodyOutPath: join(dir, "ci-flake-digest-issue.md"),
  };
}

async function writeFrozenArtifact(dir, digest) {
  const paths = artifactPaths(dir);
  await Promise.all([
    writeFile(paths.outPath, `${JSON.stringify(digest, null, 2)}\n`),
    writeFile(paths.markdownOutPath, `${digest.markdown}\n`),
    writeFile(paths.issueBodyOutPath, `${digest.issueBody}\n`),
  ]);
  return paths;
}

function publicationOptions(paths, overrides = {}) {
  return {
    repository: REPOSITORY,
    token: "token",
    ...paths,
    artifactId: "9728430414",
    artifactDigest: `sha256:${"b".repeat(64)}`,
    artifactProducerOutcome: "success",
    producerWorkflow: "platform-ci-flake-digest.yml",
    producerJob: "digest",
    producerStep: "artifact",
    runId: "9001",
    runAttempt: 1,
    headSha: HEAD_SHA,
    ...overrides,
  };
}

function clearDigest(checkedAt = CHECKED_AT) {
  const windows = buildDigestWindows(checkedAt, 7);
  return buildFlakeDigest({
    checkedAt,
    repository: REPOSITORY,
    windows,
    thresholds: { retryCount: 3, flakyFailureCount: 1 },
    currentRuns: [],
    previousRuns: [],
    signatureFlakes: [],
    collection: { status: "complete", reasons: [], sources: completeAuthoritySources(windows) },
  });
}

function breachingDigest(checkedAt = CHECKED_AT) {
  const windows = buildDigestWindows(checkedAt, 7);
  return buildFlakeDigest({
    checkedAt,
    repository: REPOSITORY,
    windows,
    thresholds: { retryCount: 3, flakyFailureCount: 1 },
    currentRuns: [run(1, 2, "success")],
    previousRuns: [],
    signatureFlakes: [],
    collection: {
      status: "complete",
      reasons: [],
      sources: completeAuthoritySources(windows, { currentIds: ["1"] }),
    },
  });
}

function completeAuthoritySources(windows, options = {}) {
  const actions = (window, sourceRunIds) => ({
    status: "complete",
    window,
    reportedTotal: sourceRunIds.length,
    uniqueCollectedCount: sourceRunIds.length,
    pageCount: 1,
    capHit: false,
    sourceRunIds,
    shards: [
      {
        window,
        reportedTotal: sourceRunIds.length,
        uniqueCollectedCount: sourceRunIds.length,
        pageCount: 1,
        capHit: false,
      },
    ],
  });
  return {
    "actions-current": actions(windows.current, options.currentIds ?? []),
    "actions-previous": actions(windows.previous, options.previousIds ?? []),
    "delivery-signatures": {
      status: "complete",
      query: "delivery-failure-signature/v1",
      reportedTotal: 0,
      uniqueCollectedCount: 0,
      pageCount: 1,
    },
    "vitest-current": { status: "complete", window: windows.current, requestCount: 0, producers: [] },
  };
}

// Synthetic GitHub/Vitest identities; never paired with a real external run.
function syntheticVitestPayload(runId, attempt, options = {}) {
  const date = options.reverse
    ? runId === 101
      ? "2026-07-07"
      : "2026-07-06"
    : runId === 101 && attempt === 1
      ? "2026-07-06"
      : "2026-07-07";
  const first = runId === 101 && attempt === 1;
  const state = first ? (options.firstState ?? "failed") : (options.secondState ?? "passed");
  const payload = {
    schemaVersion: "workspace-test-results/v1",
    producer: {
      repository: REPOSITORY,
      headSha: !first && options.changedHead ? "c".repeat(40) : HEAD_SHA,
      testedSha: !first && options.changedTestedSha ? "d".repeat(40) : "b".repeat(40),
      runId: String(runId),
      runAttempt: attempt,
      job: "unit-tests",
    },
    invocations: [
      {
        id: `${"0".repeat(32)}${String(runId).padStart(4, "0")}`,
        script: "test",
        startedAt: `${date}T10:01:00.000Z`,
        completedAt: `${date}T10:02:00.000Z`,
        tasks: [
          {
            workspace: "@chase-sets/synthetic",
            script: "test",
            status: options.unknownTask ? "unknown" : "complete",
            reason: options.unknownTask ? "started report missing" : "",
            assertionCount: options.unknownTask ? 0 : 1,
            fileFailureCount: 0,
            rows: options.unknownTask
              ? []
              : [
                  {
                    file: "bounded-contexts/synthetic/test.test.ts",
                    fullName: options.emptyName
                      ? ""
                      : !first && options.changedName
                        ? "different test"
                        : "suite synthetic test",
                    state,
                    durationMs: options.malformed ? -1 : 1.25,
                    retryCount: 0,
                  },
                ],
          },
          ...(options.unstartedSibling
            ? [
                {
                  workspace: "@chase-sets/synthetic",
                  script: "test:unit",
                  status: "not-started",
                  reason: "",
                  assertionCount: 0,
                  fileFailureCount: 0,
                  rows: [],
                },
              ]
            : []),
        ],
      },
    ],
  };
  const task = payload.invocations[0].tasks[0];
  if (options.duplicateNames) {
    task.rows.push({ ...task.rows[0], state: first ? "passed" : "failed", durationMs: 25 });
    task.assertionCount++;
    if (!first && options.reverseDuplicates) task.rows.reverse();
  }
  if (options.duplicateInvocation) {
    const invocation = structuredClone(payload.invocations[0]);
    invocation.id = "f".repeat(36);
    payload.invocations.push(invocation);
  }
  return payload;
}

function vitestCollectorFetch(options = {}) {
  const runs = options.sameRunRetry ? [run(101, 2)] : [run(101, 1, "failure"), run(102)];
  for (const value of runs)
    Object.assign(value, {
      path: ".github/workflows/platform-pr.yml",
      status: "completed",
      head_sha: options.changedHead && value.id === 102 ? "c".repeat(40) : HEAD_SHA,
      repository: { id: 42 },
    });
  const fallback = completeCollectorFetch({ currentRuns: runs });
  return async (input) => {
    const url = new URL(input);
    const jobsMatch = url.pathname.match(/\/runs\/(\d+)\/attempts\/(\d+)\/jobs$/);
    if (jobsMatch) {
      const runId = Number(jobsMatch[1]);
      const attempt = Number(jobsMatch[2]);
      const p = syntheticVitestPayload(runId, attempt, options);
      const date = p.invocations[0].startedAt.slice(0, 10);
      const job = {
        id: runId * 10 + attempt,
        run_id: runId,
        run_attempt: attempt,
        name: "Unit Tests",
        status: "completed",
        conclusion: "success",
        steps: [
          {
            name: "Run non-DB tests",
            status: "completed",
            conclusion: options.skipped ? "skipped" : options.cancelled ? "cancelled" : "success",
            started_at: `${date}T10:00:00Z`,
            completed_at: `${date}T10:03:00Z`,
          },
          ...(options.preRollout
            ? []
            : [{ name: "Prepare workspace test results", status: "completed", conclusion: "success" }]),
        ],
      };
      if (options.secondPage) {
        const dummy = Array.from({ length: 100 }, (_, i) => ({ id: 20000 + i, name: "unrelated" }));
        if (url.searchParams.get("page") === "1")
          return jsonResponse(
            { total_count: 101, jobs: dummy },
            { link: nextLink(new URL(url.toString().replace(`/repos/${REPOSITORY}`, "/repositories/42")), 2) },
          );
      }
      return jsonResponse({ total_count: options.secondPage ? 101 : 1, jobs: [job] });
    }
    const artifactMatch = url.pathname.match(/\/runs\/(\d+)\/artifacts$/);
    if (artifactMatch) {
      const runId = Number(artifactMatch[1]);
      const attempts = options.sameRunRetry ? [1, 2] : [1];
      const artifacts = options.missingArtifact
        ? []
        : attempts.map((attempt) => ({
            id: runId * 10 + attempt,
            name: `workspace-test-results-unit-tests-${runId}-${attempt}`,
            size_in_bytes: 2000,
            expired: options.expired ?? false,
            expires_at: "2026-07-12T00:00:00Z",
          }));
      if (options.duplicateArtifact) artifacts.push({ ...artifacts[0], id: 9999 });
      if (options.duplicateAttempt) artifacts.push(artifacts[0]);
      if (options.secondPage || options.incompletePage) {
        if (url.searchParams.get("page") === "1")
          return jsonResponse(
            {
              total_count: 101,
              artifacts: Array.from({ length: 100 }, (_, i) => ({ id: 10000 + i, name: "unrelated" })),
            },
            { link: options.incompletePage ? null : nextLink(url, 2) },
          );
      }
      return jsonResponse({ total_count: options.secondPage ? 101 : artifacts.length, artifacts });
    }
    const zipMatch = url.pathname.match(/\/artifacts\/(\d+)\/zip$/);
    if (zipMatch) {
      const id = Number(zipMatch[1]);
      const bytes = storedZip([
        [
          options.missingPayload ? "diagnostic.json" : "workspace-test-results.json",
          Buffer.from(JSON.stringify(syntheticVitestPayload(Math.floor(id / 10), id % 10, options))),
        ],
      ]);
      return { ok: true, arrayBuffer: async () => bytes };
    }
    return fallback(input);
  };
}

function storedZip(entries) {
  const localParts = [];
  const centralParts = [];
  let offset = 0;
  for (const [name, bytes] of entries) {
    const nameBytes = Buffer.from(name);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt32LE(bytes.length, 18);
    local.writeUInt32LE(bytes.length, 22);
    local.writeUInt16LE(nameBytes.length, 26);
    localParts.push(local, nameBytes, bytes);
    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt32LE(bytes.length, 20);
    central.writeUInt32LE(bytes.length, 24);
    central.writeUInt16LE(nameBytes.length, 28);
    central.writeUInt32LE(offset, 42);
    centralParts.push(central, nameBytes);
    offset += local.length + nameBytes.length + bytes.length;
  }
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(Buffer.concat(centralParts).length, 12);
  end.writeUInt32LE(offset, 16);
  return Buffer.concat([...localParts, ...centralParts, end]);
}

function issueAuthority() {
  const issues = new Map(
    LEGACY.map(([number, node_id, title]) => [
      number,
      { number, node_id, title, body: LEGACY_BODY, state: "open", state_reason: null },
    ]),
  );
  const calls = [];
  const readCounts = new Map();
  const state = {
    issues,
    calls,
    failPatchNumber: null,
    ambiguousPatchNumber: null,
    driftOnSecondReadNumber: null,
    fetchImpl: async (input, request = {}) => {
      const url = new URL(input);
      const method = request.method ?? "GET";
      const match = url.pathname.match(/\/issues\/(\d+)$/);
      const number = match ? Number(match[1]) : null;
      calls.push({ method, number, path: url.pathname });
      if (!match || !issues.has(number)) return jsonResponse({}, { status: 404 });
      if (method === "GET") {
        const readCount = (readCounts.get(number) ?? 0) + 1;
        readCounts.set(number, readCount);
        if (state.driftOnSecondReadNumber === number && readCount === 2) {
          issues.set(number, { ...issues.get(number), body: `${issues.get(number).body}\nexternal concurrent edit` });
        }
        return jsonResponse(issues.get(number));
      }
      if (method !== "PATCH") return jsonResponse({}, { status: 405 });
      if (state.failPatchNumber === number) return jsonResponse({}, { status: 503 });
      const desired = JSON.parse(request.body);
      const saved = { ...issues.get(number), ...desired };
      if (desired.state === "open" && desired.state_reason === undefined) saved.state_reason = null;
      issues.set(number, saved);
      if (state.ambiguousPatchNumber === number) {
        state.ambiguousPatchNumber = null;
        throw new Error("connection reset after write");
      }
      return jsonResponse(saved);
    },
  };
  return state;
}

function markerCount(body, version) {
  return String(body).split(`<!-- ${version} `).length - 1;
}
