import process from "node:process";

// Generated status for the program roadmap issue. The contract this reports
// against lives in docs/contributing/backlog-model.md. Numbers are generated
// because a hand-maintained rollup drifted on 5 of 12 rows in two weeks.

export const START_MARKER = "<!-- roadmap-status:start -->";
export const END_MARKER = "<!-- roadmap-status:end -->";

const EPIC_LABEL = "kind:epic";
const NON_EXECUTABLE_MILESTONES = new Set(["Deferred / Incubation", "Operations"]);

// The native issue type is authoritative. `kind:epic` is kept as a fallback
// because the label predates the type and the orchestrator still reads it.
export function isEpic(issue) {
  const type = issue.type?.name ?? issue.issueType?.name ?? null;
  if (type) return type === "Epic";
  return (issue.labels ?? []).some((label) => (label.name ?? label) === EPIC_LABEL);
}

export function isRefined(issue) {
  const names = (issue.labels ?? []).map((label) => label.name ?? label);
  return (
    Boolean(issue.milestone) &&
    names.some((name) => name.startsWith("priority:")) &&
    names.some((name) => name.startsWith("area:"))
  );
}

function pct(part, total) {
  return total === 0 ? 0 : Math.round((part / total) * 100);
}

/**
 * @param issues all repository issues (open and closed), excluding pull requests
 * @param epicChildren Map<epicNumber, Array<{state, milestone}>>
 * @param nowMs timestamp used for the "added recently" window
 */
export function summarizeWaves({ milestones, issues, epicChildren = new Map(), nowMs, windowDays = 7 }) {
  const slices = issues.filter((issue) => !isEpic(issue));
  const epics = issues.filter(isEpic);
  const cutoff = nowMs - windowDays * 24 * 60 * 60 * 1000;

  // An epic's wave is the earliest-dated wave among its children: epics are
  // unmilestoned by contract, so they have no wave of their own.
  const milestoneOrder = new Map(milestones.map((milestone, index) => [milestone.title, index]));
  const epicWave = new Map();
  for (const epic of epics) {
    const children = epicChildren.get(epic.number) ?? [];
    let best = null;
    for (const child of children) {
      const title = child.milestone?.title;
      if (!title || !milestoneOrder.has(title)) continue;
      if (best === null || milestoneOrder.get(title) < milestoneOrder.get(best)) best = title;
    }
    if (best) epicWave.set(epic.number, best);
  }

  const rows = milestones.map((milestone) => {
    const mine = slices.filter((issue) => issue.milestone?.title === milestone.title);
    const closed = mine.filter((issue) => issue.state === "closed");
    const open = mine.filter((issue) => issue.state === "open");
    const addedRecently = mine.filter((issue) => Date.parse(issue.created_at) >= cutoff);

    const waveEpics = epics.filter((epic) => epicWave.get(epic.number) === milestone.title);
    const completeEpics = waveEpics.filter((epic) => {
      const children = epicChildren.get(epic.number) ?? [];
      return children.length > 0 && children.every((child) => child.state === "closed");
    });

    return {
      title: milestone.title,
      dueOn: milestone.due_on ? milestone.due_on.slice(0, 10) : "—",
      executable: !NON_EXECUTABLE_MILESTONES.has(milestone.title),
      total: mine.length,
      closed: closed.length,
      open: open.length,
      percent: pct(closed.length, mine.length),
      addedRecently: addedRecently.length,
      refinedOpen: open.filter(isRefined).length,
      epicsTotal: waveEpics.length,
      epicsComplete: completeEpics.length,
    };
  });

  return { rows, windowDays };
}

export function renderRoadmapStatus(summary) {
  const lines = [
    START_MARKER,
    "",
    "## Generated status",
    "",
    "Generated by `scripts/roadmap-status.mjs`. Do not edit by hand — edits are overwritten.",
    "Contract: [`docs/contributing/backlog-model.md`](../blob/main/docs/contributing/backlog-model.md).",
    "",
    "| Outcome | Target | Slices | Done | Open | Refined | Added (7d) | Epics done |",
    "|---|---|---:|---:|---:|---:|---:|---:|",
  ];

  for (const row of summary.rows) {
    const label = row.executable ? row.title : `${row.title} _(not executable)_`;
    const refined = row.executable ? `${row.refinedOpen}/${row.open}` : "—";
    const epics = row.epicsTotal === 0 ? "—" : `${row.epicsComplete}/${row.epicsTotal}`;
    const growth = row.addedRecently > 0 ? `+${row.addedRecently}` : "0";
    lines.push(
      `| ${label} | ${row.dueOn} | ${row.total} | ${row.closed} (${row.percent}%) | ${row.open} | ${refined} | ${growth} | ${epics} |`,
    );
  }

  const executable = summary.rows.filter((row) => row.executable);
  const totalOpen = executable.reduce((sum, row) => sum + row.open, 0);
  const totalRefined = executable.reduce((sum, row) => sum + row.refinedOpen, 0);
  const totalAdded = executable.reduce((sum, row) => sum + row.addedRecently, 0);

  lines.push(
    "",
    `Executable backlog: **${totalOpen} open slices**, ${totalRefined} refined (${pct(totalRefined, totalOpen)}%), ` +
      `${totalAdded} added in the last ${summary.windowDays} days.`,
    "",
    "**Refined** = milestone + `priority:*` + `area:*`. Unrefined far-horizon work is expected, not a defect.",
    "",
    END_MARKER,
  );

  return lines.join("\n");
}

export function spliceIntoBody(body, block) {
  const text = String(body ?? "");
  const start = text.indexOf(START_MARKER);
  const end = text.indexOf(END_MARKER);
  if (start === -1 || end === -1 || end < start) {
    // Fail safe: never rewrite a body that has not opted in with markers.
    return null;
  }
  return `${text.slice(0, start)}${block}${text.slice(end + END_MARKER.length)}`;
}

async function gh(pathname, token, init = {}) {
  const url = pathname.startsWith("http") ? pathname : `https://api.github.com${pathname}`;
  const response = await fetch(url, {
    ...init,
    headers: {
      accept: "application/vnd.github+json",
      authorization: `Bearer ${token}`,
      "x-github-api-version": "2022-11-28",
      ...(init.headers ?? {}),
    },
  });
  if (!response.ok) {
    throw new Error(`GitHub request failed: ${response.status} ${pathname} ${await response.text()}`);
  }
  return response;
}

async function paginate(pathname, token) {
  const items = [];
  let url = pathname;
  while (url) {
    const response = await gh(url, token);
    items.push(...(await response.json()));
    const link = response.headers.get("link") ?? "";
    const next = link.split(",").find((part) => part.includes('rel="next"'));
    url = next ? next.slice(next.indexOf("<") + 1, next.indexOf(">")) : null;
  }
  return items;
}

async function main() {
  const repo = process.env.GITHUB_REPOSITORY;
  const token = process.env.GITHUB_TOKEN;
  const roadmapIssue = process.env.ROADMAP_ISSUE;
  if (!repo || !token) {
    console.error("GITHUB_REPOSITORY and GITHUB_TOKEN are required.");
    return 2;
  }

  const milestones = (await paginate(`/repos/${repo}/milestones?state=open&per_page=100`, token)).sort((a, b) => {
    if (!a.due_on) return 1;
    if (!b.due_on) return -1;
    return a.due_on.localeCompare(b.due_on);
  });
  const raw = await paginate(`/repos/${repo}/issues?state=all&per_page=100`, token);
  const issues = raw.filter((issue) => !issue.pull_request);

  const epicChildren = new Map();
  for (const epic of issues.filter(isEpic)) {
    const children = await paginate(`/repos/${repo}/issues/${epic.number}/sub_issues?per_page=100`, token);
    epicChildren.set(
      epic.number,
      children.map((child) => ({ state: child.state, milestone: child.milestone })),
    );
  }

  const summary = summarizeWaves({ milestones, issues, epicChildren, nowMs: Date.now() });
  const block = renderRoadmapStatus(summary);
  console.log(block);

  if (process.env.GITHUB_STEP_SUMMARY) {
    const { appendFileSync } = await import("node:fs");
    appendFileSync(process.env.GITHUB_STEP_SUMMARY, `${block}\n`);
  }

  if (roadmapIssue) {
    const current = await (await gh(`/repos/${repo}/issues/${roadmapIssue}`, token)).json();
    const next = spliceIntoBody(current.body, block);
    if (next === null) {
      console.error(`Issue #${roadmapIssue} has no roadmap-status markers; leaving the body untouched.`);
      return 1;
    }
    if (next !== current.body) {
      await gh(`/repos/${repo}/issues/${roadmapIssue}`, token, {
        method: "PATCH",
        body: JSON.stringify({ body: next }),
      });
    }
  }

  return 0;
}

if (process.argv[1] && process.argv[1].endsWith("roadmap-status.mjs")) {
  process.exitCode = await main();
}
