import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  analyzeLocaleCatalogModule,
  assertNoLocaleCatalogKeyCollisions,
  listTrackedLocaleModulePaths,
  syncWorkspaceMetadata,
} from "./sync-workspace-metadata.mjs";

const tempRoots = [];

function writeJson(filePath, value) {
  writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

async function createMetadataFixture() {
  const rootDir = mkdtempSync(path.join(tmpdir(), "chase-sets-metadata-"));
  tempRoots.push(rootDir);

  await mkdir(path.join(rootDir, "bounded-contexts", "catalog"), { recursive: true });
  await mkdir(path.join(rootDir, "infrastructure", "event-core-postgres"), { recursive: true });
  await mkdir(path.join(rootDir, "contracts", "localization", "locales", "en"), { recursive: true });

  writeJson(path.join(rootDir, "tsconfig.base.json"), {
    compilerOptions: {
      paths: {},
    },
  });
  writeJson(path.join(rootDir, "bounded-contexts", "catalog", "context.json"), {
    contextName: "catalog",
    localeCatalogs: ["contracts/localization/locales/en/example.ts"],
    apiDeployables: ["platform-api"],
    runtimeDeployables: ["platform-worker"],
    deployableContributions: [
      {
        deployable: "marketplace-web",
      },
    ],
  });
  writeFileSync(
    path.join(rootDir, "infrastructure", "event-core-postgres", "schema.sql"),
    "CREATE TABLE IF NOT EXISTS event_store_events (event_id text PRIMARY KEY);\n",
    "utf8",
  );
  writeFileSync(
    path.join(rootDir, "contracts", "localization", "locales", "en", "example.ts"),
    'export const exampleEnglishTranslations = {\n  "example.key": "Example",\n} as const;\n',
    "utf8",
  );

  const workspaces = [
    {
      name: "@chase-sets/catalog",
      dir: path.join(rootDir, "bounded-contexts", "catalog"),
      dirName: "catalog",
      root: "bounded-contexts",
      packageJson: {
        name: "@chase-sets/catalog",
        exports: {
          ".": "./index.ts",
          "./context": "./context.json",
        },
      },
    },
    {
      name: "@chase-sets/localization",
      dir: path.join(rootDir, "contracts", "localization"),
      dirName: "localization",
      root: "contracts",
      packageJson: {
        name: "@chase-sets/localization",
        exports: {
          ".": "./index.ts",
          "./locales/en": "./locales/en.ts",
          "./locales/en/*": "./locales/en/*.ts",
        },
      },
    },
  ];

  return {
    rootDir,
    trackedLocaleFiles: ["contracts/localization/locales/en/example.ts"],
    workspaces,
  };
}

afterEach(() => {
  for (const rootDir of tempRoots.splice(0)) {
    rmSync(rootDir, { recursive: true, force: true });
  }
});

describe("sync-workspace-metadata --check", () => {
  it("passes when generated metadata is current", async () => {
    const fixture = await createMetadataFixture();

    syncWorkspaceMetadata(fixture);

    expect(readFileSync(path.join(fixture.rootDir, "tsconfig.base.json"), "utf8")).toMatch(
      /^\/\/ Workspace tsconfigs extend this file or tsconfig\.vitest\.json;/,
    );
    const tsconfigBase = JSON.parse(
      readFileSync(path.join(fixture.rootDir, "tsconfig.base.json"), "utf8").replace(/^\/\/.*\n/, ""),
    );
    expect(tsconfigBase.compilerOptions).toMatchObject({
      module: "Preserve",
      moduleResolution: "Bundler",
    });
    expect(tsconfigBase.compilerOptions).not.toHaveProperty("importsNotUsedAsValues");
    expect(tsconfigBase.compilerOptions).not.toHaveProperty("preserveValueImports");
    expect(tsconfigBase.compilerOptions).not.toHaveProperty("verbatimModuleSyntax");
    expect(() => syncWorkspaceMetadata({ ...fixture, check: true })).not.toThrow();
    const englishMerge = readFileSync(
      path.join(fixture.rootDir, "contracts", "localization", "locales", "en.ts"),
      "utf8",
    );
    expect(englishMerge).toContain("// Generated by scripts/sync-workspace-metadata.mjs. Do not edit by hand.");
    expect(englishMerge).toContain('import { exampleEnglishTranslations } from "./en/example";');
    expect(englishMerge).toContain("export type EnglishTranslationKey = keyof typeof englishTranslations;");
  });

  it("fails when the generated event-core Postgres schema is stale", async () => {
    const fixture = await createMetadataFixture();
    syncWorkspaceMetadata(fixture);
    const generatedPath = path.join(fixture.rootDir, "infrastructure", "event-core-postgres", "schema.ts");
    const staleContent = 'export const eventCorePostgresSchemaSql = "stale";\n';
    writeFileSync(generatedPath, staleContent, "utf8");

    expect(() => syncWorkspaceMetadata({ ...fixture, check: true })).toThrow(
      /infrastructure\/event-core-postgres\/schema\.ts is stale/,
    );
    expect(readFileSync(generatedPath, "utf8")).toBe(staleContent);
  });

  it("fails closed when locale catalog discovery cannot run git", () => {
    expect(() =>
      listTrackedLocaleModulePaths("opaque-root", {
        execGit() {
          throw new Error("synthetic git outage");
        },
      }),
    ).toThrow(/Failed to discover tracked localization modules with git ls-files: synthetic git outage/);
  });

  it("fails closed when an optional localeCatalogs declaration has the wrong shape", async () => {
    const fixture = await createMetadataFixture();
    const manifestPath = path.join(fixture.rootDir, "bounded-contexts", "catalog", "context.json");
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    manifest.localeCatalogs = "contracts/localization/locales/en/example.ts";
    writeJson(manifestPath, manifest);

    expect(() => syncWorkspaceMetadata(fixture)).toThrow(
      /Invalid localeCatalogs .* expected an array of tracked module paths/,
    );
  });

  it("fails closed when a localeCatalogs declaration names no discovered module", async () => {
    const fixture = await createMetadataFixture();
    const manifestPath = path.join(fixture.rootDir, "bounded-contexts", "catalog", "context.json");
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    manifest.localeCatalogs = ["contracts/localization/locales/en/absent.ts"];
    writeJson(manifestPath, manifest);

    expect(() => syncWorkspaceMetadata(fixture)).toThrow(
      /Invalid localeCatalogs entry .* no tracked or generated locale module exists/,
    );
  });

  it("refuses to overwrite a tracked namespace module that is not generated", async () => {
    const fixture = await createMetadataFixture();
    syncWorkspaceMetadata(fixture);
    const outputPath = path.join(fixture.rootDir, "contracts", "localization", "locales", "en.ts");
    writeFileSync(outputPath, 'export const manual = { "manual.key": "Manual" } as const;\n', "utf8");

    expect(() =>
      syncWorkspaceMetadata({
        ...fixture,
        trackedLocaleFiles: [...fixture.trackedLocaleFiles, "contracts/localization/locales/en.ts"],
      }),
    ).toThrow(/Tracked localization merge .* is not a generated artifact; refusing to overwrite it/);
  });
});

describe("localization catalog collision detection", () => {
  it("names the duplicate key and both owners for syntax-diverse modules at arbitrary paths", () => {
    const first = analyzeLocaleCatalogModule({
      filePath: "opaque/quartz.ts",
      ownerLabel: "owner-one",
      source: 'export const violet = { "shared.key": "First" } as const;',
    });
    const second = analyzeLocaleCatalogModule({
      filePath: "strange/sibling.ts",
      ownerLabel: "owner-two",
      source: 'const amber = { ["shared.key" as const]: "Second" } as const;\nexport { amber as surface };',
    });

    expect(() => assertNoLocaleCatalogKeyCollisions([first, second])).toThrow(
      /Duplicate localization key "shared\.key".*"opaque\/quartz\.ts" \(owner: owner-one\).*"strange\/sibling\.ts" \(owner: owner-two\)/,
    );
  });
});
