// Generated by scripts/generate-deployable-runtimes.mjs. Do not edit by hand.

import { collectProjectors } from "@chase-sets/bounded-context-runtime";
import type { PgTransactionalPool } from "@chase-sets/event-core-postgres";
import { module as identityModule } from "@chase-sets/identity";
import { module as authModule } from "@chase-sets/auth";
import { createIdentityBootstrapPort, createIdentityUserDirectoryPort, createIdentityMembershipPort, createIdentityInvitationPort, createIdentityProvisioningPort } from "@chase-sets/identity/integration";

export type ContextRuntimeServices = Readonly<{
  identity: ReturnType<typeof identityModule.createServices>;
  auth: ReturnType<typeof authModule.createServices>;
}>;

export type ContextRuntimeHostPorts = Readonly<Record<string, never>>;

export function createContextRuntime(
  pool: PgTransactionalPool,
  hostPorts: ContextRuntimeHostPorts = {} as ContextRuntimeHostPorts,
) {
  const services = {} as Record<string, unknown> as {
  identity: ReturnType<typeof identityModule.createServices>;
  auth: ReturnType<typeof authModule.createServices>;
  };

  services.identity = identityModule.createServices(pool, undefined);
  services.auth = authModule.createServices(pool, {
    identityBootstrap: createIdentityBootstrapPort(services.identity),
    identityUsers: createIdentityUserDirectoryPort(services.identity),
    identityMemberships: createIdentityMembershipPort(services.identity),
    identityInvitations: createIdentityInvitationPort(services.identity),
    identityProvisioning: createIdentityProvisioningPort(services.identity),
  });

  const mountedModules = [
    { module: identityModule, services: services.identity },
    { module: authModule, services: services.auth },
  ] as const;

  return {
    mountedModules,
    services: services as ContextRuntimeServices,
    projectors: collectProjectors([
    services.identity,
    services.auth,
    ]),
  };
}
