// Generated by scripts/generate-deployable-api-mounts.mjs. Do not edit by hand.

import type { ResolvedApiMount } from "@chase-sets/bounded-context-runtime";
import { resolveApiMounts as resolveIdentityApiMounts } from "@chase-sets/identity";

export function createContextApiMounts(
  services: Parameters<typeof resolveIdentityApiMounts>[0],
): readonly ResolvedApiMount[] {
  return resolveIdentityApiMounts(services);
}
