// Generated by scripts/generate-deployable-api-mounts.mjs. Do not edit by hand.

import { resolveModuleApiMounts, type ResolvedApiMount } from "@chase-sets/bounded-context-runtime";
import { module as AuthModule } from "@chase-sets/auth";
import { module as IdentityModule } from "@chase-sets/identity";

export function createContextApiMounts(
  services: {
  auth: ReturnType<typeof AuthModule.createServices>;
  identity: ReturnType<typeof IdentityModule.createServices>;
},
): readonly ResolvedApiMount[] {
  return [
    ...resolveModuleApiMounts(AuthModule, services.auth),
    ...resolveModuleApiMounts(IdentityModule, services.identity),
  ];
}
