// Generated by scripts/generate-deployable-runtimes.mjs. Do not edit by hand.

import { collectProjectors, resolveModuleProjectionGroups, resolveModuleSubscriptions } from "@chase-sets/bounded-context-runtime";
import type { PgTransactionalPool } from "@chase-sets/event-core-postgres";
import { module as authModule } from "@chase-sets/auth";
import { module as identityModule } from "@chase-sets/identity";

export type ContextRuntimePools = Readonly<{
  auth: PgTransactionalPool;
  identity: PgTransactionalPool;
}>;

export type ContextRuntimeServices = Readonly<{
  auth: ReturnType<typeof authModule.createServices>;
  identity: ReturnType<typeof identityModule.createServices>;
}>;

export type ContextRuntimeHostPorts = Readonly<Record<string, never>>;

export function createContextRuntime(
  pools: ContextRuntimePools,
  hostPorts: ContextRuntimeHostPorts = {} as ContextRuntimeHostPorts,
) {
  const services = {} as Record<string, unknown> as {
  auth: ReturnType<typeof authModule.createServices>;
  identity: ReturnType<typeof identityModule.createServices>;
  };

  services.auth = authModule.createServices(pools.auth, undefined);
  services.identity = identityModule.createServices(pools.identity, undefined);

  const mountedContexts = [
    {
      contextName: "auth",
      mountRole: "active",
      module: authModule,
      services: services.auth,
      pool: pools.auth,
      projectors: authModule.projectors(services.auth),
    },
    {
      contextName: "identity",
      mountRole: "active",
      module: identityModule,
      services: services.identity,
      pool: pools.identity,
      projectors: identityModule.projectors(services.identity),
    },
  ] as const;

  const mountedModules = [
    { module: authModule, services: services.auth },
    { module: identityModule, services: services.identity },
  ] as const;

  const subscriptionRunners = resolveModuleSubscriptions(mountedContexts);
  const projectionGroups = resolveModuleProjectionGroups(
    mountedContexts,
    subscriptionRunners,
  );

  return {
    mountedContexts,
    mountedModules,
    services: services as ContextRuntimeServices,
    projectors: collectProjectors([
    services.auth,
    services.identity,
    ]),
    projectionGroups,
    subscriptionRunners,
  };
}
