// Generated by scripts/generate-deployable-api-mounts.mjs. Do not edit by hand.

import type { ResolvedApiMount } from "@chase-sets/bounded-context-runtime";
import { resolveApiMounts as resolveAuthApiMounts } from "@chase-sets/auth";
import { resolveApiMounts as resolveIdentityApiMounts } from "@chase-sets/identity";

export function createContextApiMounts(
  services: {
  auth: Parameters<typeof resolveAuthApiMounts>[0];
  identity: Parameters<typeof resolveIdentityApiMounts>[0];
},
): readonly ResolvedApiMount[] {
  return [
    ...resolveAuthApiMounts(services.auth),
    ...resolveIdentityApiMounts(services.identity),
  ];
}
