export {
  ApiError as CatalogApiError,
  api as catalogApi,
  createCatalogApiClient,
} from "./support/shell-support/api/client";
export type { CatalogApiClientOptions } from "./support/shell-support/api/client";
export type {
  Blueprint,
  BlueprintDetail,
  BulkPublishCandidate,
  BulkPublishPreview,
  BulkPublishResult,
  CatalogItemDetail,
  CatalogItemListItem,
  CategoryDetail,
  CategoryListItem,
  Component,
  ComponentDetail,
  Dimension,
  DimensionDetail,
  DisplayTemplate,
  DisplayTemplateDetail,
  Field,
  ReferenceRecord,
  ReferenceType,
  BulkSourceObservationPromotionOutcome,
  BulkSourceObservationPromotionResult,
  SourceObservationIntegrationScope,
  SourceObservationPromotionPreview,
  SourceObservationPromotionScope,
  SourceObservationDetail,
  CatalogProviderProfileDryRunResult,
  CatalogProviderProfileVersionReview,
  SourceObservationListItem,
  ProviderScopeMappingCandidateSummary,
  ScopeCoverageMatrix,
  ScopeCoverageProviderRow,
  ScopeCoverageState,
  UnmappedScopeInboxGroup,
  UnmappedScopeInboxReadModel,
} from "./support/client-support/contracts";
