// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

export * from "@chase-sets/identity/routes/admin/memberships-detail";
export { default } from "@chase-sets/identity/routes/admin/memberships-detail";
