// Generated by scripts/generate-deployable-shells.mjs. Do not edit by hand.

import type { NavigationItem } from "@chase-sets/design-system";

type ShellActor = Readonly<{
  permissions?: readonly string[];
}> | null | undefined;

type ShellContribution = Readonly<{
  key: string;
  label: string;
  icon: NavigationItem["icon"];
  href: string;
  order: number;
  visibility: "always" | "signed-in" | "signed-out";
  requiredPermissions: readonly string[];
}>;

function hasRequiredPermissions(
  actor: ShellActor,
  requiredPermissions: readonly string[],
) {
  if (requiredPermissions.length === 0) {
    return true;
  }

  const grantedPermissions = actor?.permissions ?? [];
  return requiredPermissions.every((permission) => grantedPermissions.includes(permission));
}

function isVisibleForActor(
  actor: ShellActor,
  contribution: ShellContribution,
) {
  if (contribution.visibility === "signed-in" && !actor) {
    return false;
  }

  if (contribution.visibility === "signed-out" && actor) {
    return false;
  }

  return hasRequiredPermissions(actor, contribution.requiredPermissions);
}

function resolveShellItems(
  contributions: readonly ShellContribution[],
  actor?: ShellActor,
): NavigationItem[] {
  return [...contributions]
    .filter((contribution) => isVisibleForActor(actor, contribution))
    .sort((left, right) =>
      left.order === right.order
        ? left.label.localeCompare(right.label)
        : left.order - right.order,
    )
    .map(({ key, label, icon, href }) => ({
      key,
      label,
      icon,
      href,
    }));
}

const BottomNavContributions = [
  {
    key: "search",
    label: "Browse",
    icon: "search",
    href: "/search",
    order: 10,
    visibility: "always",
    requiredPermissions: [],
  },
  {
    key: "inventory",
    label: "Inventory",
    icon: "package",
    href: "/account/inventory",
    order: 100,
    visibility: "signed-in",
    requiredPermissions: ["inventory.view"],
  },
  {
    key: "cart",
    label: "Cart",
    icon: "cart",
    href: "/account/cart",
    order: 110,
    visibility: "signed-in",
    requiredPermissions: ["orders.manage"],
  },
  {
    key: "listings",
    label: "Listings",
    icon: "package",
    href: "/account/listings",
    order: 120,
    visibility: "signed-in",
    requiredPermissions: ["listings.view"],
  },
  {
    key: "market-offers",
    label: "Market Offers",
    icon: "package",
    href: "/account/market-offers",
    order: 130,
    visibility: "signed-in",
    requiredPermissions: ["offers.view", "listings.view"],
  },
  {
    key: "offers",
    label: "Offers",
    icon: "package",
    href: "/account/offers",
    order: 140,
    visibility: "signed-in",
    requiredPermissions: ["offers.view"],
  },
  {
    key: "shipments",
    label: "Shipments",
    icon: "package",
    href: "/account/shipments",
    order: 150,
    visibility: "signed-in",
    requiredPermissions: ["fulfillment.view"],
  },
  {
    key: "reputation",
    label: "Reputation",
    icon: "star",
    href: "/account/reputation",
    order: 160,
    visibility: "signed-in",
    requiredPermissions: ["reputation.view"],
  },
  {
    key: "orders",
    label: "Orders",
    icon: "cart",
    href: "/account/orders",
    order: 170,
    visibility: "signed-in",
    requiredPermissions: ["orders.view"],
  },
  {
    key: "fulfillment",
    label: "Fulfillment",
    icon: "package",
    href: "/account/fulfillment",
    order: 180,
    visibility: "signed-in",
    requiredPermissions: ["fulfillment.view", "fulfillment.manage"],
  },
  {
    key: "sales",
    label: "Sales",
    icon: "package",
    href: "/account/sales",
    order: 190,
    visibility: "signed-in",
    requiredPermissions: ["orders.view", "listings.view"],
  },
  {
    key: "account",
    label: "Account",
    icon: "user",
    href: "/account",
    order: 200,
    visibility: "signed-in",
    requiredPermissions: ["accounts.view"],
  },
  {
    key: "sign-in",
    label: "Sign In",
    icon: "user",
    href: "/sign-in",
    order: 900,
    visibility: "signed-out",
    requiredPermissions: [],
  },
  {
    key: "register",
    label: "Register",
    icon: "plus",
    href: "/register",
    order: 910,
    visibility: "signed-out",
    requiredPermissions: [],
  },
] satisfies readonly ShellContribution[];

const TopNavContributions = [
  {
    key: "search",
    label: "Browse",
    icon: "search",
    href: "/search",
    order: 10,
    visibility: "always",
    requiredPermissions: [],
  },
  {
    key: "inventory",
    label: "Inventory",
    icon: "package",
    href: "/account/inventory",
    order: 100,
    visibility: "signed-in",
    requiredPermissions: ["inventory.view"],
  },
  {
    key: "cart",
    label: "Cart",
    icon: "cart",
    href: "/account/cart",
    order: 110,
    visibility: "signed-in",
    requiredPermissions: ["orders.manage"],
  },
  {
    key: "listings",
    label: "Listings",
    icon: "package",
    href: "/account/listings",
    order: 120,
    visibility: "signed-in",
    requiredPermissions: ["listings.view"],
  },
  {
    key: "market-offers",
    label: "Market Offers",
    icon: "package",
    href: "/account/market-offers",
    order: 130,
    visibility: "signed-in",
    requiredPermissions: ["offers.view", "listings.view"],
  },
  {
    key: "offers",
    label: "Offers",
    icon: "package",
    href: "/account/offers",
    order: 140,
    visibility: "signed-in",
    requiredPermissions: ["offers.view"],
  },
  {
    key: "shipments",
    label: "Shipments",
    icon: "package",
    href: "/account/shipments",
    order: 150,
    visibility: "signed-in",
    requiredPermissions: ["fulfillment.view"],
  },
  {
    key: "reputation",
    label: "Reputation",
    icon: "star",
    href: "/account/reputation",
    order: 160,
    visibility: "signed-in",
    requiredPermissions: ["reputation.view"],
  },
  {
    key: "orders",
    label: "Orders",
    icon: "cart",
    href: "/account/orders",
    order: 170,
    visibility: "signed-in",
    requiredPermissions: ["orders.view"],
  },
  {
    key: "fulfillment",
    label: "Fulfillment",
    icon: "package",
    href: "/account/fulfillment",
    order: 180,
    visibility: "signed-in",
    requiredPermissions: ["fulfillment.view", "fulfillment.manage"],
  },
  {
    key: "sales",
    label: "Sales",
    icon: "package",
    href: "/account/sales",
    order: 190,
    visibility: "signed-in",
    requiredPermissions: ["orders.view", "listings.view"],
  },
  {
    key: "account",
    label: "Account",
    icon: "user",
    href: "/account",
    order: 200,
    visibility: "signed-in",
    requiredPermissions: ["accounts.view"],
  },
  {
    key: "sign-in",
    label: "Sign In",
    icon: "user",
    href: "/sign-in",
    order: 900,
    visibility: "signed-out",
    requiredPermissions: [],
  },
  {
    key: "register",
    label: "Register",
    icon: "plus",
    href: "/register",
    order: 910,
    visibility: "signed-out",
    requiredPermissions: [],
  },
] satisfies readonly ShellContribution[];

export function createMarketplaceBottomNavItems(actor?: ShellActor): NavigationItem[] {
  return resolveShellItems(BottomNavContributions, actor);
}

export function createMarketplaceTopNavItems(actor?: ShellActor): NavigationItem[] {
  return resolveShellItems(TopNavContributions, actor);
}
