export const tcgplayerAutomationResponseFixtures = {
  productLines: [
    {
      productLineId: 3,
      productLineName: "Pokemon",
      productLineUrlName: "pokemon",
      isDirect: true,
    },
  ],
  catalogSetNames: {
    errors: [],
    results: [
      {
        setNameId: 2387,
        categoryId: 3,
        name: "Prismatic Evolutions",
        cleanSetName: "Prismatic Evolutions",
        urlName: "prismatic-evolutions",
        abbreviation: "PRE",
        releaseDate: "2025-01-17T00:00:00",
        isSupplemental: false,
        active: true,
      },
    ],
  },
  productSearch: {
    errors: [],
    results: [
      {
        aggregations: {
          cardType: [{ urlValue: "pokemon", isActive: false, value: "Pokemon", count: 1 }],
          stage: [{ urlValue: "basic", isActive: false, value: "Basic", count: 1 }],
          rarityName: [
            { urlValue: "special-illustration-rare", isActive: false, value: "Special Illustration Rare", count: 1 },
          ],
          setName: [{ urlValue: "prismatic-evolutions", isActive: true, value: "Prismatic Evolutions", count: 1 }],
          productTypeName: [{ urlValue: "cards", isActive: false, value: "Cards", count: 1 }],
          productLineName: [{ urlValue: "pokemon", isActive: true, value: "Pokemon", count: 1 }],
          condition: [{ urlValue: "near-mint", isActive: false, value: "Near Mint", count: 4 }],
          language: [{ urlValue: "english", isActive: false, value: "English", count: 4 }],
          printing: [{ urlValue: "holofoil", isActive: false, value: "Holofoil", count: 4 }],
        },
        results: [
          {
            listings: [
              {
                customData: { images: [], title: "Seller listing title", description: "Seller listing note" },
                directProduct: false,
                goldSeller: true,
                listingId: 99112233,
                channelId: 0,
                conditionId: 1,
                verifiedSeller: true,
                directInventory: 0,
                rankedShippingPrice: 0,
                productId: 610001,
                printing: "Holofoil",
                languageAbbreviation: "EN",
                sellerName: "redacted-seller",
                sellerPrograms: [],
                forwardFreight: false,
                sellerShippingPrice: 0,
                language: "English",
                shippingPrice: 0,
                condition: "Near Mint",
                languageId: 1,
                score: 1,
                directSeller: false,
                productConditionId: 9001001,
                sellerId: "seller-redacted",
                listingType: "ListingWithoutPhotos",
                sellerRating: 100,
                sellerSales: "10000+",
                quantity: 2,
                sellerKey: "seller-key-redacted",
                price: 199.99,
              },
            ],
            shippingCategoryId: 1,
            duplicate: false,
            productLineUrlName: "pokemon",
            productUrlName: "pokemon-prismatic-evolutions-eevee-ex",
            productTypeId: 10,
            productTypeName: "Cards",
            rarityName: "Special Illustration Rare",
            sealed: false,
            marketPrice: 184.22,
            customAttributes: {
              description: "A representative card description.",
              stage: "Basic",
              releaseDate: "2025-01-17",
              number: "167/131",
              cardType: ["Pokemon"],
              rarityDbName: "Special Illustration Rare",
              flavorText: "Representative flavor text.",
              hp: "210",
              attack1: "Rainbow DNA",
              attack2: "Quartz Shine",
              attack3: null,
              attack4: null,
            },
            productName: "Eevee ex",
            setId: 2387,
            productId: 610001,
            score: 42.5,
            setName: "Prismatic Evolutions",
            foilOnly: true,
            setUrlName: "PRE",
            sellerListable: true,
            totalListings: 4,
            productLineId: 3,
            productStatusId: 1,
            productLineName: "Pokemon",
            maxFulfillableQuantity: 2,
            lowestPrice: 199.99,
            lowestPriceWithShipping: 199.99,
          },
        ],
        algorithm: "sales_exp_fields_experiment",
        searchType: "product",
        didYouMean: {},
        totalResults: 1,
        resultId: "search-result-redacted",
      },
    ],
  },
  productDetail: {
    customListings: 0,
    shippingCategoryId: 1,
    duplicate: false,
    productLineUrlName: "pokemon",
    productTypeName: "Cards",
    productUrlName: "pokemon-prismatic-evolutions-eevee-ex",
    productTypeId: 10,
    rarityName: "Special Illustration Rare",
    sealed: false,
    marketPrice: 184.22,
    customAttributes: {
      description: "A representative product description.",
      attack2: "Quartz Shine",
      stage: "Basic",
      detailNote: "Representative detail note.",
      energyType: ["Colorless"],
      releaseDate: "2025-01-17",
      number: "167/131",
      cardType: ["Pokemon"],
      retreatCost: "1",
      cardTypeB: "Pokemon",
      resistance: null,
      rarityDbName: "Special Illustration Rare",
      weakness: null,
      flavorText: "Representative flavor text.",
      attack1: "Rainbow DNA",
      hp: "210",
      attack3: null,
      attack4: null,
    },
    lowestPriceWithShipping: 199.99,
    productName: "Eevee ex",
    setId: 2387,
    setCode: "PRE",
    productId: 610001,
    imageCount: 1,
    score: 42.5,
    setName: "Prismatic Evolutions",
    sellers: 4,
    foilOnly: true,
    setUrlName: "PRE",
    sellerListable: true,
    productLineId: 3,
    productStatusId: 1,
    productLineName: "Pokemon",
    maxFulfillableQuantity: 2,
    normalOnly: false,
    listings: 4,
    lowestPrice: 199.99,
    medianPrice: null,
    formattedAttributes: {
      "Card Number / Rarity": "167/131 / Special Illustration Rare",
      "Card Type / HP / Stage": "Pokemon / 210 / Basic",
      "Attack 1": "Rainbow DNA",
      "Attack 2": "Quartz Shine",
      "Weakness / Resistance / Retreat Cost": "None / None / 1",
      Artist: "Naoki Saito",
    },
    skus: [
      {
        sku: 7001001,
        condition: "Near Mint",
        variant: "Holofoil",
        language: "English",
      },
      {
        sku: 7001002,
        condition: "Lightly Played",
        variant: "Holofoil",
        language: "English",
      },
    ],
  },
} as const;
