// Generated by scripts/generate-deployable-shells.mjs. Do not edit by hand.

import type { NavigationItem } from "@chase-sets/design-system";

type ShellActor = Readonly<{
  permissions?: readonly string[];
}> | null | undefined;

type ShellContribution = Readonly<{
  key: string;
  label: string;
  icon: NavigationItem["icon"];
  href: string;
  order: number;
  visibility: "always" | "signed-in" | "signed-out";
  requiredPermissions: readonly string[];
}>;

function hasRequiredPermissions(
  actor: ShellActor,
  requiredPermissions: readonly string[],
) {
  if (requiredPermissions.length === 0) {
    return true;
  }

  const grantedPermissions = actor?.permissions ?? [];
  return requiredPermissions.every((permission) => grantedPermissions.includes(permission));
}

function isVisibleForActor(
  actor: ShellActor,
  contribution: ShellContribution,
) {
  if (contribution.visibility === "signed-in" && !actor) {
    return false;
  }

  if (contribution.visibility === "signed-out" && actor) {
    return false;
  }

  return hasRequiredPermissions(actor, contribution.requiredPermissions);
}

function resolveShellItems(
  contributions: readonly ShellContribution[],
  actor?: ShellActor,
): NavigationItem[] {
  return [...contributions]
    .filter((contribution) => isVisibleForActor(actor, contribution))
    .sort((left, right) =>
      left.order === right.order
        ? left.label.localeCompare(right.label)
        : left.order - right.order,
    )
    .map(({ key, label, icon, href }) => ({
      key,
      label,
      icon,
      href,
    }));
}

const PrimaryNavContributions = [
  {
    key: "dimensions",
    label: "Dimensions",
    icon: "spark",
    href: "/dimensions",
    order: 10,
    visibility: "signed-in",
    requiredPermissions: [],
  },
  {
    key: "fields",
    label: "Fields",
    icon: "edit",
    href: "/fields",
    order: 20,
    visibility: "signed-in",
    requiredPermissions: [],
  },
  {
    key: "components",
    label: "Components",
    icon: "package",
    href: "/components",
    order: 30,
    visibility: "signed-in",
    requiredPermissions: [],
  },
  {
    key: "blueprints",
    label: "Blueprints",
    icon: "copy",
    href: "/blueprints",
    order: 40,
    visibility: "signed-in",
    requiredPermissions: [],
  },
  {
    key: "categories",
    label: "Categories",
    icon: "filter",
    href: "/categories",
    order: 50,
    visibility: "signed-in",
    requiredPermissions: [],
  },
  {
    key: "catalog-items",
    label: "Catalog Items",
    icon: "dashboard",
    href: "/catalog-items",
    order: 60,
    visibility: "signed-in",
    requiredPermissions: [],
  },
] satisfies readonly ShellContribution[];

export function createCatalogAdminPrimaryNavItems(actor?: ShellActor): NavigationItem[] {
  return resolveShellItems(PrimaryNavContributions, actor);
}
