// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

import { route, type RouteConfig } from "@react-router/dev/routes";

export const contextRoutes = [
  route("blueprints", "routes/blueprints.tsx"),
  route("blueprints/:id", "routes/blueprints-detail.tsx"),
  route("catalog-items", "routes/catalog-items.tsx"),
  route("catalog-items/:id", "routes/catalog-items-detail.tsx"),
  route("categories", "routes/categories.tsx"),
  route("categories/:id", "routes/categories-detail.tsx"),
  route("components", "routes/components.tsx"),
  route("components/:id", "routes/components-detail.tsx"),
  route("dimensions", "routes/dimensions.tsx"),
  route("dimensions/:id", "routes/dimensions-detail.tsx"),
  route("fields", "routes/fields.tsx"),
  route("fields/:id", "routes/fields-detail.tsx"),
] satisfies RouteConfig;
