// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/items/:id": {
    params: {
      "id": string;
    };
  };
  "/sign-in": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/account/select": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/team": {
    params: {};
  };
  "/account/security": {
    params: {};
  };
  "/account/consents": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/robots.txt" | "/sitemap.xml" | "/search" | "/items/:id" | "/sign-in" | "/register" | "/account/select" | "/account" | "/account/team" | "/account/security" | "/account/consents";
  };
  "routes/robots.ts": {
    id: "routes/robots";
    page: "/robots.txt";
  };
  "routes/sitemap.ts": {
    id: "routes/sitemap";
    page: "/sitemap.xml";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/search" | "/items/:id" | "/sign-in" | "/register" | "/account/select" | "/account" | "/account/team" | "/account/security" | "/account/consents";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/item-detail.tsx": {
    id: "routes/item-detail";
    page: "/items/:id";
  };
  "routes/sign-in.tsx": {
    id: "routes/sign-in";
    page: "/sign-in";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/account-select.tsx": {
    id: "routes/account-select";
    page: "/account/select";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account";
  };
  "routes/account-team.tsx": {
    id: "routes/account-team";
    page: "/account/team";
  };
  "routes/account-security.tsx": {
    id: "routes/account-security";
    page: "/account/security";
  };
  "routes/account-consents.tsx": {
    id: "routes/account-consents";
    page: "/account/consents";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/robots": typeof import("./app/routes/robots.ts");
  "routes/sitemap": typeof import("./app/routes/sitemap.ts");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/item-detail": typeof import("./app/routes/item-detail.tsx");
  "routes/sign-in": typeof import("./app/routes/sign-in.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/account-select": typeof import("./app/routes/account-select.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/account-team": typeof import("./app/routes/account-team.tsx");
  "routes/account-security": typeof import("./app/routes/account-security.tsx");
  "routes/account-consents": typeof import("./app/routes/account-consents.tsx");
};