// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/favicon.svg": {
    params: {};
  };
  "/favicon.ico": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/account/select": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-out": {
    params: {};
  };
  "/items/:id": {
    params: {
      "id": string;
    };
  };
  "/search": {
    params: {};
  };
  "/account/fulfillment": {
    params: {};
  };
  "/account/fulfillment/:shipmentId": {
    params: {
      "shipmentId": string;
    };
  };
  "/account/shipments/:shipmentId": {
    params: {
      "shipmentId": string;
    };
  };
  "/account/shipments": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/consents": {
    params: {};
  };
  "/account/security": {
    params: {};
  };
  "/account/team": {
    params: {};
  };
  "/account/inventory": {
    params: {};
  };
  "/account/inventory/locations": {
    params: {};
  };
  "/account/inventory/records/:recordId": {
    params: {
      "recordId": string;
    };
  };
  "/account/listings/:listingId": {
    params: {
      "listingId": string;
    };
  };
  "/account/listings": {
    params: {};
  };
  "/account/market-offers/:offerId": {
    params: {
      "offerId": string;
    };
  };
  "/account/market-offers": {
    params: {};
  };
  "/account/offers/:offerId": {
    params: {
      "offerId": string;
    };
  };
  "/account/offers": {
    params: {};
  };
  "/account/cart": {
    params: {};
  };
  "/account/orders/:orderId": {
    params: {
      "orderId": string;
    };
  };
  "/account/orders": {
    params: {};
  };
  "/account/sales/:orderId": {
    params: {
      "orderId": string;
    };
  };
  "/account/sales": {
    params: {};
  };
  "/account/payments/:paymentId": {
    params: {
      "paymentId": string;
    };
  };
  "/account/payments/new": {
    params: {};
  };
  "/account/orders/:orderId/review": {
    params: {
      "orderId": string;
    };
  };
  "/account/reviews/received": {
    params: {};
  };
  "/account/reputation": {
    params: {};
  };
  "/account/reviews/:reviewId": {
    params: {
      "reviewId": string;
    };
  };
  "/account/sales/:orderId/review": {
    params: {
      "orderId": string;
    };
  };
  "/account/reviews/written": {
    params: {};
  };
  "/account/payouts/:payoutId": {
    params: {
      "payoutId": string;
    };
  };
  "/account/payouts": {
    params: {};
  };
  "/account/settlement": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/favicon.svg" | "/favicon.ico" | "/.well-known/appspecific/com.chrome.devtools.json" | "/robots.txt" | "/sitemap.xml" | "/account/select" | "/register" | "/sign-in" | "/sign-out" | "/items/:id" | "/search" | "/account/fulfillment" | "/account/fulfillment/:shipmentId" | "/account/shipments/:shipmentId" | "/account/shipments" | "/account" | "/account/consents" | "/account/security" | "/account/team" | "/account/inventory" | "/account/inventory/locations" | "/account/inventory/records/:recordId" | "/account/listings/:listingId" | "/account/listings" | "/account/market-offers/:offerId" | "/account/market-offers" | "/account/offers/:offerId" | "/account/offers" | "/account/cart" | "/account/orders/:orderId" | "/account/orders" | "/account/sales/:orderId" | "/account/sales" | "/account/payments/:paymentId" | "/account/payments/new" | "/account/orders/:orderId/review" | "/account/reviews/received" | "/account/reputation" | "/account/reviews/:reviewId" | "/account/sales/:orderId/review" | "/account/reviews/written" | "/account/payouts/:payoutId" | "/account/payouts" | "/account/settlement";
  };
  "routes/favicon-svg.ts": {
    id: "routes/favicon-svg";
    page: "/favicon.svg";
  };
  "routes/favicon.ts": {
    id: "routes/favicon";
    page: "/favicon.ico";
  };
  "routes/chrome-devtools.ts": {
    id: "routes/chrome-devtools";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/robots.ts": {
    id: "routes/robots";
    page: "/robots.txt";
  };
  "routes/sitemap.ts": {
    id: "routes/sitemap";
    page: "/sitemap.xml";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/account/select" | "/register" | "/sign-in" | "/sign-out" | "/items/:id" | "/search" | "/account/fulfillment" | "/account/fulfillment/:shipmentId" | "/account/shipments/:shipmentId" | "/account/shipments" | "/account" | "/account/consents" | "/account/security" | "/account/team" | "/account/inventory" | "/account/inventory/locations" | "/account/inventory/records/:recordId" | "/account/listings/:listingId" | "/account/listings" | "/account/market-offers/:offerId" | "/account/market-offers" | "/account/offers/:offerId" | "/account/offers" | "/account/cart" | "/account/orders/:orderId" | "/account/orders" | "/account/sales/:orderId" | "/account/sales" | "/account/payments/:paymentId" | "/account/payments/new" | "/account/orders/:orderId/review" | "/account/reviews/received" | "/account/reputation" | "/account/reviews/:reviewId" | "/account/sales/:orderId/review" | "/account/reviews/written" | "/account/payouts/:payoutId" | "/account/payouts" | "/account/settlement";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "../../../bounded-contexts/auth/routes/marketplace/account-select.tsx": {
    id: "../../../bounded-contexts/auth/routes/marketplace/account-select";
    page: "/account/select";
  };
  "../../../bounded-contexts/auth/routes/marketplace/register.tsx": {
    id: "../../../bounded-contexts/auth/routes/marketplace/register";
    page: "/register";
  };
  "../../../bounded-contexts/auth/routes/marketplace/sign-in.tsx": {
    id: "../../../bounded-contexts/auth/routes/marketplace/sign-in";
    page: "/sign-in";
  };
  "../../../bounded-contexts/auth/routes/marketplace/sign-out.tsx": {
    id: "../../../bounded-contexts/auth/routes/marketplace/sign-out";
    page: "/sign-out";
  };
  "../../../bounded-contexts/discovery/routes/item-detail.tsx": {
    id: "../../../bounded-contexts/discovery/routes/item-detail";
    page: "/items/:id";
  };
  "../../../bounded-contexts/discovery/routes/search.tsx": {
    id: "../../../bounded-contexts/discovery/routes/search";
    page: "/search";
  };
  "../../../bounded-contexts/fulfillment/routes/marketplace/account-fulfillment.tsx": {
    id: "../../../bounded-contexts/fulfillment/routes/marketplace/account-fulfillment";
    page: "/account/fulfillment";
  };
  "../../../bounded-contexts/fulfillment/routes/marketplace/account-fulfillment-shipment.tsx": {
    id: "../../../bounded-contexts/fulfillment/routes/marketplace/account-fulfillment-shipment";
    page: "/account/fulfillment/:shipmentId";
  };
  "../../../bounded-contexts/fulfillment/routes/marketplace/account-shipment.tsx": {
    id: "../../../bounded-contexts/fulfillment/routes/marketplace/account-shipment";
    page: "/account/shipments/:shipmentId";
  };
  "../../../bounded-contexts/fulfillment/routes/marketplace/account-shipments.tsx": {
    id: "../../../bounded-contexts/fulfillment/routes/marketplace/account-shipments";
    page: "/account/shipments";
  };
  "../../../bounded-contexts/identity/routes/marketplace/account.tsx": {
    id: "../../../bounded-contexts/identity/routes/marketplace/account";
    page: "/account";
  };
  "../../../bounded-contexts/identity/routes/marketplace/account-consents.tsx": {
    id: "../../../bounded-contexts/identity/routes/marketplace/account-consents";
    page: "/account/consents";
  };
  "../../../bounded-contexts/identity/routes/marketplace/account-security.tsx": {
    id: "../../../bounded-contexts/identity/routes/marketplace/account-security";
    page: "/account/security";
  };
  "../../../bounded-contexts/identity/routes/marketplace/account-team.tsx": {
    id: "../../../bounded-contexts/identity/routes/marketplace/account-team";
    page: "/account/team";
  };
  "../../../bounded-contexts/inventory/routes/marketplace/account-inventory.tsx": {
    id: "../../../bounded-contexts/inventory/routes/marketplace/account-inventory";
    page: "/account/inventory";
  };
  "../../../bounded-contexts/inventory/routes/marketplace/account-inventory-locations.tsx": {
    id: "../../../bounded-contexts/inventory/routes/marketplace/account-inventory-locations";
    page: "/account/inventory/locations";
  };
  "../../../bounded-contexts/inventory/routes/marketplace/account-inventory-record.tsx": {
    id: "../../../bounded-contexts/inventory/routes/marketplace/account-inventory-record";
    page: "/account/inventory/records/:recordId";
  };
  "../../../bounded-contexts/marketplace/routes/account-listing.tsx": {
    id: "../../../bounded-contexts/marketplace/routes/account-listing";
    page: "/account/listings/:listingId";
  };
  "../../../bounded-contexts/marketplace/routes/account-listings.tsx": {
    id: "../../../bounded-contexts/marketplace/routes/account-listings";
    page: "/account/listings";
  };
  "../../../bounded-contexts/marketplace/routes/account-market-offer.tsx": {
    id: "../../../bounded-contexts/marketplace/routes/account-market-offer";
    page: "/account/market-offers/:offerId";
  };
  "../../../bounded-contexts/marketplace/routes/account-market-offers.tsx": {
    id: "../../../bounded-contexts/marketplace/routes/account-market-offers";
    page: "/account/market-offers";
  };
  "../../../bounded-contexts/marketplace/routes/account-offer.tsx": {
    id: "../../../bounded-contexts/marketplace/routes/account-offer";
    page: "/account/offers/:offerId";
  };
  "../../../bounded-contexts/marketplace/routes/account-offers.tsx": {
    id: "../../../bounded-contexts/marketplace/routes/account-offers";
    page: "/account/offers";
  };
  "../../../bounded-contexts/ordering/routes/account-cart.tsx": {
    id: "../../../bounded-contexts/ordering/routes/account-cart";
    page: "/account/cart";
  };
  "../../../bounded-contexts/ordering/routes/account-order.tsx": {
    id: "../../../bounded-contexts/ordering/routes/account-order";
    page: "/account/orders/:orderId";
  };
  "../../../bounded-contexts/ordering/routes/account-orders.tsx": {
    id: "../../../bounded-contexts/ordering/routes/account-orders";
    page: "/account/orders";
  };
  "../../../bounded-contexts/ordering/routes/account-sale.tsx": {
    id: "../../../bounded-contexts/ordering/routes/account-sale";
    page: "/account/sales/:orderId";
  };
  "../../../bounded-contexts/ordering/routes/account-sales.tsx": {
    id: "../../../bounded-contexts/ordering/routes/account-sales";
    page: "/account/sales";
  };
  "../../../bounded-contexts/payments/routes/marketplace/account-payment.tsx": {
    id: "../../../bounded-contexts/payments/routes/marketplace/account-payment";
    page: "/account/payments/:paymentId";
  };
  "../../../bounded-contexts/payments/routes/marketplace/account-payment-new.tsx": {
    id: "../../../bounded-contexts/payments/routes/marketplace/account-payment-new";
    page: "/account/payments/new";
  };
  "../../../bounded-contexts/reputation/routes/marketplace/account-order-review.tsx": {
    id: "../../../bounded-contexts/reputation/routes/marketplace/account-order-review";
    page: "/account/orders/:orderId/review";
  };
  "../../../bounded-contexts/reputation/routes/marketplace/account-received-reviews.tsx": {
    id: "../../../bounded-contexts/reputation/routes/marketplace/account-received-reviews";
    page: "/account/reviews/received";
  };
  "../../../bounded-contexts/reputation/routes/marketplace/account-reputation.tsx": {
    id: "../../../bounded-contexts/reputation/routes/marketplace/account-reputation";
    page: "/account/reputation";
  };
  "../../../bounded-contexts/reputation/routes/marketplace/account-review.tsx": {
    id: "../../../bounded-contexts/reputation/routes/marketplace/account-review";
    page: "/account/reviews/:reviewId";
  };
  "../../../bounded-contexts/reputation/routes/marketplace/account-sale-review.tsx": {
    id: "../../../bounded-contexts/reputation/routes/marketplace/account-sale-review";
    page: "/account/sales/:orderId/review";
  };
  "../../../bounded-contexts/reputation/routes/marketplace/account-written-reviews.tsx": {
    id: "../../../bounded-contexts/reputation/routes/marketplace/account-written-reviews";
    page: "/account/reviews/written";
  };
  "../../../bounded-contexts/settlement/routes/marketplace/account-payout.tsx": {
    id: "../../../bounded-contexts/settlement/routes/marketplace/account-payout";
    page: "/account/payouts/:payoutId";
  };
  "../../../bounded-contexts/settlement/routes/marketplace/account-payouts.tsx": {
    id: "../../../bounded-contexts/settlement/routes/marketplace/account-payouts";
    page: "/account/payouts";
  };
  "../../../bounded-contexts/settlement/routes/marketplace/account-settlement.tsx": {
    id: "../../../bounded-contexts/settlement/routes/marketplace/account-settlement";
    page: "/account/settlement";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/favicon-svg": typeof import("./app/routes/favicon-svg.ts");
  "routes/favicon": typeof import("./app/routes/favicon.ts");
  "routes/chrome-devtools": typeof import("./app/routes/chrome-devtools.ts");
  "routes/robots": typeof import("./app/routes/robots.ts");
  "routes/sitemap": typeof import("./app/routes/sitemap.ts");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "../../../bounded-contexts/auth/routes/marketplace/account-select": unknown;
  "../../../bounded-contexts/auth/routes/marketplace/register": unknown;
  "../../../bounded-contexts/auth/routes/marketplace/sign-in": unknown;
  "../../../bounded-contexts/auth/routes/marketplace/sign-out": unknown;
  "../../../bounded-contexts/discovery/routes/item-detail": unknown;
  "../../../bounded-contexts/discovery/routes/search": unknown;
  "../../../bounded-contexts/fulfillment/routes/marketplace/account-fulfillment": unknown;
  "../../../bounded-contexts/fulfillment/routes/marketplace/account-fulfillment-shipment": unknown;
  "../../../bounded-contexts/fulfillment/routes/marketplace/account-shipment": unknown;
  "../../../bounded-contexts/fulfillment/routes/marketplace/account-shipments": unknown;
  "../../../bounded-contexts/identity/routes/marketplace/account": unknown;
  "../../../bounded-contexts/identity/routes/marketplace/account-consents": unknown;
  "../../../bounded-contexts/identity/routes/marketplace/account-security": unknown;
  "../../../bounded-contexts/identity/routes/marketplace/account-team": unknown;
  "../../../bounded-contexts/inventory/routes/marketplace/account-inventory": unknown;
  "../../../bounded-contexts/inventory/routes/marketplace/account-inventory-locations": unknown;
  "../../../bounded-contexts/inventory/routes/marketplace/account-inventory-record": unknown;
  "../../../bounded-contexts/marketplace/routes/account-listing": unknown;
  "../../../bounded-contexts/marketplace/routes/account-listings": unknown;
  "../../../bounded-contexts/marketplace/routes/account-market-offer": unknown;
  "../../../bounded-contexts/marketplace/routes/account-market-offers": unknown;
  "../../../bounded-contexts/marketplace/routes/account-offer": unknown;
  "../../../bounded-contexts/marketplace/routes/account-offers": unknown;
  "../../../bounded-contexts/ordering/routes/account-cart": unknown;
  "../../../bounded-contexts/ordering/routes/account-order": unknown;
  "../../../bounded-contexts/ordering/routes/account-orders": unknown;
  "../../../bounded-contexts/ordering/routes/account-sale": unknown;
  "../../../bounded-contexts/ordering/routes/account-sales": unknown;
  "../../../bounded-contexts/payments/routes/marketplace/account-payment": unknown;
  "../../../bounded-contexts/payments/routes/marketplace/account-payment-new": unknown;
  "../../../bounded-contexts/reputation/routes/marketplace/account-order-review": unknown;
  "../../../bounded-contexts/reputation/routes/marketplace/account-received-reviews": unknown;
  "../../../bounded-contexts/reputation/routes/marketplace/account-reputation": unknown;
  "../../../bounded-contexts/reputation/routes/marketplace/account-review": unknown;
  "../../../bounded-contexts/reputation/routes/marketplace/account-sale-review": unknown;
  "../../../bounded-contexts/reputation/routes/marketplace/account-written-reviews": unknown;
  "../../../bounded-contexts/settlement/routes/marketplace/account-payout": unknown;
  "../../../bounded-contexts/settlement/routes/marketplace/account-payouts": unknown;
  "../../../bounded-contexts/settlement/routes/marketplace/account-settlement": unknown;
};