// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

import * as RouteModule from "@chase-sets/catalog/routes/admin/categories";

export const loader = RouteModule.loader;
export const meta = RouteModule.meta;
export default RouteModule.default;
