// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

export * from "@chase-sets/catalog/routes/admin/dimensions";
export { default } from "@chase-sets/catalog/routes/admin/dimensions";
