// Generated by scripts/generate-deployable-routes.mjs. Do not edit by hand.

export * from "@chase-sets/auth/routes/catalog-admin/sign-out";
export { default } from "@chase-sets/auth/routes/catalog-admin/sign-out";
