export const AUTH_BOOTSTRAP_TENANT_ID = "tnt_identity" as const;
export const AUTH_BOOTSTRAP_USER_ID = "usr_identity_system" as const;
export const AUTH_BOOTSTRAP_ACCOUNT_ID = "acc_identity_system" as const;

export const AUTH_PERMISSION_PRESETS = {
  paymentsOperator: ["orders.manage", "orders.view"],
  payoutsOperator: [
    "payouts.manage",
    "payouts.reconcile",
    "payouts.request",
    "payouts.setup",
    "payouts.view",
  ],
  payoutsViewer: ["payouts.view"],
} satisfies Readonly<Record<string, readonly string[]>>;

export const AUTH_ROLE_PERMISSIONS = {
  owner: [
    "accounts.manage",
    "accounts.view",
    "catalog.manage",
    "catalog.view",
    "fulfillment.manage",
    "fulfillment.view",
    "memberships.manage",
    "memberships.view",
    "inventory.manage",
    "inventory.view",
    "listings.manage",
    "listings.view",
    "offers.manage",
    "offers.view",
    "orders.manage",
    "orders.view",
    ...AUTH_PERMISSION_PRESETS.payoutsOperator,
    "reputation.manage",
    "reputation.view",
    "security.manage",
  ],
  manager: [
    "accounts.view",
    "catalog.manage",
    "catalog.view",
    "fulfillment.manage",
    "fulfillment.view",
    "memberships.manage",
    "memberships.view",
    "inventory.manage",
    "inventory.view",
    "listings.manage",
    "listings.view",
    "offers.manage",
    "offers.view",
    "orders.manage",
    "orders.view",
    ...AUTH_PERMISSION_PRESETS.payoutsOperator,
    "reputation.manage",
    "reputation.view",
  ],
  fulfillment: [
    "accounts.view",
    "fulfillment.manage",
    "fulfillment.view",
    "memberships.view",
    "inventory.view",
    "listings.view",
    "offers.view",
    "orders.view",
    "reputation.view",
  ],
  viewer: [
    "accounts.view",
    "fulfillment.view",
    "memberships.view",
    "inventory.view",
    "listings.view",
    "offers.view",
    "orders.view",
    ...AUTH_PERMISSION_PRESETS.payoutsViewer,
    "reputation.view",
  ],
} satisfies Readonly<Record<string, readonly string[]>>;
